/* Start of object g_AStatus_acms */

alter TABLE AStatusAccounts add

 [ComplianceConditionCode] varchar (2) NULL,
 [SpecialComment] varchar (2) NULL
 
GO

if exists (select * from sysobjects where 
 id = object_id('sp_AStatusAccounts_qsel') and sysstat & 0xf = 4)
drop procedure sp_AStatusAccounts_qsel
GO
CREATE PROCEDURE sp_AStatusAccounts_qsel(  @acctId int ) AS
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET QUOTED_IDENTIFIER ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;
SELECT
 [acctId],
 [ATID],
 [rowClassifier],
 [grpClassifier],
 [LAD],
 [LAPD],
 [NAD],
 [AccountBlob],
 [StatementDate],
 [parent01ATID],
 [parent01AID],
 [parent02ATID],
 [parent02AID],
 [parent03ATID],
 [parent03AID],
 [parent04ATID],
 [parent04AID],
 [parent05ATID],
 [parent05AID],
 [MerchantAID],
 [Priority],
 [StatusDescription],
 [PostingReason],
 [StatusAcctReport],
 [TransactionPosting],
 [Reissue_IssueAction],
 [AuthAction],
 [FinanceChargeAction],
 [WaiveLateChargeAction],
 [WaiveMbrshipFeeAction],
 [WaiveOverLimitFeeAction],
 [WaiveNSFAction],
 [StatementAction],
 [RevolvingPaymentAction],
 [InsCancellationAction],
 [CreditBureauRptgAction],
 [CreditBureauStatus],
 [CheckOTB],
 [CollectionFlagsbyStatus],
 [StatementDelivery],
 [WaiveMinDue],
 [WaiveInsPremium],
 [SetDunSuppress],
 [EligibleForInsurance],
 [lastupdate],
 [ASResActionCode],
 [ASCCaseActionCode],
 [ACOverridePriority],
 [LoyaltyPointsAccumulation],
 [Email],
 [GenerateSMS],
 [GenerateLetter],
 [LoadAuthAction],
 [AuthActionVisa],
 [AuthActionDiscover],
 [AuthActionPrivateLabel],
 [ResponseCodeVisa],
 [ResponseCodeMC],
 [ResponseCodeDiscover],
 [ResponseCodePrivateLabel],
 [LoadAuthActionVisa],
 [LoadAuthActionDiscover],
 [LoadAuthActionPrivateLabel],
 [LoadResponseCodeVISA],
 [LoadResponseCodeMC],
 [LoadResponseCodeDiscover],
 [LoadResponseCodePrivateLabel],
 [tpyNAD],
 [tpyLAD],
 [tpyBlob],
 [WaiveLateChargeFor],
 [WaiveLateChargeFrom],
 [WaiveMbrshipFeeFor],
 [WaiveMbrshipFeeFrom],
 [WaiveOverLimitFeeFor],
 [WaiveOverLimitFeeFrom],
 [WaiveNSFFor],
 [WaiveNSFFrom],
 [WaiveMinDueFor],
 [WaiveMinDueFrom],
 [WaiveInsPremiumFor],
 [WaiveInsPremiumFrom],
 [WaiveInterest],
 [WaiveInterestFor],
 [WaiveInterestFrom],
 [WaiveAnnualChgAction],
 [WaiveAnnualChgFor],
 [WaiveAnnualChgFrom],
 [WaiveServiceFeeAction],
 [WaiveServiceFeeFor],
 [WaiveServiceFeeFrom],
 [WaiveTransactionFeeAction],
 [WaiveTransactionFeeFor],
 [WaiveTransactionFeeFrom],
 [WaiveCardFeeAction],
 [WaiveCardFeeFor],
 [WaiveCardFeeFrom],
 [WaiveAuthFeeAction],
 [WaiveAuthFeeFor],
 [WaiveAuthFeeFrom],
 [WaiveMessageFeeAction],
 [WaiveMessageFeeFor],
 [WaiveMessageFeeFrom],
 [CBRStatusGroup],
 [ExcludeFromCBR],
 [ComplianceConditionCode],
 [SpecialComment],
 [HoldStatement],
 [SelfServiceAccess],
 [PO_ASCheckOTB],
 [PO_ASCBRAction],
 [PO_ASCBureauStatus],
 [PO_ASEligibikityForInsurance],
 [PO_FinanceChargeAct],
 [PO_ASInsCancellationAct],
 [PO_LoyaltyPointsAcc],
 [PO_ReissueOrIssue],
 [PO_ASPostingReason],
 [PO_ASRevolvingPaymentAction],
 [PO_ASStatementAction],
 [PO_ASTransactionPosting],
 [PO_deHoldStatement],
 [PO_AsStatusAccRpt],
 [PO_ASWLateChargeAct],
 [PO_ASWMembFeeAct],
 [PO_ASWOverLimFeeAct],
 [PO_ASWNSFAction],
 [PO_ASStatementDelivery],
 [PO_ASWaiveMinDue],
 [PO_ASWaiveInterest],
 [PO_ASWaiveInsPremium],
 [PO_ASWaiveTxnFeeAct],
 [PO_ASWaiveAuthFeeAct],
 [PO_ASWaiveCardFeeAct],
 [PO_ASWAnnualChgAct],
 [PO_ASWMessageFeeAct],
 [PO_ASWServiceFeeAct],
 [LoyaltyDebits],
 [SchedulePayments]
FROM DBO.AStatusAccounts
WHERE 
   [acctId] = @acctId 
GO
grant execute on sp_AStatusAccounts_qsel to public 
GO

if exists (select * from sysobjects where 
 id = object_id('sp_AStatusAccounts_qslk') and sysstat & 0xf = 4)
drop procedure sp_AStatusAccounts_qslk
GO
CREATE PROCEDURE sp_AStatusAccounts_qslk(  @acctId int ) AS
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET QUOTED_IDENTIFIER ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;
SELECT
 [acctId],
 [ATID],
 [rowClassifier],
 [grpClassifier],
 [LAD],
 [LAPD],
 [NAD],
 [AccountBlob],
 [StatementDate],
 [parent01ATID],
 [parent01AID],
 [parent02ATID],
 [parent02AID],
 [parent03ATID],
 [parent03AID],
 [parent04ATID],
 [parent04AID],
 [parent05ATID],
 [parent05AID],
 [MerchantAID],
 [Priority],
 [StatusDescription],
 [PostingReason],
 [StatusAcctReport],
 [TransactionPosting],
 [Reissue_IssueAction],
 [AuthAction],
 [FinanceChargeAction],
 [WaiveLateChargeAction],
 [WaiveMbrshipFeeAction],
 [WaiveOverLimitFeeAction],
 [WaiveNSFAction],
 [StatementAction],
 [RevolvingPaymentAction],
 [InsCancellationAction],
 [CreditBureauRptgAction],
 [CreditBureauStatus],
 [CheckOTB],
 [CollectionFlagsbyStatus],
 [StatementDelivery],
 [WaiveMinDue],
 [WaiveInsPremium],
 [SetDunSuppress],
 [EligibleForInsurance],
 [lastupdate],
 [ASResActionCode],
 [ASCCaseActionCode],
 [ACOverridePriority],
 [LoyaltyPointsAccumulation],
 [Email],
 [GenerateSMS],
 [GenerateLetter],
 [LoadAuthAction],
 [AuthActionVisa],
 [AuthActionDiscover],
 [AuthActionPrivateLabel],
 [ResponseCodeVisa],
 [ResponseCodeMC],
 [ResponseCodeDiscover],
 [ResponseCodePrivateLabel],
 [LoadAuthActionVisa],
 [LoadAuthActionDiscover],
 [LoadAuthActionPrivateLabel],
 [LoadResponseCodeVISA],
 [LoadResponseCodeMC],
 [LoadResponseCodeDiscover],
 [LoadResponseCodePrivateLabel],
 [tpyNAD],
 [tpyLAD],
 [tpyBlob],
 [WaiveLateChargeFor],
 [WaiveLateChargeFrom],
 [WaiveMbrshipFeeFor],
 [WaiveMbrshipFeeFrom],
 [WaiveOverLimitFeeFor],
 [WaiveOverLimitFeeFrom],
 [WaiveNSFFor],
 [WaiveNSFFrom],
 [WaiveMinDueFor],
 [WaiveMinDueFrom],
 [WaiveInsPremiumFor],
 [WaiveInsPremiumFrom],
 [WaiveInterest],
 [WaiveInterestFor],
 [WaiveInterestFrom],
 [WaiveAnnualChgAction],
 [WaiveAnnualChgFor],
 [WaiveAnnualChgFrom],
 [WaiveServiceFeeAction],
 [WaiveServiceFeeFor],
 [WaiveServiceFeeFrom],
 [WaiveTransactionFeeAction],
 [WaiveTransactionFeeFor],
 [WaiveTransactionFeeFrom],
 [WaiveCardFeeAction],
 [WaiveCardFeeFor],
 [WaiveCardFeeFrom],
 [WaiveAuthFeeAction],
 [WaiveAuthFeeFor],
 [WaiveAuthFeeFrom],
 [WaiveMessageFeeAction],
 [WaiveMessageFeeFor],
 [WaiveMessageFeeFrom],
 [CBRStatusGroup],
 [ExcludeFromCBR],
 [ComplianceConditionCode],
 [SpecialComment],
 [HoldStatement],
 [SelfServiceAccess],
 [PO_ASCheckOTB],
 [PO_ASCBRAction],
 [PO_ASCBureauStatus],
 [PO_ASEligibikityForInsurance],
 [PO_FinanceChargeAct],
 [PO_ASInsCancellationAct],
 [PO_LoyaltyPointsAcc],
 [PO_ReissueOrIssue],
 [PO_ASPostingReason],
 [PO_ASRevolvingPaymentAction],
 [PO_ASStatementAction],
 [PO_ASTransactionPosting],
 [PO_deHoldStatement],
 [PO_AsStatusAccRpt],
 [PO_ASWLateChargeAct],
 [PO_ASWMembFeeAct],
 [PO_ASWOverLimFeeAct],
 [PO_ASWNSFAction],
 [PO_ASStatementDelivery],
 [PO_ASWaiveMinDue],
 [PO_ASWaiveInterest],
 [PO_ASWaiveInsPremium],
 [PO_ASWaiveTxnFeeAct],
 [PO_ASWaiveAuthFeeAct],
 [PO_ASWaiveCardFeeAct],
 [PO_ASWAnnualChgAct],
 [PO_ASWMessageFeeAct],
 [PO_ASWServiceFeeAct],
 [LoyaltyDebits],
 [SchedulePayments]
FROM DBO.AStatusAccounts with (updlock)
WHERE 
   [acctId] = @acctId 
GO
grant execute on sp_AStatusAccounts_qslk to public 
GO

if exists (select * from sysobjects where 
 id = object_id('sp_AStatusAccounts_sel') and sysstat & 0xf = 4)
drop procedure sp_AStatusAccounts_sel
GO
CREATE PROCEDURE sp_AStatusAccounts_sel AS
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET QUOTED_IDENTIFIER ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;

SELECT [acctId],
 [ATID],
 [rowClassifier],
 [grpClassifier],
 [LAD],
 [LAPD],
 [NAD],
 [AccountBlob],
 [StatementDate],
 [parent01ATID],
 [parent01AID],
 [parent02ATID],
 [parent02AID],
 [parent03ATID],
 [parent03AID],
 [parent04ATID],
 [parent04AID],
 [parent05ATID],
 [parent05AID],
 [MerchantAID],
 [Priority],
 [StatusDescription],
 [PostingReason],
 [StatusAcctReport],
 [TransactionPosting],
 [Reissue_IssueAction],
 [AuthAction],
 [FinanceChargeAction],
 [WaiveLateChargeAction],
 [WaiveMbrshipFeeAction],
 [WaiveOverLimitFeeAction],
 [WaiveNSFAction],
 [StatementAction],
 [RevolvingPaymentAction],
 [InsCancellationAction],
 [CreditBureauRptgAction],
 [CreditBureauStatus],
 [CheckOTB],
 [CollectionFlagsbyStatus],
 [StatementDelivery],
 [WaiveMinDue],
 [WaiveInsPremium],
 [SetDunSuppress],
 [EligibleForInsurance],
 [lastupdate],
 [ASResActionCode],
 [ASCCaseActionCode],
 [ACOverridePriority],
 [LoyaltyPointsAccumulation],
 [Email],
 [GenerateSMS],
 [GenerateLetter],
 [LoadAuthAction],
 [AuthActionVisa],
 [AuthActionDiscover],
 [AuthActionPrivateLabel],
 [ResponseCodeVisa],
 [ResponseCodeMC],
 [ResponseCodeDiscover],
 [ResponseCodePrivateLabel],
 [LoadAuthActionVisa],
 [LoadAuthActionDiscover],
 [LoadAuthActionPrivateLabel],
 [LoadResponseCodeVISA],
 [LoadResponseCodeMC],
 [LoadResponseCodeDiscover],
 [LoadResponseCodePrivateLabel],
 [tpyNAD],
 [tpyLAD],
 [tpyBlob],
 [WaiveLateChargeFor],
 [WaiveLateChargeFrom],
 [WaiveMbrshipFeeFor],
 [WaiveMbrshipFeeFrom],
 [WaiveOverLimitFeeFor],
 [WaiveOverLimitFeeFrom],
 [WaiveNSFFor],
 [WaiveNSFFrom],
 [WaiveMinDueFor],
 [WaiveMinDueFrom],
 [WaiveInsPremiumFor],
 [WaiveInsPremiumFrom],
 [WaiveInterest],
 [WaiveInterestFor],
 [WaiveInterestFrom],
 [WaiveAnnualChgAction],
 [WaiveAnnualChgFor],
 [WaiveAnnualChgFrom],
 [WaiveServiceFeeAction],
 [WaiveServiceFeeFor],
 [WaiveServiceFeeFrom],
 [WaiveTransactionFeeAction],
 [WaiveTransactionFeeFor],
 [WaiveTransactionFeeFrom],
 [WaiveCardFeeAction],
 [WaiveCardFeeFor],
 [WaiveCardFeeFrom],
 [WaiveAuthFeeAction],
 [WaiveAuthFeeFor],
 [WaiveAuthFeeFrom],
 [WaiveMessageFeeAction],
 [WaiveMessageFeeFor],
 [WaiveMessageFeeFrom],
 [CBRStatusGroup],
 [ExcludeFromCBR],
 [ComplianceConditionCode],
 [SpecialComment],
 [HoldStatement],
 [SelfServiceAccess],
 [PO_ASCheckOTB],
 [PO_ASCBRAction],
 [PO_ASCBureauStatus],
 [PO_ASEligibikityForInsurance],
 [PO_FinanceChargeAct],
 [PO_ASInsCancellationAct],
 [PO_LoyaltyPointsAcc],
 [PO_ReissueOrIssue],
 [PO_ASPostingReason],
 [PO_ASRevolvingPaymentAction],
 [PO_ASStatementAction],
 [PO_ASTransactionPosting],
 [PO_deHoldStatement],
 [PO_AsStatusAccRpt],
 [PO_ASWLateChargeAct],
 [PO_ASWMembFeeAct],
 [PO_ASWOverLimFeeAct],
 [PO_ASWNSFAction],
 [PO_ASStatementDelivery],
 [PO_ASWaiveMinDue],
 [PO_ASWaiveInterest],
 [PO_ASWaiveInsPremium],
 [PO_ASWaiveTxnFeeAct],
 [PO_ASWaiveAuthFeeAct],
 [PO_ASWaiveCardFeeAct],
 [PO_ASWAnnualChgAct],
 [PO_ASWMessageFeeAct],
 [PO_ASWServiceFeeAct],
 [LoyaltyDebits],
 [SchedulePayments]
FROM DBO.AStatusAccounts WITH (NOLOCK)
GO

grant execute on sp_AStatusAccounts_sel to public 
GO

if exists (select * from sysobjects where 
 id = object_id('sp_AStatusAccounts_del') and sysstat & 0xf = 4)
drop procedure sp_AStatusAccounts_del
GO
CREATE PROCEDURE sp_AStatusAccounts_del(  @acctId int ) AS
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET QUOTED_IDENTIFIER ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;
DELETE FROM DBO.AStatusAccounts
WHERE 
   [acctId] = @acctId 
GO
grant execute on sp_AStatusAccounts_del to public 
GO


if exists (select * from sysobjects where 
 id = object_id('sp_AStatusAccounts_upd') and sysstat & 0xf = 4)
drop procedure sp_AStatusAccounts_upd
GO
CREATE PROCEDURE sp_AStatusAccounts_upd  @acctId int,
  @ATID int,
  @rowClassifier char (16),
  @grpClassifier char (16),
  @LAD datetime,
  @LAPD datetime,
  @NAD datetime,
  @AccountBlob text,
  @StatementDate datetime,
  @parent01ATID int,
  @parent01AID int,
  @parent02ATID int,
  @parent02AID int,
  @parent03ATID int,
  @parent03AID int,
  @parent04ATID int,
  @parent04AID int,
  @parent05ATID int,
  @parent05AID int,
  @MerchantAID int,
  @Priority int,
  @StatusDescription char (50),
  @PostingReason char (5),
  @StatusAcctReport char (5),
  @TransactionPosting char (5),
  @Reissue_IssueAction char (5),
  @AuthAction char (5),
  @FinanceChargeAction char (5),
  @WaiveLateChargeAction char (5),
  @WaiveMbrshipFeeAction char (5),
  @WaiveOverLimitFeeAction char (5),
  @WaiveNSFAction char (5),
  @StatementAction char (5),
  @RevolvingPaymentAction char (5),
  @InsCancellationAction char (5),
  @CreditBureauRptgAction char (5),
  @CreditBureauStatus char (2),
  @CheckOTB char (5),
  @CollectionFlagsbyStatus char (5),
  @StatementDelivery char (5),
  @WaiveMinDue char (5),
  @WaiveInsPremium char (5),
  @SetDunSuppress char (5),
  @EligibleForInsurance char (5),
  @lastupdate int,
  @ASResActionCode char (2),
  @ASCCaseActionCode char (2),
  @ACOverridePriority int,
  @LoyaltyPointsAccumulation int,
  @Email varchar (30),
  @GenerateSMS varchar (30),
  @GenerateLetter varchar (30),
  @LoadAuthAction char (9),
  @AuthActionVisa char (9),
  @AuthActionDiscover varchar (9),
  @AuthActionPrivateLabel char (9),
  @ResponseCodeVisa char (9),
  @ResponseCodeMC char (9),
  @ResponseCodeDiscover char (9),
  @ResponseCodePrivateLabel char (9),
  @LoadAuthActionVisa char (9),
  @LoadAuthActionDiscover char (9),
  @LoadAuthActionPrivateLabel char (9),
  @LoadResponseCodeVISA char (9),
  @LoadResponseCodeMC char (9),
  @LoadResponseCodeDiscover char (9),
  @LoadResponseCodePrivateLabel char (9),
  @tpyNAD datetime,
  @tpyLAD datetime,
  @tpyBlob text,
  @WaiveLateChargeFor varchar (2),
  @WaiveLateChargeFrom varchar (1),
  @WaiveMbrshipFeeFor varchar (2),
  @WaiveMbrshipFeeFrom char (1),
  @WaiveOverLimitFeeFor char (2),
  @WaiveOverLimitFeeFrom char (1),
  @WaiveNSFFor varchar (2),
  @WaiveNSFFrom varchar (1),
  @WaiveMinDueFor varchar (2),
  @WaiveMinDueFrom varchar (1),
  @WaiveInsPremiumFor varchar (2),
  @WaiveInsPremiumFrom varchar (1),
  @WaiveInterest varchar (5),
  @WaiveInterestFor varchar (2),
  @WaiveInterestFrom varchar (1),
  @WaiveAnnualChgAction varchar (5),
  @WaiveAnnualChgFor varchar (2),
  @WaiveAnnualChgFrom varchar (1),
  @WaiveServiceFeeAction varchar (5),
  @WaiveServiceFeeFor varchar (2),
  @WaiveServiceFeeFrom varchar (1),
  @WaiveTransactionFeeAction varchar (5),
  @WaiveTransactionFeeFor varchar (2),
  @WaiveTransactionFeeFrom varchar (1),
  @WaiveCardFeeAction varchar (5),
  @WaiveCardFeeFor varchar (2),
  @WaiveCardFeeFrom varchar (1),
  @WaiveAuthFeeAction varchar (5),
  @WaiveAuthFeeFor varchar (2),
  @WaiveAuthFeeFrom varchar (1),
  @WaiveMessageFeeAction varchar (5),
  @WaiveMessageFeeFor varchar (2),
  @WaiveMessageFeeFrom varchar (1),
  @CBRStatusGroup char (2),
  @ExcludeFromCBR int,
  @ComplianceConditionCode varchar (2),
  @SpecialComment varchar (2),
  @HoldStatement varchar (25),
  @SelfServiceAccess char (3),
  @PO_ASCheckOTB tinyint,
  @PO_ASCBRAction tinyint,
  @PO_ASCBureauStatus tinyint,
  @PO_ASEligibikityForInsurance tinyint,
  @PO_FinanceChargeAct tinyint,
  @PO_ASInsCancellationAct tinyint,
  @PO_LoyaltyPointsAcc tinyint,
  @PO_ReissueOrIssue tinyint,
  @PO_ASPostingReason tinyint,
  @PO_ASRevolvingPaymentAction tinyint,
  @PO_ASStatementAction tinyint,
  @PO_ASTransactionPosting tinyint,
  @PO_deHoldStatement tinyint,
  @PO_AsStatusAccRpt tinyint,
  @PO_ASWLateChargeAct tinyint,
  @PO_ASWMembFeeAct tinyint,
  @PO_ASWOverLimFeeAct tinyint,
  @PO_ASWNSFAction tinyint,
  @PO_ASStatementDelivery tinyint,
  @PO_ASWaiveMinDue tinyint,
  @PO_ASWaiveInterest tinyint,
  @PO_ASWaiveInsPremium tinyint,
  @PO_ASWaiveTxnFeeAct tinyint,
  @PO_ASWaiveAuthFeeAct tinyint,
  @PO_ASWaiveCardFeeAct tinyint,
  @PO_ASWAnnualChgAct tinyint,
  @PO_ASWMessageFeeAct tinyint,
  @PO_ASWServiceFeeAct tinyint,
  @LoyaltyDebits varchar (5),
  @SchedulePayments varchar (1) AS
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET QUOTED_IDENTIFIER ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;
SET NOCOUNT OFF;
 UPDATE DBO.AStatusAccounts SET   [ATID] = @ATID,
  [rowClassifier] = @rowClassifier,
  [grpClassifier] = @grpClassifier,
  [LAD] = @LAD,
  [LAPD] = @LAPD,
  [NAD] = @NAD,
  [AccountBlob] = @AccountBlob,
  [StatementDate] = @StatementDate,
  [parent01ATID] = @parent01ATID,
  [parent01AID] = @parent01AID,
  [parent02ATID] = @parent02ATID,
  [parent02AID] = @parent02AID,
  [parent03ATID] = @parent03ATID,
  [parent03AID] = @parent03AID,
  [parent04ATID] = @parent04ATID,
  [parent04AID] = @parent04AID,
  [parent05ATID] = @parent05ATID,
  [parent05AID] = @parent05AID,
  [MerchantAID] = @MerchantAID,
  [Priority] = @Priority,
  [StatusDescription] = @StatusDescription,
  [PostingReason] = @PostingReason,
  [StatusAcctReport] = @StatusAcctReport,
  [TransactionPosting] = @TransactionPosting,
  [Reissue_IssueAction] = @Reissue_IssueAction,
  [AuthAction] = @AuthAction,
  [FinanceChargeAction] = @FinanceChargeAction,
  [WaiveLateChargeAction] = @WaiveLateChargeAction,
  [WaiveMbrshipFeeAction] = @WaiveMbrshipFeeAction,
  [WaiveOverLimitFeeAction] = @WaiveOverLimitFeeAction,
  [WaiveNSFAction] = @WaiveNSFAction,
  [StatementAction] = @StatementAction,
  [RevolvingPaymentAction] = @RevolvingPaymentAction,
  [InsCancellationAction] = @InsCancellationAction,
  [CreditBureauRptgAction] = @CreditBureauRptgAction,
  [CreditBureauStatus] = @CreditBureauStatus,
  [CheckOTB] = @CheckOTB,
  [CollectionFlagsbyStatus] = @CollectionFlagsbyStatus,
  [StatementDelivery] = @StatementDelivery,
  [WaiveMinDue] = @WaiveMinDue,
  [WaiveInsPremium] = @WaiveInsPremium,
  [SetDunSuppress] = @SetDunSuppress,
  [EligibleForInsurance] = @EligibleForInsurance,
  [lastupdate] = @lastupdate,
  [ASResActionCode] = @ASResActionCode,
  [ASCCaseActionCode] = @ASCCaseActionCode,
  [ACOverridePriority] = @ACOverridePriority,
  [LoyaltyPointsAccumulation] = @LoyaltyPointsAccumulation,
  [Email] = @Email,
  [GenerateSMS] = @GenerateSMS,
  [GenerateLetter] = @GenerateLetter,
  [LoadAuthAction] = @LoadAuthAction,
  [AuthActionVisa] = @AuthActionVisa,
  [AuthActionDiscover] = @AuthActionDiscover,
  [AuthActionPrivateLabel] = @AuthActionPrivateLabel,
  [ResponseCodeVisa] = @ResponseCodeVisa,
  [ResponseCodeMC] = @ResponseCodeMC,
  [ResponseCodeDiscover] = @ResponseCodeDiscover,
  [ResponseCodePrivateLabel] = @ResponseCodePrivateLabel,
  [LoadAuthActionVisa] = @LoadAuthActionVisa,
  [LoadAuthActionDiscover] = @LoadAuthActionDiscover,
  [LoadAuthActionPrivateLabel] = @LoadAuthActionPrivateLabel,
  [LoadResponseCodeVISA] = @LoadResponseCodeVISA,
  [LoadResponseCodeMC] = @LoadResponseCodeMC,
  [LoadResponseCodeDiscover] = @LoadResponseCodeDiscover,
  [LoadResponseCodePrivateLabel] = @LoadResponseCodePrivateLabel,
  [tpyNAD] = @tpyNAD,
  [tpyLAD] = @tpyLAD,
  [tpyBlob] = @tpyBlob,
  [WaiveLateChargeFor] = @WaiveLateChargeFor,
  [WaiveLateChargeFrom] = @WaiveLateChargeFrom,
  [WaiveMbrshipFeeFor] = @WaiveMbrshipFeeFor,
  [WaiveMbrshipFeeFrom] = @WaiveMbrshipFeeFrom,
  [WaiveOverLimitFeeFor] = @WaiveOverLimitFeeFor,
  [WaiveOverLimitFeeFrom] = @WaiveOverLimitFeeFrom,
  [WaiveNSFFor] = @WaiveNSFFor,
  [WaiveNSFFrom] = @WaiveNSFFrom,
  [WaiveMinDueFor] = @WaiveMinDueFor,
  [WaiveMinDueFrom] = @WaiveMinDueFrom,
  [WaiveInsPremiumFor] = @WaiveInsPremiumFor,
  [WaiveInsPremiumFrom] = @WaiveInsPremiumFrom,
  [WaiveInterest] = @WaiveInterest,
  [WaiveInterestFor] = @WaiveInterestFor,
  [WaiveInterestFrom] = @WaiveInterestFrom,
  [WaiveAnnualChgAction] = @WaiveAnnualChgAction,
  [WaiveAnnualChgFor] = @WaiveAnnualChgFor,
  [WaiveAnnualChgFrom] = @WaiveAnnualChgFrom,
  [WaiveServiceFeeAction] = @WaiveServiceFeeAction,
  [WaiveServiceFeeFor] = @WaiveServiceFeeFor,
  [WaiveServiceFeeFrom] = @WaiveServiceFeeFrom,
  [WaiveTransactionFeeAction] = @WaiveTransactionFeeAction,
  [WaiveTransactionFeeFor] = @WaiveTransactionFeeFor,
  [WaiveTransactionFeeFrom] = @WaiveTransactionFeeFrom,
  [WaiveCardFeeAction] = @WaiveCardFeeAction,
  [WaiveCardFeeFor] = @WaiveCardFeeFor,
  [WaiveCardFeeFrom] = @WaiveCardFeeFrom,
  [WaiveAuthFeeAction] = @WaiveAuthFeeAction,
  [WaiveAuthFeeFor] = @WaiveAuthFeeFor,
  [WaiveAuthFeeFrom] = @WaiveAuthFeeFrom,
  [WaiveMessageFeeAction] = @WaiveMessageFeeAction,
  [WaiveMessageFeeFor] = @WaiveMessageFeeFor,
  [WaiveMessageFeeFrom] = @WaiveMessageFeeFrom,
  [CBRStatusGroup] = @CBRStatusGroup,
  [ExcludeFromCBR] = @ExcludeFromCBR,
  [ComplianceConditionCode] = @ComplianceConditionCode,
  [SpecialComment] = @SpecialComment,
  [HoldStatement] = @HoldStatement,
  [SelfServiceAccess] = @SelfServiceAccess,
  [PO_ASCheckOTB] = @PO_ASCheckOTB,
  [PO_ASCBRAction] = @PO_ASCBRAction,
  [PO_ASCBureauStatus] = @PO_ASCBureauStatus,
  [PO_ASEligibikityForInsurance] = @PO_ASEligibikityForInsurance,
  [PO_FinanceChargeAct] = @PO_FinanceChargeAct,
  [PO_ASInsCancellationAct] = @PO_ASInsCancellationAct,
  [PO_LoyaltyPointsAcc] = @PO_LoyaltyPointsAcc,
  [PO_ReissueOrIssue] = @PO_ReissueOrIssue,
  [PO_ASPostingReason] = @PO_ASPostingReason,
  [PO_ASRevolvingPaymentAction] = @PO_ASRevolvingPaymentAction,
  [PO_ASStatementAction] = @PO_ASStatementAction,
  [PO_ASTransactionPosting] = @PO_ASTransactionPosting,
  [PO_deHoldStatement] = @PO_deHoldStatement,
  [PO_AsStatusAccRpt] = @PO_AsStatusAccRpt,
  [PO_ASWLateChargeAct] = @PO_ASWLateChargeAct,
  [PO_ASWMembFeeAct] = @PO_ASWMembFeeAct,
  [PO_ASWOverLimFeeAct] = @PO_ASWOverLimFeeAct,
  [PO_ASWNSFAction] = @PO_ASWNSFAction,
  [PO_ASStatementDelivery] = @PO_ASStatementDelivery,
  [PO_ASWaiveMinDue] = @PO_ASWaiveMinDue,
  [PO_ASWaiveInterest] = @PO_ASWaiveInterest,
  [PO_ASWaiveInsPremium] = @PO_ASWaiveInsPremium,
  [PO_ASWaiveTxnFeeAct] = @PO_ASWaiveTxnFeeAct,
  [PO_ASWaiveAuthFeeAct] = @PO_ASWaiveAuthFeeAct,
  [PO_ASWaiveCardFeeAct] = @PO_ASWaiveCardFeeAct,
  [PO_ASWAnnualChgAct] = @PO_ASWAnnualChgAct,
  [PO_ASWMessageFeeAct] = @PO_ASWMessageFeeAct,
  [PO_ASWServiceFeeAct] = @PO_ASWServiceFeeAct,
  [LoyaltyDebits] = @LoyaltyDebits,
  [SchedulePayments] = @SchedulePayments 
WHERE 
   [acctId] = @acctId 
GO
grant execute on sp_AStatusAccounts_upd to public 
GO

if exists (select * from sysobjects where 
 id = object_id('sp_AStatusAccounts_ins') and sysstat & 0xf = 4)
drop procedure sp_AStatusAccounts_ins
GO
CREATE PROCEDURE sp_AStatusAccounts_ins (
  @acctId int,
  @ATID int,
  @rowClassifier char (16),
  @grpClassifier char (16),
  @LAD datetime,
  @LAPD datetime,
  @NAD datetime,
  @AccountBlob text,
  @StatementDate datetime,
  @parent01ATID int,
  @parent01AID int,
  @parent02ATID int,
  @parent02AID int,
  @parent03ATID int,
  @parent03AID int,
  @parent04ATID int,
  @parent04AID int,
  @parent05ATID int,
  @parent05AID int,
  @MerchantAID int,
  @Priority int,
  @StatusDescription char (50),
  @PostingReason char (5),
  @StatusAcctReport char (5),
  @TransactionPosting char (5),
  @Reissue_IssueAction char (5),
  @AuthAction char (5),
  @FinanceChargeAction char (5),
  @WaiveLateChargeAction char (5),
  @WaiveMbrshipFeeAction char (5),
  @WaiveOverLimitFeeAction char (5),
  @WaiveNSFAction char (5),
  @StatementAction char (5),
  @RevolvingPaymentAction char (5),
  @InsCancellationAction char (5),
  @CreditBureauRptgAction char (5),
  @CreditBureauStatus char (2),
  @CheckOTB char (5),
  @CollectionFlagsbyStatus char (5),
  @StatementDelivery char (5),
  @WaiveMinDue char (5),
  @WaiveInsPremium char (5),
  @SetDunSuppress char (5),
  @EligibleForInsurance char (5),
  @lastupdate int,
  @ASResActionCode char (2),
  @ASCCaseActionCode char (2),
  @ACOverridePriority int,
  @LoyaltyPointsAccumulation int,
  @Email varchar (30),
  @GenerateSMS varchar (30),
  @GenerateLetter varchar (30),
  @LoadAuthAction char (9),
  @AuthActionVisa char (9),
  @AuthActionDiscover varchar (9),
  @AuthActionPrivateLabel char (9),
  @ResponseCodeVisa char (9),
  @ResponseCodeMC char (9),
  @ResponseCodeDiscover char (9),
  @ResponseCodePrivateLabel char (9),
  @LoadAuthActionVisa char (9),
  @LoadAuthActionDiscover char (9),
  @LoadAuthActionPrivateLabel char (9),
  @LoadResponseCodeVISA char (9),
  @LoadResponseCodeMC char (9),
  @LoadResponseCodeDiscover char (9),
  @LoadResponseCodePrivateLabel char (9),
  @tpyNAD datetime,
  @tpyLAD datetime,
  @tpyBlob text,
  @WaiveLateChargeFor varchar (2),
  @WaiveLateChargeFrom varchar (1),
  @WaiveMbrshipFeeFor varchar (2),
  @WaiveMbrshipFeeFrom char (1),
  @WaiveOverLimitFeeFor char (2),
  @WaiveOverLimitFeeFrom char (1),
  @WaiveNSFFor varchar (2),
  @WaiveNSFFrom varchar (1),
  @WaiveMinDueFor varchar (2),
  @WaiveMinDueFrom varchar (1),
  @WaiveInsPremiumFor varchar (2),
  @WaiveInsPremiumFrom varchar (1),
  @WaiveInterest varchar (5),
  @WaiveInterestFor varchar (2),
  @WaiveInterestFrom varchar (1),
  @WaiveAnnualChgAction varchar (5),
  @WaiveAnnualChgFor varchar (2),
  @WaiveAnnualChgFrom varchar (1),
  @WaiveServiceFeeAction varchar (5),
  @WaiveServiceFeeFor varchar (2),
  @WaiveServiceFeeFrom varchar (1),
  @WaiveTransactionFeeAction varchar (5),
  @WaiveTransactionFeeFor varchar (2),
  @WaiveTransactionFeeFrom varchar (1),
  @WaiveCardFeeAction varchar (5),
  @WaiveCardFeeFor varchar (2),
  @WaiveCardFeeFrom varchar (1),
  @WaiveAuthFeeAction varchar (5),
  @WaiveAuthFeeFor varchar (2),
  @WaiveAuthFeeFrom varchar (1),
  @WaiveMessageFeeAction varchar (5),
  @WaiveMessageFeeFor varchar (2),
  @WaiveMessageFeeFrom varchar (1),
  @CBRStatusGroup char (2),
  @ExcludeFromCBR int,
  @ComplianceConditionCode varchar (2),
  @SpecialComment varchar (2),
  @HoldStatement varchar (25),
  @SelfServiceAccess char (3),
  @PO_ASCheckOTB tinyint,
  @PO_ASCBRAction tinyint,
  @PO_ASCBureauStatus tinyint,
  @PO_ASEligibikityForInsurance tinyint,
  @PO_FinanceChargeAct tinyint,
  @PO_ASInsCancellationAct tinyint,
  @PO_LoyaltyPointsAcc tinyint,
  @PO_ReissueOrIssue tinyint,
  @PO_ASPostingReason tinyint,
  @PO_ASRevolvingPaymentAction tinyint,
  @PO_ASStatementAction tinyint,
  @PO_ASTransactionPosting tinyint,
  @PO_deHoldStatement tinyint,
  @PO_AsStatusAccRpt tinyint,
  @PO_ASWLateChargeAct tinyint,
  @PO_ASWMembFeeAct tinyint,
  @PO_ASWOverLimFeeAct tinyint,
  @PO_ASWNSFAction tinyint,
  @PO_ASStatementDelivery tinyint,
  @PO_ASWaiveMinDue tinyint,
  @PO_ASWaiveInterest tinyint,
  @PO_ASWaiveInsPremium tinyint,
  @PO_ASWaiveTxnFeeAct tinyint,
  @PO_ASWaiveAuthFeeAct tinyint,
  @PO_ASWaiveCardFeeAct tinyint,
  @PO_ASWAnnualChgAct tinyint,
  @PO_ASWMessageFeeAct tinyint,
  @PO_ASWServiceFeeAct tinyint,
  @LoyaltyDebits varchar (5),
  @SchedulePayments varchar (1))
AS
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET QUOTED_IDENTIFIER ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;
 INSERT INTO DBO.AStatusAccounts 
(  [acctId],
 [ATID],
 [rowClassifier],
 [grpClassifier],
 [LAD],
 [LAPD],
 [NAD],
 [AccountBlob],
 [StatementDate],
 [parent01ATID],
 [parent01AID],
 [parent02ATID],
 [parent02AID],
 [parent03ATID],
 [parent03AID],
 [parent04ATID],
 [parent04AID],
 [parent05ATID],
 [parent05AID],
 [MerchantAID],
 [Priority],
 [StatusDescription],
 [PostingReason],
 [StatusAcctReport],
 [TransactionPosting],
 [Reissue_IssueAction],
 [AuthAction],
 [FinanceChargeAction],
 [WaiveLateChargeAction],
 [WaiveMbrshipFeeAction],
 [WaiveOverLimitFeeAction],
 [WaiveNSFAction],
 [StatementAction],
 [RevolvingPaymentAction],
 [InsCancellationAction],
 [CreditBureauRptgAction],
 [CreditBureauStatus],
 [CheckOTB],
 [CollectionFlagsbyStatus],
 [StatementDelivery],
 [WaiveMinDue],
 [WaiveInsPremium],
 [SetDunSuppress],
 [EligibleForInsurance],
 [lastupdate],
 [ASResActionCode],
 [ASCCaseActionCode],
 [ACOverridePriority],
 [LoyaltyPointsAccumulation],
 [Email],
 [GenerateSMS],
 [GenerateLetter],
 [LoadAuthAction],
 [AuthActionVisa],
 [AuthActionDiscover],
 [AuthActionPrivateLabel],
 [ResponseCodeVisa],
 [ResponseCodeMC],
 [ResponseCodeDiscover],
 [ResponseCodePrivateLabel],
 [LoadAuthActionVisa],
 [LoadAuthActionDiscover],
 [LoadAuthActionPrivateLabel],
 [LoadResponseCodeVISA],
 [LoadResponseCodeMC],
 [LoadResponseCodeDiscover],
 [LoadResponseCodePrivateLabel],
 [tpyNAD],
 [tpyLAD],
 [tpyBlob],
 [WaiveLateChargeFor],
 [WaiveLateChargeFrom],
 [WaiveMbrshipFeeFor],
 [WaiveMbrshipFeeFrom],
 [WaiveOverLimitFeeFor],
 [WaiveOverLimitFeeFrom],
 [WaiveNSFFor],
 [WaiveNSFFrom],
 [WaiveMinDueFor],
 [WaiveMinDueFrom],
 [WaiveInsPremiumFor],
 [WaiveInsPremiumFrom],
 [WaiveInterest],
 [WaiveInterestFor],
 [WaiveInterestFrom],
 [WaiveAnnualChgAction],
 [WaiveAnnualChgFor],
 [WaiveAnnualChgFrom],
 [WaiveServiceFeeAction],
 [WaiveServiceFeeFor],
 [WaiveServiceFeeFrom],
 [WaiveTransactionFeeAction],
 [WaiveTransactionFeeFor],
 [WaiveTransactionFeeFrom],
 [WaiveCardFeeAction],
 [WaiveCardFeeFor],
 [WaiveCardFeeFrom],
 [WaiveAuthFeeAction],
 [WaiveAuthFeeFor],
 [WaiveAuthFeeFrom],
 [WaiveMessageFeeAction],
 [WaiveMessageFeeFor],
 [WaiveMessageFeeFrom],
 [CBRStatusGroup],
 [ExcludeFromCBR],
 [ComplianceConditionCode],
 [SpecialComment],
 [HoldStatement],
 [SelfServiceAccess],
 [PO_ASCheckOTB],
 [PO_ASCBRAction],
 [PO_ASCBureauStatus],
 [PO_ASEligibikityForInsurance],
 [PO_FinanceChargeAct],
 [PO_ASInsCancellationAct],
 [PO_LoyaltyPointsAcc],
 [PO_ReissueOrIssue],
 [PO_ASPostingReason],
 [PO_ASRevolvingPaymentAction],
 [PO_ASStatementAction],
 [PO_ASTransactionPosting],
 [PO_deHoldStatement],
 [PO_AsStatusAccRpt],
 [PO_ASWLateChargeAct],
 [PO_ASWMembFeeAct],
 [PO_ASWOverLimFeeAct],
 [PO_ASWNSFAction],
 [PO_ASStatementDelivery],
 [PO_ASWaiveMinDue],
 [PO_ASWaiveInterest],
 [PO_ASWaiveInsPremium],
 [PO_ASWaiveTxnFeeAct],
 [PO_ASWaiveAuthFeeAct],
 [PO_ASWaiveCardFeeAct],
 [PO_ASWAnnualChgAct],
 [PO_ASWMessageFeeAct],
 [PO_ASWServiceFeeAct],
 [LoyaltyDebits],
 [SchedulePayments])
VALUES (  @acctId,
 @ATID,
 @rowClassifier,
 @grpClassifier,
 @LAD,
 @LAPD,
 @NAD,
 @AccountBlob,
 @StatementDate,
 @parent01ATID,
 @parent01AID,
 @parent02ATID,
 @parent02AID,
 @parent03ATID,
 @parent03AID,
 @parent04ATID,
 @parent04AID,
 @parent05ATID,
 @parent05AID,
 @MerchantAID,
 @Priority,
 @StatusDescription,
 @PostingReason,
 @StatusAcctReport,
 @TransactionPosting,
 @Reissue_IssueAction,
 @AuthAction,
 @FinanceChargeAction,
 @WaiveLateChargeAction,
 @WaiveMbrshipFeeAction,
 @WaiveOverLimitFeeAction,
 @WaiveNSFAction,
 @StatementAction,
 @RevolvingPaymentAction,
 @InsCancellationAction,
 @CreditBureauRptgAction,
 @CreditBureauStatus,
 @CheckOTB,
 @CollectionFlagsbyStatus,
 @StatementDelivery,
 @WaiveMinDue,
 @WaiveInsPremium,
 @SetDunSuppress,
 @EligibleForInsurance,
 @lastupdate,
 @ASResActionCode,
 @ASCCaseActionCode,
 @ACOverridePriority,
 @LoyaltyPointsAccumulation,
 @Email,
 @GenerateSMS,
 @GenerateLetter,
 @LoadAuthAction,
 @AuthActionVisa,
 @AuthActionDiscover,
 @AuthActionPrivateLabel,
 @ResponseCodeVisa,
 @ResponseCodeMC,
 @ResponseCodeDiscover,
 @ResponseCodePrivateLabel,
 @LoadAuthActionVisa,
 @LoadAuthActionDiscover,
 @LoadAuthActionPrivateLabel,
 @LoadResponseCodeVISA,
 @LoadResponseCodeMC,
 @LoadResponseCodeDiscover,
 @LoadResponseCodePrivateLabel,
 @tpyNAD,
 @tpyLAD,
 @tpyBlob,
 @WaiveLateChargeFor,
 @WaiveLateChargeFrom,
 @WaiveMbrshipFeeFor,
 @WaiveMbrshipFeeFrom,
 @WaiveOverLimitFeeFor,
 @WaiveOverLimitFeeFrom,
 @WaiveNSFFor,
 @WaiveNSFFrom,
 @WaiveMinDueFor,
 @WaiveMinDueFrom,
 @WaiveInsPremiumFor,
 @WaiveInsPremiumFrom,
 @WaiveInterest,
 @WaiveInterestFor,
 @WaiveInterestFrom,
 @WaiveAnnualChgAction,
 @WaiveAnnualChgFor,
 @WaiveAnnualChgFrom,
 @WaiveServiceFeeAction,
 @WaiveServiceFeeFor,
 @WaiveServiceFeeFrom,
 @WaiveTransactionFeeAction,
 @WaiveTransactionFeeFor,
 @WaiveTransactionFeeFrom,
 @WaiveCardFeeAction,
 @WaiveCardFeeFor,
 @WaiveCardFeeFrom,
 @WaiveAuthFeeAction,
 @WaiveAuthFeeFor,
 @WaiveAuthFeeFrom,
 @WaiveMessageFeeAction,
 @WaiveMessageFeeFor,
 @WaiveMessageFeeFrom,
 @CBRStatusGroup,
 @ExcludeFromCBR,
 @ComplianceConditionCode,
 @SpecialComment,
 @HoldStatement,
 @SelfServiceAccess,
 @PO_ASCheckOTB,
 @PO_ASCBRAction,
 @PO_ASCBureauStatus,
 @PO_ASEligibikityForInsurance,
 @PO_FinanceChargeAct,
 @PO_ASInsCancellationAct,
 @PO_LoyaltyPointsAcc,
 @PO_ReissueOrIssue,
 @PO_ASPostingReason,
 @PO_ASRevolvingPaymentAction,
 @PO_ASStatementAction,
 @PO_ASTransactionPosting,
 @PO_deHoldStatement,
 @PO_AsStatusAccRpt,
 @PO_ASWLateChargeAct,
 @PO_ASWMembFeeAct,
 @PO_ASWOverLimFeeAct,
 @PO_ASWNSFAction,
 @PO_ASStatementDelivery,
 @PO_ASWaiveMinDue,
 @PO_ASWaiveInterest,
 @PO_ASWaiveInsPremium,
 @PO_ASWaiveTxnFeeAct,
 @PO_ASWaiveAuthFeeAct,
 @PO_ASWaiveCardFeeAct,
 @PO_ASWAnnualChgAct,
 @PO_ASWMessageFeeAct,
 @PO_ASWServiceFeeAct,
 @LoyaltyDebits,
 @SchedulePayments)
GO

grant execute on sp_AStatusAccounts_ins to public 
GO

if exists (select * from sysobjects where 
 id = object_id('sp_AStatusAccounts_insupd') and sysstat & 0xf = 4)
drop procedure sp_AStatusAccounts_insupd
GO
CREATE PROCEDURE sp_AStatusAccounts_insupd (  @acctId int,
  @ATID int,
  @rowClassifier char (16),
  @grpClassifier char (16),
  @LAD datetime,
  @LAPD datetime,
  @NAD datetime,
  @AccountBlob text,
  @StatementDate datetime,
  @parent01ATID int,
  @parent01AID int,
  @parent02ATID int,
  @parent02AID int,
  @parent03ATID int,
  @parent03AID int,
  @parent04ATID int,
  @parent04AID int,
  @parent05ATID int,
  @parent05AID int,
  @MerchantAID int,
  @Priority int,
  @StatusDescription char (50),
  @PostingReason char (5),
  @StatusAcctReport char (5),
  @TransactionPosting char (5),
  @Reissue_IssueAction char (5),
  @AuthAction char (5),
  @FinanceChargeAction char (5),
  @WaiveLateChargeAction char (5),
  @WaiveMbrshipFeeAction char (5),
  @WaiveOverLimitFeeAction char (5),
  @WaiveNSFAction char (5),
  @StatementAction char (5),
  @RevolvingPaymentAction char (5),
  @InsCancellationAction char (5),
  @CreditBureauRptgAction char (5),
  @CreditBureauStatus char (2),
  @CheckOTB char (5),
  @CollectionFlagsbyStatus char (5),
  @StatementDelivery char (5),
  @WaiveMinDue char (5),
  @WaiveInsPremium char (5),
  @SetDunSuppress char (5),
  @EligibleForInsurance char (5),
  @lastupdate int,
  @ASResActionCode char (2),
  @ASCCaseActionCode char (2),
  @ACOverridePriority int,
  @LoyaltyPointsAccumulation int,
  @Email varchar (30),
  @GenerateSMS varchar (30),
  @GenerateLetter varchar (30),
  @LoadAuthAction char (9),
  @AuthActionVisa char (9),
  @AuthActionDiscover varchar (9),
  @AuthActionPrivateLabel char (9),
  @ResponseCodeVisa char (9),
  @ResponseCodeMC char (9),
  @ResponseCodeDiscover char (9),
  @ResponseCodePrivateLabel char (9),
  @LoadAuthActionVisa char (9),
  @LoadAuthActionDiscover char (9),
  @LoadAuthActionPrivateLabel char (9),
  @LoadResponseCodeVISA char (9),
  @LoadResponseCodeMC char (9),
  @LoadResponseCodeDiscover char (9),
  @LoadResponseCodePrivateLabel char (9),
  @tpyNAD datetime,
  @tpyLAD datetime,
  @tpyBlob text,
  @WaiveLateChargeFor varchar (2),
  @WaiveLateChargeFrom varchar (1),
  @WaiveMbrshipFeeFor varchar (2),
  @WaiveMbrshipFeeFrom char (1),
  @WaiveOverLimitFeeFor char (2),
  @WaiveOverLimitFeeFrom char (1),
  @WaiveNSFFor varchar (2),
  @WaiveNSFFrom varchar (1),
  @WaiveMinDueFor varchar (2),
  @WaiveMinDueFrom varchar (1),
  @WaiveInsPremiumFor varchar (2),
  @WaiveInsPremiumFrom varchar (1),
  @WaiveInterest varchar (5),
  @WaiveInterestFor varchar (2),
  @WaiveInterestFrom varchar (1),
  @WaiveAnnualChgAction varchar (5),
  @WaiveAnnualChgFor varchar (2),
  @WaiveAnnualChgFrom varchar (1),
  @WaiveServiceFeeAction varchar (5),
  @WaiveServiceFeeFor varchar (2),
  @WaiveServiceFeeFrom varchar (1),
  @WaiveTransactionFeeAction varchar (5),
  @WaiveTransactionFeeFor varchar (2),
  @WaiveTransactionFeeFrom varchar (1),
  @WaiveCardFeeAction varchar (5),
  @WaiveCardFeeFor varchar (2),
  @WaiveCardFeeFrom varchar (1),
  @WaiveAuthFeeAction varchar (5),
  @WaiveAuthFeeFor varchar (2),
  @WaiveAuthFeeFrom varchar (1),
  @WaiveMessageFeeAction varchar (5),
  @WaiveMessageFeeFor varchar (2),
  @WaiveMessageFeeFrom varchar (1),
  @CBRStatusGroup char (2),
  @ExcludeFromCBR int,
  @ComplianceConditionCode varchar (2),
  @SpecialComment varchar (2),
  @HoldStatement varchar (25),
  @SelfServiceAccess char (3),
  @PO_ASCheckOTB tinyint,
  @PO_ASCBRAction tinyint,
  @PO_ASCBureauStatus tinyint,
  @PO_ASEligibikityForInsurance tinyint,
  @PO_FinanceChargeAct tinyint,
  @PO_ASInsCancellationAct tinyint,
  @PO_LoyaltyPointsAcc tinyint,
  @PO_ReissueOrIssue tinyint,
  @PO_ASPostingReason tinyint,
  @PO_ASRevolvingPaymentAction tinyint,
  @PO_ASStatementAction tinyint,
  @PO_ASTransactionPosting tinyint,
  @PO_deHoldStatement tinyint,
  @PO_AsStatusAccRpt tinyint,
  @PO_ASWLateChargeAct tinyint,
  @PO_ASWMembFeeAct tinyint,
  @PO_ASWOverLimFeeAct tinyint,
  @PO_ASWNSFAction tinyint,
  @PO_ASStatementDelivery tinyint,
  @PO_ASWaiveMinDue tinyint,
  @PO_ASWaiveInterest tinyint,
  @PO_ASWaiveInsPremium tinyint,
  @PO_ASWaiveTxnFeeAct tinyint,
  @PO_ASWaiveAuthFeeAct tinyint,
  @PO_ASWaiveCardFeeAct tinyint,
  @PO_ASWAnnualChgAct tinyint,
  @PO_ASWMessageFeeAct tinyint,
  @PO_ASWServiceFeeAct tinyint,
  @LoyaltyDebits varchar (5),
  @SchedulePayments varchar (1)) AS
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET QUOTED_IDENTIFIER ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;
SET NOCOUNT OFF;

IF EXISTS (SELECT [acctId] FROM DBO.AStatusAccounts WHERE 
   [acctId] = @acctId 
)
UPDATE DBO.AStatusAccounts SET  [ATID] = @ATID,
  [rowClassifier] = @rowClassifier,
  [grpClassifier] = @grpClassifier,
  [LAD] = @LAD,
  [LAPD] = @LAPD,
  [NAD] = @NAD,
  [AccountBlob] = @AccountBlob,
  [StatementDate] = @StatementDate,
  [parent01ATID] = @parent01ATID,
  [parent01AID] = @parent01AID,
  [parent02ATID] = @parent02ATID,
  [parent02AID] = @parent02AID,
  [parent03ATID] = @parent03ATID,
  [parent03AID] = @parent03AID,
  [parent04ATID] = @parent04ATID,
  [parent04AID] = @parent04AID,
  [parent05ATID] = @parent05ATID,
  [parent05AID] = @parent05AID,
  [MerchantAID] = @MerchantAID,
  [Priority] = @Priority,
  [StatusDescription] = @StatusDescription,
  [PostingReason] = @PostingReason,
  [StatusAcctReport] = @StatusAcctReport,
  [TransactionPosting] = @TransactionPosting,
  [Reissue_IssueAction] = @Reissue_IssueAction,
  [AuthAction] = @AuthAction,
  [FinanceChargeAction] = @FinanceChargeAction,
  [WaiveLateChargeAction] = @WaiveLateChargeAction,
  [WaiveMbrshipFeeAction] = @WaiveMbrshipFeeAction,
  [WaiveOverLimitFeeAction] = @WaiveOverLimitFeeAction,
  [WaiveNSFAction] = @WaiveNSFAction,
  [StatementAction] = @StatementAction,
  [RevolvingPaymentAction] = @RevolvingPaymentAction,
  [InsCancellationAction] = @InsCancellationAction,
  [CreditBureauRptgAction] = @CreditBureauRptgAction,
  [CreditBureauStatus] = @CreditBureauStatus,
  [CheckOTB] = @CheckOTB,
  [CollectionFlagsbyStatus] = @CollectionFlagsbyStatus,
  [StatementDelivery] = @StatementDelivery,
  [WaiveMinDue] = @WaiveMinDue,
  [WaiveInsPremium] = @WaiveInsPremium,
  [SetDunSuppress] = @SetDunSuppress,
  [EligibleForInsurance] = @EligibleForInsurance,
  [lastupdate] = @lastupdate,
  [ASResActionCode] = @ASResActionCode,
  [ASCCaseActionCode] = @ASCCaseActionCode,
  [ACOverridePriority] = @ACOverridePriority,
  [LoyaltyPointsAccumulation] = @LoyaltyPointsAccumulation,
  [Email] = @Email,
  [GenerateSMS] = @GenerateSMS,
  [GenerateLetter] = @GenerateLetter,
  [LoadAuthAction] = @LoadAuthAction,
  [AuthActionVisa] = @AuthActionVisa,
  [AuthActionDiscover] = @AuthActionDiscover,
  [AuthActionPrivateLabel] = @AuthActionPrivateLabel,
  [ResponseCodeVisa] = @ResponseCodeVisa,
  [ResponseCodeMC] = @ResponseCodeMC,
  [ResponseCodeDiscover] = @ResponseCodeDiscover,
  [ResponseCodePrivateLabel] = @ResponseCodePrivateLabel,
  [LoadAuthActionVisa] = @LoadAuthActionVisa,
  [LoadAuthActionDiscover] = @LoadAuthActionDiscover,
  [LoadAuthActionPrivateLabel] = @LoadAuthActionPrivateLabel,
  [LoadResponseCodeVISA] = @LoadResponseCodeVISA,
  [LoadResponseCodeMC] = @LoadResponseCodeMC,
  [LoadResponseCodeDiscover] = @LoadResponseCodeDiscover,
  [LoadResponseCodePrivateLabel] = @LoadResponseCodePrivateLabel,
  [tpyNAD] = @tpyNAD,
  [tpyLAD] = @tpyLAD,
  [tpyBlob] = @tpyBlob,
  [WaiveLateChargeFor] = @WaiveLateChargeFor,
  [WaiveLateChargeFrom] = @WaiveLateChargeFrom,
  [WaiveMbrshipFeeFor] = @WaiveMbrshipFeeFor,
  [WaiveMbrshipFeeFrom] = @WaiveMbrshipFeeFrom,
  [WaiveOverLimitFeeFor] = @WaiveOverLimitFeeFor,
  [WaiveOverLimitFeeFrom] = @WaiveOverLimitFeeFrom,
  [WaiveNSFFor] = @WaiveNSFFor,
  [WaiveNSFFrom] = @WaiveNSFFrom,
  [WaiveMinDueFor] = @WaiveMinDueFor,
  [WaiveMinDueFrom] = @WaiveMinDueFrom,
  [WaiveInsPremiumFor] = @WaiveInsPremiumFor,
  [WaiveInsPremiumFrom] = @WaiveInsPremiumFrom,
  [WaiveInterest] = @WaiveInterest,
  [WaiveInterestFor] = @WaiveInterestFor,
  [WaiveInterestFrom] = @WaiveInterestFrom,
  [WaiveAnnualChgAction] = @WaiveAnnualChgAction,
  [WaiveAnnualChgFor] = @WaiveAnnualChgFor,
  [WaiveAnnualChgFrom] = @WaiveAnnualChgFrom,
  [WaiveServiceFeeAction] = @WaiveServiceFeeAction,
  [WaiveServiceFeeFor] = @WaiveServiceFeeFor,
  [WaiveServiceFeeFrom] = @WaiveServiceFeeFrom,
  [WaiveTransactionFeeAction] = @WaiveTransactionFeeAction,
  [WaiveTransactionFeeFor] = @WaiveTransactionFeeFor,
  [WaiveTransactionFeeFrom] = @WaiveTransactionFeeFrom,
  [WaiveCardFeeAction] = @WaiveCardFeeAction,
  [WaiveCardFeeFor] = @WaiveCardFeeFor,
  [WaiveCardFeeFrom] = @WaiveCardFeeFrom,
  [WaiveAuthFeeAction] = @WaiveAuthFeeAction,
  [WaiveAuthFeeFor] = @WaiveAuthFeeFor,
  [WaiveAuthFeeFrom] = @WaiveAuthFeeFrom,
  [WaiveMessageFeeAction] = @WaiveMessageFeeAction,
  [WaiveMessageFeeFor] = @WaiveMessageFeeFor,
  [WaiveMessageFeeFrom] = @WaiveMessageFeeFrom,
  [CBRStatusGroup] = @CBRStatusGroup,
  [ExcludeFromCBR] = @ExcludeFromCBR,
  [ComplianceConditionCode] = @ComplianceConditionCode,
  [SpecialComment] = @SpecialComment,
  [HoldStatement] = @HoldStatement,
  [SelfServiceAccess] = @SelfServiceAccess,
  [PO_ASCheckOTB] = @PO_ASCheckOTB,
  [PO_ASCBRAction] = @PO_ASCBRAction,
  [PO_ASCBureauStatus] = @PO_ASCBureauStatus,
  [PO_ASEligibikityForInsurance] = @PO_ASEligibikityForInsurance,
  [PO_FinanceChargeAct] = @PO_FinanceChargeAct,
  [PO_ASInsCancellationAct] = @PO_ASInsCancellationAct,
  [PO_LoyaltyPointsAcc] = @PO_LoyaltyPointsAcc,
  [PO_ReissueOrIssue] = @PO_ReissueOrIssue,
  [PO_ASPostingReason] = @PO_ASPostingReason,
  [PO_ASRevolvingPaymentAction] = @PO_ASRevolvingPaymentAction,
  [PO_ASStatementAction] = @PO_ASStatementAction,
  [PO_ASTransactionPosting] = @PO_ASTransactionPosting,
  [PO_deHoldStatement] = @PO_deHoldStatement,
  [PO_AsStatusAccRpt] = @PO_AsStatusAccRpt,
  [PO_ASWLateChargeAct] = @PO_ASWLateChargeAct,
  [PO_ASWMembFeeAct] = @PO_ASWMembFeeAct,
  [PO_ASWOverLimFeeAct] = @PO_ASWOverLimFeeAct,
  [PO_ASWNSFAction] = @PO_ASWNSFAction,
  [PO_ASStatementDelivery] = @PO_ASStatementDelivery,
  [PO_ASWaiveMinDue] = @PO_ASWaiveMinDue,
  [PO_ASWaiveInterest] = @PO_ASWaiveInterest,
  [PO_ASWaiveInsPremium] = @PO_ASWaiveInsPremium,
  [PO_ASWaiveTxnFeeAct] = @PO_ASWaiveTxnFeeAct,
  [PO_ASWaiveAuthFeeAct] = @PO_ASWaiveAuthFeeAct,
  [PO_ASWaiveCardFeeAct] = @PO_ASWaiveCardFeeAct,
  [PO_ASWAnnualChgAct] = @PO_ASWAnnualChgAct,
  [PO_ASWMessageFeeAct] = @PO_ASWMessageFeeAct,
  [PO_ASWServiceFeeAct] = @PO_ASWServiceFeeAct,
  [LoyaltyDebits] = @LoyaltyDebits,
  [SchedulePayments] = @SchedulePayments

WHERE 
   [acctId] = @acctId 
ELSE
INSERT INTO DBO.AStatusAccounts
 ( [acctId],
 [ATID],
 [rowClassifier],
 [grpClassifier],
 [LAD],
 [LAPD],
 [NAD],
 [AccountBlob],
 [StatementDate],
 [parent01ATID],
 [parent01AID],
 [parent02ATID],
 [parent02AID],
 [parent03ATID],
 [parent03AID],
 [parent04ATID],
 [parent04AID],
 [parent05ATID],
 [parent05AID],
 [MerchantAID],
 [Priority],
 [StatusDescription],
 [PostingReason],
 [StatusAcctReport],
 [TransactionPosting],
 [Reissue_IssueAction],
 [AuthAction],
 [FinanceChargeAction],
 [WaiveLateChargeAction],
 [WaiveMbrshipFeeAction],
 [WaiveOverLimitFeeAction],
 [WaiveNSFAction],
 [StatementAction],
 [RevolvingPaymentAction],
 [InsCancellationAction],
 [CreditBureauRptgAction],
 [CreditBureauStatus],
 [CheckOTB],
 [CollectionFlagsbyStatus],
 [StatementDelivery],
 [WaiveMinDue],
 [WaiveInsPremium],
 [SetDunSuppress],
 [EligibleForInsurance],
 [lastupdate],
 [ASResActionCode],
 [ASCCaseActionCode],
 [ACOverridePriority],
 [LoyaltyPointsAccumulation],
 [Email],
 [GenerateSMS],
 [GenerateLetter],
 [LoadAuthAction],
 [AuthActionVisa],
 [AuthActionDiscover],
 [AuthActionPrivateLabel],
 [ResponseCodeVisa],
 [ResponseCodeMC],
 [ResponseCodeDiscover],
 [ResponseCodePrivateLabel],
 [LoadAuthActionVisa],
 [LoadAuthActionDiscover],
 [LoadAuthActionPrivateLabel],
 [LoadResponseCodeVISA],
 [LoadResponseCodeMC],
 [LoadResponseCodeDiscover],
 [LoadResponseCodePrivateLabel],
 [tpyNAD],
 [tpyLAD],
 [tpyBlob],
 [WaiveLateChargeFor],
 [WaiveLateChargeFrom],
 [WaiveMbrshipFeeFor],
 [WaiveMbrshipFeeFrom],
 [WaiveOverLimitFeeFor],
 [WaiveOverLimitFeeFrom],
 [WaiveNSFFor],
 [WaiveNSFFrom],
 [WaiveMinDueFor],
 [WaiveMinDueFrom],
 [WaiveInsPremiumFor],
 [WaiveInsPremiumFrom],
 [WaiveInterest],
 [WaiveInterestFor],
 [WaiveInterestFrom],
 [WaiveAnnualChgAction],
 [WaiveAnnualChgFor],
 [WaiveAnnualChgFrom],
 [WaiveServiceFeeAction],
 [WaiveServiceFeeFor],
 [WaiveServiceFeeFrom],
 [WaiveTransactionFeeAction],
 [WaiveTransactionFeeFor],
 [WaiveTransactionFeeFrom],
 [WaiveCardFeeAction],
 [WaiveCardFeeFor],
 [WaiveCardFeeFrom],
 [WaiveAuthFeeAction],
 [WaiveAuthFeeFor],
 [WaiveAuthFeeFrom],
 [WaiveMessageFeeAction],
 [WaiveMessageFeeFor],
 [WaiveMessageFeeFrom],
 [CBRStatusGroup],
 [ExcludeFromCBR],
 [ComplianceConditionCode],
 [SpecialComment],
 [HoldStatement],
 [SelfServiceAccess],
 [PO_ASCheckOTB],
 [PO_ASCBRAction],
 [PO_ASCBureauStatus],
 [PO_ASEligibikityForInsurance],
 [PO_FinanceChargeAct],
 [PO_ASInsCancellationAct],
 [PO_LoyaltyPointsAcc],
 [PO_ReissueOrIssue],
 [PO_ASPostingReason],
 [PO_ASRevolvingPaymentAction],
 [PO_ASStatementAction],
 [PO_ASTransactionPosting],
 [PO_deHoldStatement],
 [PO_AsStatusAccRpt],
 [PO_ASWLateChargeAct],
 [PO_ASWMembFeeAct],
 [PO_ASWOverLimFeeAct],
 [PO_ASWNSFAction],
 [PO_ASStatementDelivery],
 [PO_ASWaiveMinDue],
 [PO_ASWaiveInterest],
 [PO_ASWaiveInsPremium],
 [PO_ASWaiveTxnFeeAct],
 [PO_ASWaiveAuthFeeAct],
 [PO_ASWaiveCardFeeAct],
 [PO_ASWAnnualChgAct],
 [PO_ASWMessageFeeAct],
 [PO_ASWServiceFeeAct],
 [LoyaltyDebits],
 [SchedulePayments]) VALUES ( @acctId,
 @ATID,
 @rowClassifier,
 @grpClassifier,
 @LAD,
 @LAPD,
 @NAD,
 @AccountBlob,
 @StatementDate,
 @parent01ATID,
 @parent01AID,
 @parent02ATID,
 @parent02AID,
 @parent03ATID,
 @parent03AID,
 @parent04ATID,
 @parent04AID,
 @parent05ATID,
 @parent05AID,
 @MerchantAID,
 @Priority,
 @StatusDescription,
 @PostingReason,
 @StatusAcctReport,
 @TransactionPosting,
 @Reissue_IssueAction,
 @AuthAction,
 @FinanceChargeAction,
 @WaiveLateChargeAction,
 @WaiveMbrshipFeeAction,
 @WaiveOverLimitFeeAction,
 @WaiveNSFAction,
 @StatementAction,
 @RevolvingPaymentAction,
 @InsCancellationAction,
 @CreditBureauRptgAction,
 @CreditBureauStatus,
 @CheckOTB,
 @CollectionFlagsbyStatus,
 @StatementDelivery,
 @WaiveMinDue,
 @WaiveInsPremium,
 @SetDunSuppress,
 @EligibleForInsurance,
 @lastupdate,
 @ASResActionCode,
 @ASCCaseActionCode,
 @ACOverridePriority,
 @LoyaltyPointsAccumulation,
 @Email,
 @GenerateSMS,
 @GenerateLetter,
 @LoadAuthAction,
 @AuthActionVisa,
 @AuthActionDiscover,
 @AuthActionPrivateLabel,
 @ResponseCodeVisa,
 @ResponseCodeMC,
 @ResponseCodeDiscover,
 @ResponseCodePrivateLabel,
 @LoadAuthActionVisa,
 @LoadAuthActionDiscover,
 @LoadAuthActionPrivateLabel,
 @LoadResponseCodeVISA,
 @LoadResponseCodeMC,
 @LoadResponseCodeDiscover,
 @LoadResponseCodePrivateLabel,
 @tpyNAD,
 @tpyLAD,
 @tpyBlob,
 @WaiveLateChargeFor,
 @WaiveLateChargeFrom,
 @WaiveMbrshipFeeFor,
 @WaiveMbrshipFeeFrom,
 @WaiveOverLimitFeeFor,
 @WaiveOverLimitFeeFrom,
 @WaiveNSFFor,
 @WaiveNSFFrom,
 @WaiveMinDueFor,
 @WaiveMinDueFrom,
 @WaiveInsPremiumFor,
 @WaiveInsPremiumFrom,
 @WaiveInterest,
 @WaiveInterestFor,
 @WaiveInterestFrom,
 @WaiveAnnualChgAction,
 @WaiveAnnualChgFor,
 @WaiveAnnualChgFrom,
 @WaiveServiceFeeAction,
 @WaiveServiceFeeFor,
 @WaiveServiceFeeFrom,
 @WaiveTransactionFeeAction,
 @WaiveTransactionFeeFor,
 @WaiveTransactionFeeFrom,
 @WaiveCardFeeAction,
 @WaiveCardFeeFor,
 @WaiveCardFeeFrom,
 @WaiveAuthFeeAction,
 @WaiveAuthFeeFor,
 @WaiveAuthFeeFrom,
 @WaiveMessageFeeAction,
 @WaiveMessageFeeFor,
 @WaiveMessageFeeFrom,
 @CBRStatusGroup,
 @ExcludeFromCBR,
 @ComplianceConditionCode,
 @SpecialComment,
 @HoldStatement,
 @SelfServiceAccess,
 @PO_ASCheckOTB,
 @PO_ASCBRAction,
 @PO_ASCBureauStatus,
 @PO_ASEligibikityForInsurance,
 @PO_FinanceChargeAct,
 @PO_ASInsCancellationAct,
 @PO_LoyaltyPointsAcc,
 @PO_ReissueOrIssue,
 @PO_ASPostingReason,
 @PO_ASRevolvingPaymentAction,
 @PO_ASStatementAction,
 @PO_ASTransactionPosting,
 @PO_deHoldStatement,
 @PO_AsStatusAccRpt,
 @PO_ASWLateChargeAct,
 @PO_ASWMembFeeAct,
 @PO_ASWOverLimFeeAct,
 @PO_ASWNSFAction,
 @PO_ASStatementDelivery,
 @PO_ASWaiveMinDue,
 @PO_ASWaiveInterest,
 @PO_ASWaiveInsPremium,
 @PO_ASWaiveTxnFeeAct,
 @PO_ASWaiveAuthFeeAct,
 @PO_ASWaiveCardFeeAct,
 @PO_ASWAnnualChgAct,
 @PO_ASWMessageFeeAct,
 @PO_ASWServiceFeeAct,
 @LoyaltyDebits,
 @SchedulePayments)
GO

grant execute on sp_AStatusAccounts_insupd to public 
GO

/* End of object g_AStatus_acms */
