/* Start of object msBSegmentCreditCard */

ALTER TABLE BSegmentCreditCard ADD [BankruptcyFileDate] datetime NULL
GO

if exists (select * from sysobjects where 
 id = object_id('sp_BSegmentCreditCard_qsel') and sysstat & 0xf = 4)
drop procedure sp_BSegmentCreditCard_qsel
GO
CREATE PROCEDURE sp_BSegmentCreditCard_qsel(  @acctId int ) AS
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET QUOTED_IDENTIFIER ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;
SELECT
 [acctId],
 [FixedPaymentAmt],
 [FixedPaymentPercent],
 [PaymentLevel],
 [PaymentType],
 [AmountOfPayment120DLate],
 [AmountOfPayment150DLate],
 [AmountOfPayment180DLate],
 [AmountOfPayment210DLate],
 [AmountOfPayment30DLate],
 [AmountOfPayment60DLate],
 [AmountOfPayment90DLate],
 [AmtOfPayXDLate],
 [AmountOfTotalDue],
 [AutoSkipPaymentOpt],
 [pmtpriority],
 [BalSubjPayment],
 [SkipPayOptInEffect],
 [TempBalSubjPayment],
 [TempCurrentDue],
 [WaiveInterest],
 [BSWFeeIntStartDate],
 [DtOfLastDelinqCTD],
 [DateOfOriginalPaymentDueDTD],
 [DateOfTotalDue],
 [NumberTimesReaged],
 [LastSkipPymtDate],
 [LastSkipPymtAmt],
 [NoOfSkipPymts],
 [NoPayDaysDelinquent],
 [VirtualHdOfDelqChain],
 [CollReasonCode],
 [NextPaymentDueDate],
 [NumberOfPaymentPastDue],
 [NumberOfPayment30DLate],
 [NumberOfPayment60DLate],
 [NumberOfPayment90DLate],
 [NumberOfPayment120DLate],
 [NumberOfPayment150DLate],
 [NumberOfPayment180DLate],
 [NumberOfPayment210DLate],
 [daysdelinquent],
 [HighDelqBalanceLTD],
 [HighCyclePastDueLTD],
 [InterestDisclCycle],
 [InterestDisclMethod],
 [AmtGenIntCredits],
 [AmtGenInterestCreditsLTD],
 [AmtGenInterestCreditsYTD],
 [AmtInterestCreditsCTD],
 [AmtInterestCreditsLTD],
 [AmtInterestCreditsYTD],
 [AutoFinalChargeOffTiming],
 [ChrgdOffAcctAccrMeth],
 [ChargeOffAccountStatus],
 [ChargeOffDate],
 [DirectDebitPayStatus],
 [FinalChargeOffDate],
 [NbrOfDaysUntilChargeOff],
 [SystemChargeOffStatus],
 [UserChargeOffStatus],
 [InsFundsFeeNotChgOff],
 [ChargeOffStatement],
 [collectionfeesbnpco],
 [currentbalanceco],
 [DelinHistoryCtrCTD],
 [AmtOfInterestCTD],
 [AmtOfInterestLTD],
 [AmtOfInterestMTD],
 [AmtOfInterestYTD],
 [IntAccrCycle],
 [AfterCycleRevolvBSFC],
 [AggregateDays],
 [IntBilledNotPaid],
 [interestbnpco],
 [DeferredAccrued],
 [DeferredAggregate],
 [DeferredAggDays],
 [NewTransactionsAccrued],
 [NewTransactionsAgg],
 [NewTransactionsBSFC],
 [InterestPerDiem],
 [RevolvingAccrued],
 [RevolvingAgg],
 [RevolvingBSFC],
 [TotalAccruedInterest],
 [TotalBSFC],
 [latefeesbnpco],
 [membershipfeesbnpco],
 [nsffeesbnpco],
 [overlimitfeesbnpco],
 [PayHistoryCtrCTD],
 [PrePaidAmount],
 [principalco],
 [ratechgeffdate],
 [recoveryfeesbnpco],
 [totalamountco],
 [servicefeesbnpco],
 [AutoInitialChargeOffReason],
 [AutoInitialChargeOffStartDate],
 [ManualInitialChargeOffReason],
 [ManualInitialChargeOffStartDate],
 [ChargeOffProcessIndicator],
 [ChargeOffDateParam],
 [FinalChargeOffDateParam],
 [AutoInitialChargeOffCriteria],
 [AutoInitialChargeOffCriteria_t],
 [AutoInitialChargeOffCriteria_m],
 [AutoInitialChargeOffFreq],
 [AutoFinalChargeOffCriteria],
 [AutoFinalChargeOffCriteria_t],
 [AutoFinalChargeOffCriteria_m],
 [AutoFinalChargeOffPeriod],
 [AutoFinalChargeOffFreq],
 [ReageDate1],
 [ReageDate2],
 [ReageDate3],
 [ReageDate4],
 [ReageDate5],
 [ReageDate6],
 [ReageTypeIndic1],
 [ReageTypeIndic2],
 [ReageTypeIndic3],
 [ReageTypeIndic4],
 [ReageTypeIndic5],
 [ReageTypeIndic6],
 [AmountOfPaymentsDTD],
 [PastDueRangeAmt1],
 [PastDueRangeAmt2],
 [PastDueRangeAmt3],
 [PastDueRangeAmt4],
 [PastDueRangeAmt5],
 [PastDueRangeAmt6],
 [PastDueRangeAmt7],
 [PastDueRangeAmt8],
 [PastDueRangeCnt1],
 [PastDueRangeCnt2],
 [PastDueRangeCnt3],
 [PastDueRangeCnt4],
 [PastDueRangeCnt5],
 [PastDueRangeCnt6],
 [PastDueRangeCnt7],
 [PastDueRangeCnt8],
 [CurrentDue],
 [FirstDueDate],
 [WaiveInterestFor],
 [WaiveInterestFrom],
 [InsFundsFeeNotChgOffFor],
 [InsFundsFeeNotChgOffFrom],
 [FinalCOAmount],
 [PrincipalDefCTD],
 [PrincipalDefCC1],
 [PrincipalDefCC2],
 [PrincipalDefCC3],
 [PrincipalDefAdjustment],
 [OverlimitFeeAdjustment],
 [AmountOfCreditsAsPmt],
 [AmountOfCreditsAsPmtCTD],
 [AmountOfCreditsAsPmtCC1],
 [AmountOfCreditsAsPmtCC2],
 [AmountOfCreditsAsPmtCC3],
 [AmountOfCreditsAsPmtMTD],
 [AmountOfCreditsAsPmtQTD],
 [AmountOfCreditsAsPmtYTD],
 [AmountOfCreditsAsPmtLTD],
 [PendingBalIndicator],
 [PlanCancelationDate],
 [BeginningBalance_TranTime],
 [YTDFeesTotalOnly],
 [YTDIntTotalsOnly],
 [CTDtotalFeesDebit],
 [CTDtotalFeesCredit],
 [CTDtotalIntDebit],
 [CTDtotalIntCredit],
 [CTDLateFees],
 [CTDLateFeesCredit],
 [CTDLateFeesDebit],
 [YTDLateFees],
 [CTDNSFFees],
 [CTDNSFFeesCredit],
 [CTDNSFFeesDebit],
 [YTDNSFFees],
 [CTDMinimumCharge],
 [CTDMinimumChargeCredit],
 [CTDMinimumChargeDebit],
 [YTDMinimumCharge],
 [COEligibilityDate],
 [AccountOpenDate],
 [AutoDispInitiateDate],
 [FirstLateFeeWaiveDate],
 [OverlimitBalanceCTD],
 [AccumulatedOverlimitBalance],
 [OriginalDueDate],
 [LDStatusUpdateDate],
 [AnticipatedPayOffAmount],
 [DlqOneCpdLtdCount],
 [DlqTwoCpdLtdCount],
 [DlqThreePlusCpdLtdCount],
 [PriEmbActivationFlag],
 [DMinThrhldAutoResCount],
 [TotalTransactionFeesCO],
 [TotalLateFeesCO],
 [TotalInsufficientFundsFeesCO],
 [TotalOverlimitFeesCO],
 [TotalInsurancePremiumsCO],
 [TotalCollectionExpensesCO],
 [TotalOtherFeesCO],
 [TotalAnnualFeesCO],
 [TotalInterestCO],
 [TotalPrincipalCO],
 [StatementRunningBalance],
 [StatementRemainingBalance],
 [RecoveryFeeDate],
 [QualifiedCycleCountRecoveryfee],
 [AcctInDelinq2Status],
 [CollateralID],
 [RegZ52aEndDate],
 [RegZ52aAmountThreshold],
 [RegZ52aFeeAmountYTD],
 [RunningMinimumDue],
 [RemainingMinimumDue],
 [CycleDue_DTDAtChargeoff],
 [BankruptcyFileDate]
FROM DBO.BSegmentCreditCard
WHERE 
   [acctId] = @acctId 
GO
grant execute on sp_BSegmentCreditCard_qsel to public 
GO

if exists (select * from sysobjects where 
 id = object_id('sp_BSegmentCreditCard_qslk') and sysstat & 0xf = 4)
drop procedure sp_BSegmentCreditCard_qslk
GO
CREATE PROCEDURE sp_BSegmentCreditCard_qslk(  @acctId int ) AS
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET QUOTED_IDENTIFIER ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;
SELECT
 [acctId],
 [FixedPaymentAmt],
 [FixedPaymentPercent],
 [PaymentLevel],
 [PaymentType],
 [AmountOfPayment120DLate],
 [AmountOfPayment150DLate],
 [AmountOfPayment180DLate],
 [AmountOfPayment210DLate],
 [AmountOfPayment30DLate],
 [AmountOfPayment60DLate],
 [AmountOfPayment90DLate],
 [AmtOfPayXDLate],
 [AmountOfTotalDue],
 [AutoSkipPaymentOpt],
 [pmtpriority],
 [BalSubjPayment],
 [SkipPayOptInEffect],
 [TempBalSubjPayment],
 [TempCurrentDue],
 [WaiveInterest],
 [BSWFeeIntStartDate],
 [DtOfLastDelinqCTD],
 [DateOfOriginalPaymentDueDTD],
 [DateOfTotalDue],
 [NumberTimesReaged],
 [LastSkipPymtDate],
 [LastSkipPymtAmt],
 [NoOfSkipPymts],
 [NoPayDaysDelinquent],
 [VirtualHdOfDelqChain],
 [CollReasonCode],
 [NextPaymentDueDate],
 [NumberOfPaymentPastDue],
 [NumberOfPayment30DLate],
 [NumberOfPayment60DLate],
 [NumberOfPayment90DLate],
 [NumberOfPayment120DLate],
 [NumberOfPayment150DLate],
 [NumberOfPayment180DLate],
 [NumberOfPayment210DLate],
 [daysdelinquent],
 [HighDelqBalanceLTD],
 [HighCyclePastDueLTD],
 [InterestDisclCycle],
 [InterestDisclMethod],
 [AmtGenIntCredits],
 [AmtGenInterestCreditsLTD],
 [AmtGenInterestCreditsYTD],
 [AmtInterestCreditsCTD],
 [AmtInterestCreditsLTD],
 [AmtInterestCreditsYTD],
 [AutoFinalChargeOffTiming],
 [ChrgdOffAcctAccrMeth],
 [ChargeOffAccountStatus],
 [ChargeOffDate],
 [DirectDebitPayStatus],
 [FinalChargeOffDate],
 [NbrOfDaysUntilChargeOff],
 [SystemChargeOffStatus],
 [UserChargeOffStatus],
 [InsFundsFeeNotChgOff],
 [ChargeOffStatement],
 [collectionfeesbnpco],
 [currentbalanceco],
 [DelinHistoryCtrCTD],
 [AmtOfInterestCTD],
 [AmtOfInterestLTD],
 [AmtOfInterestMTD],
 [AmtOfInterestYTD],
 [IntAccrCycle],
 [AfterCycleRevolvBSFC],
 [AggregateDays],
 [IntBilledNotPaid],
 [interestbnpco],
 [DeferredAccrued],
 [DeferredAggregate],
 [DeferredAggDays],
 [NewTransactionsAccrued],
 [NewTransactionsAgg],
 [NewTransactionsBSFC],
 [InterestPerDiem],
 [RevolvingAccrued],
 [RevolvingAgg],
 [RevolvingBSFC],
 [TotalAccruedInterest],
 [TotalBSFC],
 [latefeesbnpco],
 [membershipfeesbnpco],
 [nsffeesbnpco],
 [overlimitfeesbnpco],
 [PayHistoryCtrCTD],
 [PrePaidAmount],
 [principalco],
 [ratechgeffdate],
 [recoveryfeesbnpco],
 [totalamountco],
 [servicefeesbnpco],
 [AutoInitialChargeOffReason],
 [AutoInitialChargeOffStartDate],
 [ManualInitialChargeOffReason],
 [ManualInitialChargeOffStartDate],
 [ChargeOffProcessIndicator],
 [ChargeOffDateParam],
 [FinalChargeOffDateParam],
 [AutoInitialChargeOffCriteria],
 [AutoInitialChargeOffCriteria_t],
 [AutoInitialChargeOffCriteria_m],
 [AutoInitialChargeOffFreq],
 [AutoFinalChargeOffCriteria],
 [AutoFinalChargeOffCriteria_t],
 [AutoFinalChargeOffCriteria_m],
 [AutoFinalChargeOffPeriod],
 [AutoFinalChargeOffFreq],
 [ReageDate1],
 [ReageDate2],
 [ReageDate3],
 [ReageDate4],
 [ReageDate5],
 [ReageDate6],
 [ReageTypeIndic1],
 [ReageTypeIndic2],
 [ReageTypeIndic3],
 [ReageTypeIndic4],
 [ReageTypeIndic5],
 [ReageTypeIndic6],
 [AmountOfPaymentsDTD],
 [PastDueRangeAmt1],
 [PastDueRangeAmt2],
 [PastDueRangeAmt3],
 [PastDueRangeAmt4],
 [PastDueRangeAmt5],
 [PastDueRangeAmt6],
 [PastDueRangeAmt7],
 [PastDueRangeAmt8],
 [PastDueRangeCnt1],
 [PastDueRangeCnt2],
 [PastDueRangeCnt3],
 [PastDueRangeCnt4],
 [PastDueRangeCnt5],
 [PastDueRangeCnt6],
 [PastDueRangeCnt7],
 [PastDueRangeCnt8],
 [CurrentDue],
 [FirstDueDate],
 [WaiveInterestFor],
 [WaiveInterestFrom],
 [InsFundsFeeNotChgOffFor],
 [InsFundsFeeNotChgOffFrom],
 [FinalCOAmount],
 [PrincipalDefCTD],
 [PrincipalDefCC1],
 [PrincipalDefCC2],
 [PrincipalDefCC3],
 [PrincipalDefAdjustment],
 [OverlimitFeeAdjustment],
 [AmountOfCreditsAsPmt],
 [AmountOfCreditsAsPmtCTD],
 [AmountOfCreditsAsPmtCC1],
 [AmountOfCreditsAsPmtCC2],
 [AmountOfCreditsAsPmtCC3],
 [AmountOfCreditsAsPmtMTD],
 [AmountOfCreditsAsPmtQTD],
 [AmountOfCreditsAsPmtYTD],
 [AmountOfCreditsAsPmtLTD],
 [PendingBalIndicator],
 [PlanCancelationDate],
 [BeginningBalance_TranTime],
 [YTDFeesTotalOnly],
 [YTDIntTotalsOnly],
 [CTDtotalFeesDebit],
 [CTDtotalFeesCredit],
 [CTDtotalIntDebit],
 [CTDtotalIntCredit],
 [CTDLateFees],
 [CTDLateFeesCredit],
 [CTDLateFeesDebit],
 [YTDLateFees],
 [CTDNSFFees],
 [CTDNSFFeesCredit],
 [CTDNSFFeesDebit],
 [YTDNSFFees],
 [CTDMinimumCharge],
 [CTDMinimumChargeCredit],
 [CTDMinimumChargeDebit],
 [YTDMinimumCharge],
 [COEligibilityDate],
 [AccountOpenDate],
 [AutoDispInitiateDate],
 [FirstLateFeeWaiveDate],
 [OverlimitBalanceCTD],
 [AccumulatedOverlimitBalance],
 [OriginalDueDate],
 [LDStatusUpdateDate],
 [AnticipatedPayOffAmount],
 [DlqOneCpdLtdCount],
 [DlqTwoCpdLtdCount],
 [DlqThreePlusCpdLtdCount],
 [PriEmbActivationFlag],
 [DMinThrhldAutoResCount],
 [TotalTransactionFeesCO],
 [TotalLateFeesCO],
 [TotalInsufficientFundsFeesCO],
 [TotalOverlimitFeesCO],
 [TotalInsurancePremiumsCO],
 [TotalCollectionExpensesCO],
 [TotalOtherFeesCO],
 [TotalAnnualFeesCO],
 [TotalInterestCO],
 [TotalPrincipalCO],
 [StatementRunningBalance],
 [StatementRemainingBalance],
 [RecoveryFeeDate],
 [QualifiedCycleCountRecoveryfee],
 [AcctInDelinq2Status],
 [CollateralID],
 [RegZ52aEndDate],
 [RegZ52aAmountThreshold],
 [RegZ52aFeeAmountYTD],
 [RunningMinimumDue],
 [RemainingMinimumDue],
 [CycleDue_DTDAtChargeoff],
 [BankruptcyFileDate]
FROM DBO.BSegmentCreditCard with (updlock)
WHERE 
   [acctId] = @acctId 
GO
grant execute on sp_BSegmentCreditCard_qslk to public 
GO

if exists (select * from sysobjects where 
 id = object_id('sp_BSegmentCreditCard_sel') and sysstat & 0xf = 4)
drop procedure sp_BSegmentCreditCard_sel
GO
CREATE PROCEDURE sp_BSegmentCreditCard_sel AS
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET QUOTED_IDENTIFIER ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;

SELECT [acctId],
 [FixedPaymentAmt],
 [FixedPaymentPercent],
 [PaymentLevel],
 [PaymentType],
 [AmountOfPayment120DLate],
 [AmountOfPayment150DLate],
 [AmountOfPayment180DLate],
 [AmountOfPayment210DLate],
 [AmountOfPayment30DLate],
 [AmountOfPayment60DLate],
 [AmountOfPayment90DLate],
 [AmtOfPayXDLate],
 [AmountOfTotalDue],
 [AutoSkipPaymentOpt],
 [pmtpriority],
 [BalSubjPayment],
 [SkipPayOptInEffect],
 [TempBalSubjPayment],
 [TempCurrentDue],
 [WaiveInterest],
 [BSWFeeIntStartDate],
 [DtOfLastDelinqCTD],
 [DateOfOriginalPaymentDueDTD],
 [DateOfTotalDue],
 [NumberTimesReaged],
 [LastSkipPymtDate],
 [LastSkipPymtAmt],
 [NoOfSkipPymts],
 [NoPayDaysDelinquent],
 [VirtualHdOfDelqChain],
 [CollReasonCode],
 [NextPaymentDueDate],
 [NumberOfPaymentPastDue],
 [NumberOfPayment30DLate],
 [NumberOfPayment60DLate],
 [NumberOfPayment90DLate],
 [NumberOfPayment120DLate],
 [NumberOfPayment150DLate],
 [NumberOfPayment180DLate],
 [NumberOfPayment210DLate],
 [daysdelinquent],
 [HighDelqBalanceLTD],
 [HighCyclePastDueLTD],
 [InterestDisclCycle],
 [InterestDisclMethod],
 [AmtGenIntCredits],
 [AmtGenInterestCreditsLTD],
 [AmtGenInterestCreditsYTD],
 [AmtInterestCreditsCTD],
 [AmtInterestCreditsLTD],
 [AmtInterestCreditsYTD],
 [AutoFinalChargeOffTiming],
 [ChrgdOffAcctAccrMeth],
 [ChargeOffAccountStatus],
 [ChargeOffDate],
 [DirectDebitPayStatus],
 [FinalChargeOffDate],
 [NbrOfDaysUntilChargeOff],
 [SystemChargeOffStatus],
 [UserChargeOffStatus],
 [InsFundsFeeNotChgOff],
 [ChargeOffStatement],
 [collectionfeesbnpco],
 [currentbalanceco],
 [DelinHistoryCtrCTD],
 [AmtOfInterestCTD],
 [AmtOfInterestLTD],
 [AmtOfInterestMTD],
 [AmtOfInterestYTD],
 [IntAccrCycle],
 [AfterCycleRevolvBSFC],
 [AggregateDays],
 [IntBilledNotPaid],
 [interestbnpco],
 [DeferredAccrued],
 [DeferredAggregate],
 [DeferredAggDays],
 [NewTransactionsAccrued],
 [NewTransactionsAgg],
 [NewTransactionsBSFC],
 [InterestPerDiem],
 [RevolvingAccrued],
 [RevolvingAgg],
 [RevolvingBSFC],
 [TotalAccruedInterest],
 [TotalBSFC],
 [latefeesbnpco],
 [membershipfeesbnpco],
 [nsffeesbnpco],
 [overlimitfeesbnpco],
 [PayHistoryCtrCTD],
 [PrePaidAmount],
 [principalco],
 [ratechgeffdate],
 [recoveryfeesbnpco],
 [totalamountco],
 [servicefeesbnpco],
 [AutoInitialChargeOffReason],
 [AutoInitialChargeOffStartDate],
 [ManualInitialChargeOffReason],
 [ManualInitialChargeOffStartDate],
 [ChargeOffProcessIndicator],
 [ChargeOffDateParam],
 [FinalChargeOffDateParam],
 [AutoInitialChargeOffCriteria],
 [AutoInitialChargeOffCriteria_t],
 [AutoInitialChargeOffCriteria_m],
 [AutoInitialChargeOffFreq],
 [AutoFinalChargeOffCriteria],
 [AutoFinalChargeOffCriteria_t],
 [AutoFinalChargeOffCriteria_m],
 [AutoFinalChargeOffPeriod],
 [AutoFinalChargeOffFreq],
 [ReageDate1],
 [ReageDate2],
 [ReageDate3],
 [ReageDate4],
 [ReageDate5],
 [ReageDate6],
 [ReageTypeIndic1],
 [ReageTypeIndic2],
 [ReageTypeIndic3],
 [ReageTypeIndic4],
 [ReageTypeIndic5],
 [ReageTypeIndic6],
 [AmountOfPaymentsDTD],
 [PastDueRangeAmt1],
 [PastDueRangeAmt2],
 [PastDueRangeAmt3],
 [PastDueRangeAmt4],
 [PastDueRangeAmt5],
 [PastDueRangeAmt6],
 [PastDueRangeAmt7],
 [PastDueRangeAmt8],
 [PastDueRangeCnt1],
 [PastDueRangeCnt2],
 [PastDueRangeCnt3],
 [PastDueRangeCnt4],
 [PastDueRangeCnt5],
 [PastDueRangeCnt6],
 [PastDueRangeCnt7],
 [PastDueRangeCnt8],
 [CurrentDue],
 [FirstDueDate],
 [WaiveInterestFor],
 [WaiveInterestFrom],
 [InsFundsFeeNotChgOffFor],
 [InsFundsFeeNotChgOffFrom],
 [FinalCOAmount],
 [PrincipalDefCTD],
 [PrincipalDefCC1],
 [PrincipalDefCC2],
 [PrincipalDefCC3],
 [PrincipalDefAdjustment],
 [OverlimitFeeAdjustment],
 [AmountOfCreditsAsPmt],
 [AmountOfCreditsAsPmtCTD],
 [AmountOfCreditsAsPmtCC1],
 [AmountOfCreditsAsPmtCC2],
 [AmountOfCreditsAsPmtCC3],
 [AmountOfCreditsAsPmtMTD],
 [AmountOfCreditsAsPmtQTD],
 [AmountOfCreditsAsPmtYTD],
 [AmountOfCreditsAsPmtLTD],
 [PendingBalIndicator],
 [PlanCancelationDate],
 [BeginningBalance_TranTime],
 [YTDFeesTotalOnly],
 [YTDIntTotalsOnly],
 [CTDtotalFeesDebit],
 [CTDtotalFeesCredit],
 [CTDtotalIntDebit],
 [CTDtotalIntCredit],
 [CTDLateFees],
 [CTDLateFeesCredit],
 [CTDLateFeesDebit],
 [YTDLateFees],
 [CTDNSFFees],
 [CTDNSFFeesCredit],
 [CTDNSFFeesDebit],
 [YTDNSFFees],
 [CTDMinimumCharge],
 [CTDMinimumChargeCredit],
 [CTDMinimumChargeDebit],
 [YTDMinimumCharge],
 [COEligibilityDate],
 [AccountOpenDate],
 [AutoDispInitiateDate],
 [FirstLateFeeWaiveDate],
 [OverlimitBalanceCTD],
 [AccumulatedOverlimitBalance],
 [OriginalDueDate],
 [LDStatusUpdateDate],
 [AnticipatedPayOffAmount],
 [DlqOneCpdLtdCount],
 [DlqTwoCpdLtdCount],
 [DlqThreePlusCpdLtdCount],
 [PriEmbActivationFlag],
 [DMinThrhldAutoResCount],
 [TotalTransactionFeesCO],
 [TotalLateFeesCO],
 [TotalInsufficientFundsFeesCO],
 [TotalOverlimitFeesCO],
 [TotalInsurancePremiumsCO],
 [TotalCollectionExpensesCO],
 [TotalOtherFeesCO],
 [TotalAnnualFeesCO],
 [TotalInterestCO],
 [TotalPrincipalCO],
 [StatementRunningBalance],
 [StatementRemainingBalance],
 [RecoveryFeeDate],
 [QualifiedCycleCountRecoveryfee],
 [AcctInDelinq2Status],
 [CollateralID],
 [RegZ52aEndDate],
 [RegZ52aAmountThreshold],
 [RegZ52aFeeAmountYTD],
 [RunningMinimumDue],
 [RemainingMinimumDue],
 [CycleDue_DTDAtChargeoff],
 [BankruptcyFileDate]
FROM DBO.BSegmentCreditCard WITH (NOLOCK)
GO

grant execute on sp_BSegmentCreditCard_sel to public 
GO

if exists (select * from sysobjects where 
 id = object_id('sp_BSegmentCreditCard_del') and sysstat & 0xf = 4)
drop procedure sp_BSegmentCreditCard_del
GO
CREATE PROCEDURE sp_BSegmentCreditCard_del(  @acctId int ) AS
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET QUOTED_IDENTIFIER ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;
DELETE FROM DBO.BSegmentCreditCard
WHERE 
   [acctId] = @acctId 
GO
grant execute on sp_BSegmentCreditCard_del to public 
GO


if exists (select * from sysobjects where 
 id = object_id('sp_BSegmentCreditCard_upd') and sysstat & 0xf = 4)
drop procedure sp_BSegmentCreditCard_upd
GO
CREATE PROCEDURE sp_BSegmentCreditCard_upd  @acctId int,
  @FixedPaymentAmt money,
  @FixedPaymentPercent money,
  @PaymentLevel char (5),
  @PaymentType char (5),
  @AmountOfPayment120DLate money,
  @AmountOfPayment150DLate money,
  @AmountOfPayment180DLate money,
  @AmountOfPayment210DLate money,
  @AmountOfPayment30DLate money,
  @AmountOfPayment60DLate money,
  @AmountOfPayment90DLate money,
  @AmtOfPayXDLate money,
  @AmountOfTotalDue money,
  @AutoSkipPaymentOpt char (5),
  @pmtpriority char (2),
  @BalSubjPayment money,
  @SkipPayOptInEffect char (5),
  @TempBalSubjPayment money,
  @TempCurrentDue money,
  @WaiveInterest char (5),
  @BSWFeeIntStartDate datetime,
  @DtOfLastDelinqCTD datetime,
  @DateOfOriginalPaymentDueDTD datetime,
  @DateOfTotalDue datetime,
  @NumberTimesReaged int,
  @LastSkipPymtDate datetime,
  @LastSkipPymtAmt money,
  @NoOfSkipPymts int,
  @NoPayDaysDelinquent int,
  @VirtualHdOfDelqChain money,
  @CollReasonCode char (5),
  @NextPaymentDueDate datetime,
  @NumberOfPaymentPastDue int,
  @NumberOfPayment30DLate int,
  @NumberOfPayment60DLate int,
  @NumberOfPayment90DLate int,
  @NumberOfPayment120DLate int,
  @NumberOfPayment150DLate int,
  @NumberOfPayment180DLate int,
  @NumberOfPayment210DLate int,
  @daysdelinquent int,
  @HighDelqBalanceLTD money,
  @HighCyclePastDueLTD money,
  @InterestDisclCycle char (5),
  @InterestDisclMethod char (5),
  @AmtGenIntCredits money,
  @AmtGenInterestCreditsLTD money,
  @AmtGenInterestCreditsYTD money,
  @AmtInterestCreditsCTD money,
  @AmtInterestCreditsLTD money,
  @AmtInterestCreditsYTD money,
  @AutoFinalChargeOffTiming char (5),
  @ChrgdOffAcctAccrMeth char (5),
  @ChargeOffAccountStatus int,
  @ChargeOffDate datetime,
  @DirectDebitPayStatus char (5),
  @FinalChargeOffDate datetime,
  @NbrOfDaysUntilChargeOff int,
  @SystemChargeOffStatus char (5),
  @UserChargeOffStatus char (5),
  @InsFundsFeeNotChgOff char (5),
  @ChargeOffStatement char (5),
  @collectionfeesbnpco money,
  @currentbalanceco money,
  @DelinHistoryCtrCTD int,
  @AmtOfInterestCTD money,
  @AmtOfInterestLTD money,
  @AmtOfInterestMTD money,
  @AmtOfInterestYTD money,
  @IntAccrCycle money,
  @AfterCycleRevolvBSFC money,
  @AggregateDays int,
  @IntBilledNotPaid money,
  @interestbnpco money,
  @DeferredAccrued money,
  @DeferredAggregate money,
  @DeferredAggDays int,
  @NewTransactionsAccrued decimal(19,10),
  @NewTransactionsAgg money,
  @NewTransactionsBSFC money,
  @InterestPerDiem money,
  @RevolvingAccrued decimal(19,10),
  @RevolvingAgg money,
  @RevolvingBSFC money,
  @TotalAccruedInterest money,
  @TotalBSFC money,
  @latefeesbnpco money,
  @membershipfeesbnpco money,
  @nsffeesbnpco money,
  @overlimitfeesbnpco money,
  @PayHistoryCtrCTD int,
  @PrePaidAmount money,
  @principalco money,
  @ratechgeffdate datetime,
  @recoveryfeesbnpco money,
  @totalamountco money,
  @servicefeesbnpco money,
  @AutoInitialChargeOffReason char (5),
  @AutoInitialChargeOffStartDate datetime,
  @ManualInitialChargeOffReason char (5),
  @ManualInitialChargeOffStartDate datetime,
  @ChargeOffProcessIndicator char (5),
  @ChargeOffDateParam datetime,
  @FinalChargeOffDateParam datetime,
  @AutoInitialChargeOffCriteria char (5),
  @AutoInitialChargeOffCriteria_t char (5),
  @AutoInitialChargeOffCriteria_m char (5),
  @AutoInitialChargeOffFreq char (5),
  @AutoFinalChargeOffCriteria char (5),
  @AutoFinalChargeOffCriteria_t char (5),
  @AutoFinalChargeOffCriteria_m char (5),
  @AutoFinalChargeOffPeriod int,
  @AutoFinalChargeOffFreq char (5),
  @ReageDate1 datetime,
  @ReageDate2 datetime,
  @ReageDate3 datetime,
  @ReageDate4 datetime,
  @ReageDate5 datetime,
  @ReageDate6 datetime,
  @ReageTypeIndic1 int,
  @ReageTypeIndic2 int,
  @ReageTypeIndic3 int,
  @ReageTypeIndic4 int,
  @ReageTypeIndic5 int,
  @ReageTypeIndic6 int,
  @AmountOfPaymentsDTD money,
  @PastDueRangeAmt1 money,
  @PastDueRangeAmt2 money,
  @PastDueRangeAmt3 money,
  @PastDueRangeAmt4 money,
  @PastDueRangeAmt5 money,
  @PastDueRangeAmt6 money,
  @PastDueRangeAmt7 money,
  @PastDueRangeAmt8 money,
  @PastDueRangeCnt1 int,
  @PastDueRangeCnt2 int,
  @PastDueRangeCnt3 int,
  @PastDueRangeCnt4 int,
  @PastDueRangeCnt5 int,
  @PastDueRangeCnt6 int,
  @PastDueRangeCnt7 int,
  @PastDueRangeCnt8 int,
  @CurrentDue money,
  @FirstDueDate datetime,
  @WaiveInterestFor char (2),
  @WaiveInterestFrom char (1),
  @InsFundsFeeNotChgOffFor char (2),
  @InsFundsFeeNotChgOffFrom char (1),
  @FinalCOAmount money,
  @PrincipalDefCTD money,
  @PrincipalDefCC1 money,
  @PrincipalDefCC2 money,
  @PrincipalDefCC3 money,
  @PrincipalDefAdjustment money,
  @OverlimitFeeAdjustment money,
  @AmountOfCreditsAsPmt money,
  @AmountOfCreditsAsPmtCTD money,
  @AmountOfCreditsAsPmtCC1 money,
  @AmountOfCreditsAsPmtCC2 money,
  @AmountOfCreditsAsPmtCC3 money,
  @AmountOfCreditsAsPmtMTD money,
  @AmountOfCreditsAsPmtQTD money,
  @AmountOfCreditsAsPmtYTD money,
  @AmountOfCreditsAsPmtLTD money,
  @PendingBalIndicator money,
  @PlanCancelationDate datetime,
  @BeginningBalance_TranTime money,
  @YTDFeesTotalOnly money,
  @YTDIntTotalsOnly money,
  @CTDtotalFeesDebit money,
  @CTDtotalFeesCredit money,
  @CTDtotalIntDebit money,
  @CTDtotalIntCredit money,
  @CTDLateFees money,
  @CTDLateFeesCredit money,
  @CTDLateFeesDebit money,
  @YTDLateFees money,
  @CTDNSFFees money,
  @CTDNSFFeesCredit money,
  @CTDNSFFeesDebit money,
  @YTDNSFFees money,
  @CTDMinimumCharge money,
  @CTDMinimumChargeCredit money,
  @CTDMinimumChargeDebit money,
  @YTDMinimumCharge money,
  @COEligibilityDate datetime,
  @AccountOpenDate datetime,
  @AutoDispInitiateDate datetime,
  @FirstLateFeeWaiveDate datetime,
  @OverlimitBalanceCTD money,
  @AccumulatedOverlimitBalance money,
  @OriginalDueDate datetime,
  @LDStatusUpdateDate datetime,
  @AnticipatedPayOffAmount money,
  @DlqOneCpdLtdCount int,
  @DlqTwoCpdLtdCount int,
  @DlqThreePlusCpdLtdCount int,
  @PriEmbActivationFlag int,
  @DMinThrhldAutoResCount int,
  @TotalTransactionFeesCO money,
  @TotalLateFeesCO money,
  @TotalInsufficientFundsFeesCO money,
  @TotalOverlimitFeesCO money,
  @TotalInsurancePremiumsCO money,
  @TotalCollectionExpensesCO money,
  @TotalOtherFeesCO money,
  @TotalAnnualFeesCO money,
  @TotalInterestCO money,
  @TotalPrincipalCO money,
  @StatementRunningBalance money,
  @StatementRemainingBalance money,
  @RecoveryFeeDate datetime,
  @QualifiedCycleCountRecoveryfee int,
  @AcctInDelinq2Status int,
  @CollateralID varchar (50),
  @RegZ52aEndDate datetime,
  @RegZ52aAmountThreshold money,
  @RegZ52aFeeAmountYTD money,
  @RunningMinimumDue money,
  @RemainingMinimumDue money,
  @CycleDue_DTDAtChargeoff int,
  @BankruptcyFileDate datetime AS
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET QUOTED_IDENTIFIER ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;
SET NOCOUNT OFF;
 UPDATE DBO.BSegmentCreditCard SET   [FixedPaymentAmt] = @FixedPaymentAmt,
  [FixedPaymentPercent] = @FixedPaymentPercent,
  [PaymentLevel] = @PaymentLevel,
  [PaymentType] = @PaymentType,
  [AmountOfPayment120DLate] = @AmountOfPayment120DLate,
  [AmountOfPayment150DLate] = @AmountOfPayment150DLate,
  [AmountOfPayment180DLate] = @AmountOfPayment180DLate,
  [AmountOfPayment210DLate] = @AmountOfPayment210DLate,
  [AmountOfPayment30DLate] = @AmountOfPayment30DLate,
  [AmountOfPayment60DLate] = @AmountOfPayment60DLate,
  [AmountOfPayment90DLate] = @AmountOfPayment90DLate,
  [AmtOfPayXDLate] = @AmtOfPayXDLate,
  [AmountOfTotalDue] = @AmountOfTotalDue,
  [AutoSkipPaymentOpt] = @AutoSkipPaymentOpt,
  [pmtpriority] = @pmtpriority,
  [BalSubjPayment] = @BalSubjPayment,
  [SkipPayOptInEffect] = @SkipPayOptInEffect,
  [TempBalSubjPayment] = @TempBalSubjPayment,
  [TempCurrentDue] = @TempCurrentDue,
  [WaiveInterest] = @WaiveInterest,
  [BSWFeeIntStartDate] = @BSWFeeIntStartDate,
  [DtOfLastDelinqCTD] = @DtOfLastDelinqCTD,
  [DateOfOriginalPaymentDueDTD] = @DateOfOriginalPaymentDueDTD,
  [DateOfTotalDue] = @DateOfTotalDue,
  [NumberTimesReaged] = @NumberTimesReaged,
  [LastSkipPymtDate] = @LastSkipPymtDate,
  [LastSkipPymtAmt] = @LastSkipPymtAmt,
  [NoOfSkipPymts] = @NoOfSkipPymts,
  [NoPayDaysDelinquent] = @NoPayDaysDelinquent,
  [VirtualHdOfDelqChain] = @VirtualHdOfDelqChain,
  [CollReasonCode] = @CollReasonCode,
  [NextPaymentDueDate] = @NextPaymentDueDate,
  [NumberOfPaymentPastDue] = @NumberOfPaymentPastDue,
  [NumberOfPayment30DLate] = @NumberOfPayment30DLate,
  [NumberOfPayment60DLate] = @NumberOfPayment60DLate,
  [NumberOfPayment90DLate] = @NumberOfPayment90DLate,
  [NumberOfPayment120DLate] = @NumberOfPayment120DLate,
  [NumberOfPayment150DLate] = @NumberOfPayment150DLate,
  [NumberOfPayment180DLate] = @NumberOfPayment180DLate,
  [NumberOfPayment210DLate] = @NumberOfPayment210DLate,
  [daysdelinquent] = @daysdelinquent,
  [HighDelqBalanceLTD] = @HighDelqBalanceLTD,
  [HighCyclePastDueLTD] = @HighCyclePastDueLTD,
  [InterestDisclCycle] = @InterestDisclCycle,
  [InterestDisclMethod] = @InterestDisclMethod,
  [AmtGenIntCredits] = @AmtGenIntCredits,
  [AmtGenInterestCreditsLTD] = @AmtGenInterestCreditsLTD,
  [AmtGenInterestCreditsYTD] = @AmtGenInterestCreditsYTD,
  [AmtInterestCreditsCTD] = @AmtInterestCreditsCTD,
  [AmtInterestCreditsLTD] = @AmtInterestCreditsLTD,
  [AmtInterestCreditsYTD] = @AmtInterestCreditsYTD,
  [AutoFinalChargeOffTiming] = @AutoFinalChargeOffTiming,
  [ChrgdOffAcctAccrMeth] = @ChrgdOffAcctAccrMeth,
  [ChargeOffAccountStatus] = @ChargeOffAccountStatus,
  [ChargeOffDate] = @ChargeOffDate,
  [DirectDebitPayStatus] = @DirectDebitPayStatus,
  [FinalChargeOffDate] = @FinalChargeOffDate,
  [NbrOfDaysUntilChargeOff] = @NbrOfDaysUntilChargeOff,
  [SystemChargeOffStatus] = @SystemChargeOffStatus,
  [UserChargeOffStatus] = @UserChargeOffStatus,
  [InsFundsFeeNotChgOff] = @InsFundsFeeNotChgOff,
  [ChargeOffStatement] = @ChargeOffStatement,
  [collectionfeesbnpco] = @collectionfeesbnpco,
  [currentbalanceco] = @currentbalanceco,
  [DelinHistoryCtrCTD] = @DelinHistoryCtrCTD,
  [AmtOfInterestCTD] = @AmtOfInterestCTD,
  [AmtOfInterestLTD] = @AmtOfInterestLTD,
  [AmtOfInterestMTD] = @AmtOfInterestMTD,
  [AmtOfInterestYTD] = @AmtOfInterestYTD,
  [IntAccrCycle] = @IntAccrCycle,
  [AfterCycleRevolvBSFC] = @AfterCycleRevolvBSFC,
  [AggregateDays] = @AggregateDays,
  [IntBilledNotPaid] = @IntBilledNotPaid,
  [interestbnpco] = @interestbnpco,
  [DeferredAccrued] = @DeferredAccrued,
  [DeferredAggregate] = @DeferredAggregate,
  [DeferredAggDays] = @DeferredAggDays,
  [NewTransactionsAccrued] = @NewTransactionsAccrued,
  [NewTransactionsAgg] = @NewTransactionsAgg,
  [NewTransactionsBSFC] = @NewTransactionsBSFC,
  [InterestPerDiem] = @InterestPerDiem,
  [RevolvingAccrued] = @RevolvingAccrued,
  [RevolvingAgg] = @RevolvingAgg,
  [RevolvingBSFC] = @RevolvingBSFC,
  [TotalAccruedInterest] = @TotalAccruedInterest,
  [TotalBSFC] = @TotalBSFC,
  [latefeesbnpco] = @latefeesbnpco,
  [membershipfeesbnpco] = @membershipfeesbnpco,
  [nsffeesbnpco] = @nsffeesbnpco,
  [overlimitfeesbnpco] = @overlimitfeesbnpco,
  [PayHistoryCtrCTD] = @PayHistoryCtrCTD,
  [PrePaidAmount] = @PrePaidAmount,
  [principalco] = @principalco,
  [ratechgeffdate] = @ratechgeffdate,
  [recoveryfeesbnpco] = @recoveryfeesbnpco,
  [totalamountco] = @totalamountco,
  [servicefeesbnpco] = @servicefeesbnpco,
  [AutoInitialChargeOffReason] = @AutoInitialChargeOffReason,
  [AutoInitialChargeOffStartDate] = @AutoInitialChargeOffStartDate,
  [ManualInitialChargeOffReason] = @ManualInitialChargeOffReason,
  [ManualInitialChargeOffStartDate] = @ManualInitialChargeOffStartDate,
  [ChargeOffProcessIndicator] = @ChargeOffProcessIndicator,
  [ChargeOffDateParam] = @ChargeOffDateParam,
  [FinalChargeOffDateParam] = @FinalChargeOffDateParam,
  [AutoInitialChargeOffCriteria] = @AutoInitialChargeOffCriteria,
  [AutoInitialChargeOffCriteria_t] = @AutoInitialChargeOffCriteria_t,
  [AutoInitialChargeOffCriteria_m] = @AutoInitialChargeOffCriteria_m,
  [AutoInitialChargeOffFreq] = @AutoInitialChargeOffFreq,
  [AutoFinalChargeOffCriteria] = @AutoFinalChargeOffCriteria,
  [AutoFinalChargeOffCriteria_t] = @AutoFinalChargeOffCriteria_t,
  [AutoFinalChargeOffCriteria_m] = @AutoFinalChargeOffCriteria_m,
  [AutoFinalChargeOffPeriod] = @AutoFinalChargeOffPeriod,
  [AutoFinalChargeOffFreq] = @AutoFinalChargeOffFreq,
  [ReageDate1] = @ReageDate1,
  [ReageDate2] = @ReageDate2,
  [ReageDate3] = @ReageDate3,
  [ReageDate4] = @ReageDate4,
  [ReageDate5] = @ReageDate5,
  [ReageDate6] = @ReageDate6,
  [ReageTypeIndic1] = @ReageTypeIndic1,
  [ReageTypeIndic2] = @ReageTypeIndic2,
  [ReageTypeIndic3] = @ReageTypeIndic3,
  [ReageTypeIndic4] = @ReageTypeIndic4,
  [ReageTypeIndic5] = @ReageTypeIndic5,
  [ReageTypeIndic6] = @ReageTypeIndic6,
  [AmountOfPaymentsDTD] = @AmountOfPaymentsDTD,
  [PastDueRangeAmt1] = @PastDueRangeAmt1,
  [PastDueRangeAmt2] = @PastDueRangeAmt2,
  [PastDueRangeAmt3] = @PastDueRangeAmt3,
  [PastDueRangeAmt4] = @PastDueRangeAmt4,
  [PastDueRangeAmt5] = @PastDueRangeAmt5,
  [PastDueRangeAmt6] = @PastDueRangeAmt6,
  [PastDueRangeAmt7] = @PastDueRangeAmt7,
  [PastDueRangeAmt8] = @PastDueRangeAmt8,
  [PastDueRangeCnt1] = @PastDueRangeCnt1,
  [PastDueRangeCnt2] = @PastDueRangeCnt2,
  [PastDueRangeCnt3] = @PastDueRangeCnt3,
  [PastDueRangeCnt4] = @PastDueRangeCnt4,
  [PastDueRangeCnt5] = @PastDueRangeCnt5,
  [PastDueRangeCnt6] = @PastDueRangeCnt6,
  [PastDueRangeCnt7] = @PastDueRangeCnt7,
  [PastDueRangeCnt8] = @PastDueRangeCnt8,
  [CurrentDue] = @CurrentDue,
  [FirstDueDate] = @FirstDueDate,
  [WaiveInterestFor] = @WaiveInterestFor,
  [WaiveInterestFrom] = @WaiveInterestFrom,
  [InsFundsFeeNotChgOffFor] = @InsFundsFeeNotChgOffFor,
  [InsFundsFeeNotChgOffFrom] = @InsFundsFeeNotChgOffFrom,
  [FinalCOAmount] = @FinalCOAmount,
  [PrincipalDefCTD] = @PrincipalDefCTD,
  [PrincipalDefCC1] = @PrincipalDefCC1,
  [PrincipalDefCC2] = @PrincipalDefCC2,
  [PrincipalDefCC3] = @PrincipalDefCC3,
  [PrincipalDefAdjustment] = @PrincipalDefAdjustment,
  [OverlimitFeeAdjustment] = @OverlimitFeeAdjustment,
  [AmountOfCreditsAsPmt] = @AmountOfCreditsAsPmt,
  [AmountOfCreditsAsPmtCTD] = @AmountOfCreditsAsPmtCTD,
  [AmountOfCreditsAsPmtCC1] = @AmountOfCreditsAsPmtCC1,
  [AmountOfCreditsAsPmtCC2] = @AmountOfCreditsAsPmtCC2,
  [AmountOfCreditsAsPmtCC3] = @AmountOfCreditsAsPmtCC3,
  [AmountOfCreditsAsPmtMTD] = @AmountOfCreditsAsPmtMTD,
  [AmountOfCreditsAsPmtQTD] = @AmountOfCreditsAsPmtQTD,
  [AmountOfCreditsAsPmtYTD] = @AmountOfCreditsAsPmtYTD,
  [AmountOfCreditsAsPmtLTD] = @AmountOfCreditsAsPmtLTD,
  [PendingBalIndicator] = @PendingBalIndicator,
  [PlanCancelationDate] = @PlanCancelationDate,
  [BeginningBalance_TranTime] = @BeginningBalance_TranTime,
  [YTDFeesTotalOnly] = @YTDFeesTotalOnly,
  [YTDIntTotalsOnly] = @YTDIntTotalsOnly,
  [CTDtotalFeesDebit] = @CTDtotalFeesDebit,
  [CTDtotalFeesCredit] = @CTDtotalFeesCredit,
  [CTDtotalIntDebit] = @CTDtotalIntDebit,
  [CTDtotalIntCredit] = @CTDtotalIntCredit,
  [CTDLateFees] = @CTDLateFees,
  [CTDLateFeesCredit] = @CTDLateFeesCredit,
  [CTDLateFeesDebit] = @CTDLateFeesDebit,
  [YTDLateFees] = @YTDLateFees,
  [CTDNSFFees] = @CTDNSFFees,
  [CTDNSFFeesCredit] = @CTDNSFFeesCredit,
  [CTDNSFFeesDebit] = @CTDNSFFeesDebit,
  [YTDNSFFees] = @YTDNSFFees,
  [CTDMinimumCharge] = @CTDMinimumCharge,
  [CTDMinimumChargeCredit] = @CTDMinimumChargeCredit,
  [CTDMinimumChargeDebit] = @CTDMinimumChargeDebit,
  [YTDMinimumCharge] = @YTDMinimumCharge,
  [COEligibilityDate] = @COEligibilityDate,
  [AccountOpenDate] = @AccountOpenDate,
  [AutoDispInitiateDate] = @AutoDispInitiateDate,
  [FirstLateFeeWaiveDate] = @FirstLateFeeWaiveDate,
  [OverlimitBalanceCTD] = @OverlimitBalanceCTD,
  [AccumulatedOverlimitBalance] = @AccumulatedOverlimitBalance,
  [OriginalDueDate] = @OriginalDueDate,
  [LDStatusUpdateDate] = @LDStatusUpdateDate,
  [AnticipatedPayOffAmount] = @AnticipatedPayOffAmount,
  [DlqOneCpdLtdCount] = @DlqOneCpdLtdCount,
  [DlqTwoCpdLtdCount] = @DlqTwoCpdLtdCount,
  [DlqThreePlusCpdLtdCount] = @DlqThreePlusCpdLtdCount,
  [PriEmbActivationFlag] = @PriEmbActivationFlag,
  [DMinThrhldAutoResCount] = @DMinThrhldAutoResCount,
  [TotalTransactionFeesCO] = @TotalTransactionFeesCO,
  [TotalLateFeesCO] = @TotalLateFeesCO,
  [TotalInsufficientFundsFeesCO] = @TotalInsufficientFundsFeesCO,
  [TotalOverlimitFeesCO] = @TotalOverlimitFeesCO,
  [TotalInsurancePremiumsCO] = @TotalInsurancePremiumsCO,
  [TotalCollectionExpensesCO] = @TotalCollectionExpensesCO,
  [TotalOtherFeesCO] = @TotalOtherFeesCO,
  [TotalAnnualFeesCO] = @TotalAnnualFeesCO,
  [TotalInterestCO] = @TotalInterestCO,
  [TotalPrincipalCO] = @TotalPrincipalCO,
  [StatementRunningBalance] = @StatementRunningBalance,
  [StatementRemainingBalance] = @StatementRemainingBalance,
  [RecoveryFeeDate] = @RecoveryFeeDate,
  [QualifiedCycleCountRecoveryfee] = @QualifiedCycleCountRecoveryfee,
  [AcctInDelinq2Status] = @AcctInDelinq2Status,
  [CollateralID] = @CollateralID,
  [RegZ52aEndDate] = @RegZ52aEndDate,
  [RegZ52aAmountThreshold] = @RegZ52aAmountThreshold,
  [RegZ52aFeeAmountYTD] = @RegZ52aFeeAmountYTD,
  [RunningMinimumDue] = @RunningMinimumDue,
  [RemainingMinimumDue] = @RemainingMinimumDue,
  [CycleDue_DTDAtChargeoff] = @CycleDue_DTDAtChargeoff,
  [BankruptcyFileDate] = @BankruptcyFileDate 
WHERE 
   [acctId] = @acctId 
GO
grant execute on sp_BSegmentCreditCard_upd to public 
GO

if exists (select * from sysobjects where 
 id = object_id('sp_BSegmentCreditCard_ins') and sysstat & 0xf = 4)
drop procedure sp_BSegmentCreditCard_ins
GO
CREATE PROCEDURE sp_BSegmentCreditCard_ins (
  @acctId int,
  @FixedPaymentAmt money,
  @FixedPaymentPercent money,
  @PaymentLevel char (5),
  @PaymentType char (5),
  @AmountOfPayment120DLate money,
  @AmountOfPayment150DLate money,
  @AmountOfPayment180DLate money,
  @AmountOfPayment210DLate money,
  @AmountOfPayment30DLate money,
  @AmountOfPayment60DLate money,
  @AmountOfPayment90DLate money,
  @AmtOfPayXDLate money,
  @AmountOfTotalDue money,
  @AutoSkipPaymentOpt char (5),
  @pmtpriority char (2),
  @BalSubjPayment money,
  @SkipPayOptInEffect char (5),
  @TempBalSubjPayment money,
  @TempCurrentDue money,
  @WaiveInterest char (5),
  @BSWFeeIntStartDate datetime,
  @DtOfLastDelinqCTD datetime,
  @DateOfOriginalPaymentDueDTD datetime,
  @DateOfTotalDue datetime,
  @NumberTimesReaged int,
  @LastSkipPymtDate datetime,
  @LastSkipPymtAmt money,
  @NoOfSkipPymts int,
  @NoPayDaysDelinquent int,
  @VirtualHdOfDelqChain money,
  @CollReasonCode char (5),
  @NextPaymentDueDate datetime,
  @NumberOfPaymentPastDue int,
  @NumberOfPayment30DLate int,
  @NumberOfPayment60DLate int,
  @NumberOfPayment90DLate int,
  @NumberOfPayment120DLate int,
  @NumberOfPayment150DLate int,
  @NumberOfPayment180DLate int,
  @NumberOfPayment210DLate int,
  @daysdelinquent int,
  @HighDelqBalanceLTD money,
  @HighCyclePastDueLTD money,
  @InterestDisclCycle char (5),
  @InterestDisclMethod char (5),
  @AmtGenIntCredits money,
  @AmtGenInterestCreditsLTD money,
  @AmtGenInterestCreditsYTD money,
  @AmtInterestCreditsCTD money,
  @AmtInterestCreditsLTD money,
  @AmtInterestCreditsYTD money,
  @AutoFinalChargeOffTiming char (5),
  @ChrgdOffAcctAccrMeth char (5),
  @ChargeOffAccountStatus int,
  @ChargeOffDate datetime,
  @DirectDebitPayStatus char (5),
  @FinalChargeOffDate datetime,
  @NbrOfDaysUntilChargeOff int,
  @SystemChargeOffStatus char (5),
  @UserChargeOffStatus char (5),
  @InsFundsFeeNotChgOff char (5),
  @ChargeOffStatement char (5),
  @collectionfeesbnpco money,
  @currentbalanceco money,
  @DelinHistoryCtrCTD int,
  @AmtOfInterestCTD money,
  @AmtOfInterestLTD money,
  @AmtOfInterestMTD money,
  @AmtOfInterestYTD money,
  @IntAccrCycle money,
  @AfterCycleRevolvBSFC money,
  @AggregateDays int,
  @IntBilledNotPaid money,
  @interestbnpco money,
  @DeferredAccrued money,
  @DeferredAggregate money,
  @DeferredAggDays int,
  @NewTransactionsAccrued decimal(19,10),
  @NewTransactionsAgg money,
  @NewTransactionsBSFC money,
  @InterestPerDiem money,
  @RevolvingAccrued decimal(19,10),
  @RevolvingAgg money,
  @RevolvingBSFC money,
  @TotalAccruedInterest money,
  @TotalBSFC money,
  @latefeesbnpco money,
  @membershipfeesbnpco money,
  @nsffeesbnpco money,
  @overlimitfeesbnpco money,
  @PayHistoryCtrCTD int,
  @PrePaidAmount money,
  @principalco money,
  @ratechgeffdate datetime,
  @recoveryfeesbnpco money,
  @totalamountco money,
  @servicefeesbnpco money,
  @AutoInitialChargeOffReason char (5),
  @AutoInitialChargeOffStartDate datetime,
  @ManualInitialChargeOffReason char (5),
  @ManualInitialChargeOffStartDate datetime,
  @ChargeOffProcessIndicator char (5),
  @ChargeOffDateParam datetime,
  @FinalChargeOffDateParam datetime,
  @AutoInitialChargeOffCriteria char (5),
  @AutoInitialChargeOffCriteria_t char (5),
  @AutoInitialChargeOffCriteria_m char (5),
  @AutoInitialChargeOffFreq char (5),
  @AutoFinalChargeOffCriteria char (5),
  @AutoFinalChargeOffCriteria_t char (5),
  @AutoFinalChargeOffCriteria_m char (5),
  @AutoFinalChargeOffPeriod int,
  @AutoFinalChargeOffFreq char (5),
  @ReageDate1 datetime,
  @ReageDate2 datetime,
  @ReageDate3 datetime,
  @ReageDate4 datetime,
  @ReageDate5 datetime,
  @ReageDate6 datetime,
  @ReageTypeIndic1 int,
  @ReageTypeIndic2 int,
  @ReageTypeIndic3 int,
  @ReageTypeIndic4 int,
  @ReageTypeIndic5 int,
  @ReageTypeIndic6 int,
  @AmountOfPaymentsDTD money,
  @PastDueRangeAmt1 money,
  @PastDueRangeAmt2 money,
  @PastDueRangeAmt3 money,
  @PastDueRangeAmt4 money,
  @PastDueRangeAmt5 money,
  @PastDueRangeAmt6 money,
  @PastDueRangeAmt7 money,
  @PastDueRangeAmt8 money,
  @PastDueRangeCnt1 int,
  @PastDueRangeCnt2 int,
  @PastDueRangeCnt3 int,
  @PastDueRangeCnt4 int,
  @PastDueRangeCnt5 int,
  @PastDueRangeCnt6 int,
  @PastDueRangeCnt7 int,
  @PastDueRangeCnt8 int,
  @CurrentDue money,
  @FirstDueDate datetime,
  @WaiveInterestFor char (2),
  @WaiveInterestFrom char (1),
  @InsFundsFeeNotChgOffFor char (2),
  @InsFundsFeeNotChgOffFrom char (1),
  @FinalCOAmount money,
  @PrincipalDefCTD money,
  @PrincipalDefCC1 money,
  @PrincipalDefCC2 money,
  @PrincipalDefCC3 money,
  @PrincipalDefAdjustment money,
  @OverlimitFeeAdjustment money,
  @AmountOfCreditsAsPmt money,
  @AmountOfCreditsAsPmtCTD money,
  @AmountOfCreditsAsPmtCC1 money,
  @AmountOfCreditsAsPmtCC2 money,
  @AmountOfCreditsAsPmtCC3 money,
  @AmountOfCreditsAsPmtMTD money,
  @AmountOfCreditsAsPmtQTD money,
  @AmountOfCreditsAsPmtYTD money,
  @AmountOfCreditsAsPmtLTD money,
  @PendingBalIndicator money,
  @PlanCancelationDate datetime,
  @BeginningBalance_TranTime money,
  @YTDFeesTotalOnly money,
  @YTDIntTotalsOnly money,
  @CTDtotalFeesDebit money,
  @CTDtotalFeesCredit money,
  @CTDtotalIntDebit money,
  @CTDtotalIntCredit money,
  @CTDLateFees money,
  @CTDLateFeesCredit money,
  @CTDLateFeesDebit money,
  @YTDLateFees money,
  @CTDNSFFees money,
  @CTDNSFFeesCredit money,
  @CTDNSFFeesDebit money,
  @YTDNSFFees money,
  @CTDMinimumCharge money,
  @CTDMinimumChargeCredit money,
  @CTDMinimumChargeDebit money,
  @YTDMinimumCharge money,
  @COEligibilityDate datetime,
  @AccountOpenDate datetime,
  @AutoDispInitiateDate datetime,
  @FirstLateFeeWaiveDate datetime,
  @OverlimitBalanceCTD money,
  @AccumulatedOverlimitBalance money,
  @OriginalDueDate datetime,
  @LDStatusUpdateDate datetime,
  @AnticipatedPayOffAmount money,
  @DlqOneCpdLtdCount int,
  @DlqTwoCpdLtdCount int,
  @DlqThreePlusCpdLtdCount int,
  @PriEmbActivationFlag int,
  @DMinThrhldAutoResCount int,
  @TotalTransactionFeesCO money,
  @TotalLateFeesCO money,
  @TotalInsufficientFundsFeesCO money,
  @TotalOverlimitFeesCO money,
  @TotalInsurancePremiumsCO money,
  @TotalCollectionExpensesCO money,
  @TotalOtherFeesCO money,
  @TotalAnnualFeesCO money,
  @TotalInterestCO money,
  @TotalPrincipalCO money,
  @StatementRunningBalance money,
  @StatementRemainingBalance money,
  @RecoveryFeeDate datetime,
  @QualifiedCycleCountRecoveryfee int,
  @AcctInDelinq2Status int,
  @CollateralID varchar (50),
  @RegZ52aEndDate datetime,
  @RegZ52aAmountThreshold money,
  @RegZ52aFeeAmountYTD money,
  @RunningMinimumDue money,
  @RemainingMinimumDue money,
  @CycleDue_DTDAtChargeoff int,
  @BankruptcyFileDate datetime)
AS
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET QUOTED_IDENTIFIER ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;
 INSERT INTO DBO.BSegmentCreditCard 
(  [acctId],
 [FixedPaymentAmt],
 [FixedPaymentPercent],
 [PaymentLevel],
 [PaymentType],
 [AmountOfPayment120DLate],
 [AmountOfPayment150DLate],
 [AmountOfPayment180DLate],
 [AmountOfPayment210DLate],
 [AmountOfPayment30DLate],
 [AmountOfPayment60DLate],
 [AmountOfPayment90DLate],
 [AmtOfPayXDLate],
 [AmountOfTotalDue],
 [AutoSkipPaymentOpt],
 [pmtpriority],
 [BalSubjPayment],
 [SkipPayOptInEffect],
 [TempBalSubjPayment],
 [TempCurrentDue],
 [WaiveInterest],
 [BSWFeeIntStartDate],
 [DtOfLastDelinqCTD],
 [DateOfOriginalPaymentDueDTD],
 [DateOfTotalDue],
 [NumberTimesReaged],
 [LastSkipPymtDate],
 [LastSkipPymtAmt],
 [NoOfSkipPymts],
 [NoPayDaysDelinquent],
 [VirtualHdOfDelqChain],
 [CollReasonCode],
 [NextPaymentDueDate],
 [NumberOfPaymentPastDue],
 [NumberOfPayment30DLate],
 [NumberOfPayment60DLate],
 [NumberOfPayment90DLate],
 [NumberOfPayment120DLate],
 [NumberOfPayment150DLate],
 [NumberOfPayment180DLate],
 [NumberOfPayment210DLate],
 [daysdelinquent],
 [HighDelqBalanceLTD],
 [HighCyclePastDueLTD],
 [InterestDisclCycle],
 [InterestDisclMethod],
 [AmtGenIntCredits],
 [AmtGenInterestCreditsLTD],
 [AmtGenInterestCreditsYTD],
 [AmtInterestCreditsCTD],
 [AmtInterestCreditsLTD],
 [AmtInterestCreditsYTD],
 [AutoFinalChargeOffTiming],
 [ChrgdOffAcctAccrMeth],
 [ChargeOffAccountStatus],
 [ChargeOffDate],
 [DirectDebitPayStatus],
 [FinalChargeOffDate],
 [NbrOfDaysUntilChargeOff],
 [SystemChargeOffStatus],
 [UserChargeOffStatus],
 [InsFundsFeeNotChgOff],
 [ChargeOffStatement],
 [collectionfeesbnpco],
 [currentbalanceco],
 [DelinHistoryCtrCTD],
 [AmtOfInterestCTD],
 [AmtOfInterestLTD],
 [AmtOfInterestMTD],
 [AmtOfInterestYTD],
 [IntAccrCycle],
 [AfterCycleRevolvBSFC],
 [AggregateDays],
 [IntBilledNotPaid],
 [interestbnpco],
 [DeferredAccrued],
 [DeferredAggregate],
 [DeferredAggDays],
 [NewTransactionsAccrued],
 [NewTransactionsAgg],
 [NewTransactionsBSFC],
 [InterestPerDiem],
 [RevolvingAccrued],
 [RevolvingAgg],
 [RevolvingBSFC],
 [TotalAccruedInterest],
 [TotalBSFC],
 [latefeesbnpco],
 [membershipfeesbnpco],
 [nsffeesbnpco],
 [overlimitfeesbnpco],
 [PayHistoryCtrCTD],
 [PrePaidAmount],
 [principalco],
 [ratechgeffdate],
 [recoveryfeesbnpco],
 [totalamountco],
 [servicefeesbnpco],
 [AutoInitialChargeOffReason],
 [AutoInitialChargeOffStartDate],
 [ManualInitialChargeOffReason],
 [ManualInitialChargeOffStartDate],
 [ChargeOffProcessIndicator],
 [ChargeOffDateParam],
 [FinalChargeOffDateParam],
 [AutoInitialChargeOffCriteria],
 [AutoInitialChargeOffCriteria_t],
 [AutoInitialChargeOffCriteria_m],
 [AutoInitialChargeOffFreq],
 [AutoFinalChargeOffCriteria],
 [AutoFinalChargeOffCriteria_t],
 [AutoFinalChargeOffCriteria_m],
 [AutoFinalChargeOffPeriod],
 [AutoFinalChargeOffFreq],
 [ReageDate1],
 [ReageDate2],
 [ReageDate3],
 [ReageDate4],
 [ReageDate5],
 [ReageDate6],
 [ReageTypeIndic1],
 [ReageTypeIndic2],
 [ReageTypeIndic3],
 [ReageTypeIndic4],
 [ReageTypeIndic5],
 [ReageTypeIndic6],
 [AmountOfPaymentsDTD],
 [PastDueRangeAmt1],
 [PastDueRangeAmt2],
 [PastDueRangeAmt3],
 [PastDueRangeAmt4],
 [PastDueRangeAmt5],
 [PastDueRangeAmt6],
 [PastDueRangeAmt7],
 [PastDueRangeAmt8],
 [PastDueRangeCnt1],
 [PastDueRangeCnt2],
 [PastDueRangeCnt3],
 [PastDueRangeCnt4],
 [PastDueRangeCnt5],
 [PastDueRangeCnt6],
 [PastDueRangeCnt7],
 [PastDueRangeCnt8],
 [CurrentDue],
 [FirstDueDate],
 [WaiveInterestFor],
 [WaiveInterestFrom],
 [InsFundsFeeNotChgOffFor],
 [InsFundsFeeNotChgOffFrom],
 [FinalCOAmount],
 [PrincipalDefCTD],
 [PrincipalDefCC1],
 [PrincipalDefCC2],
 [PrincipalDefCC3],
 [PrincipalDefAdjustment],
 [OverlimitFeeAdjustment],
 [AmountOfCreditsAsPmt],
 [AmountOfCreditsAsPmtCTD],
 [AmountOfCreditsAsPmtCC1],
 [AmountOfCreditsAsPmtCC2],
 [AmountOfCreditsAsPmtCC3],
 [AmountOfCreditsAsPmtMTD],
 [AmountOfCreditsAsPmtQTD],
 [AmountOfCreditsAsPmtYTD],
 [AmountOfCreditsAsPmtLTD],
 [PendingBalIndicator],
 [PlanCancelationDate],
 [BeginningBalance_TranTime],
 [YTDFeesTotalOnly],
 [YTDIntTotalsOnly],
 [CTDtotalFeesDebit],
 [CTDtotalFeesCredit],
 [CTDtotalIntDebit],
 [CTDtotalIntCredit],
 [CTDLateFees],
 [CTDLateFeesCredit],
 [CTDLateFeesDebit],
 [YTDLateFees],
 [CTDNSFFees],
 [CTDNSFFeesCredit],
 [CTDNSFFeesDebit],
 [YTDNSFFees],
 [CTDMinimumCharge],
 [CTDMinimumChargeCredit],
 [CTDMinimumChargeDebit],
 [YTDMinimumCharge],
 [COEligibilityDate],
 [AccountOpenDate],
 [AutoDispInitiateDate],
 [FirstLateFeeWaiveDate],
 [OverlimitBalanceCTD],
 [AccumulatedOverlimitBalance],
 [OriginalDueDate],
 [LDStatusUpdateDate],
 [AnticipatedPayOffAmount],
 [DlqOneCpdLtdCount],
 [DlqTwoCpdLtdCount],
 [DlqThreePlusCpdLtdCount],
 [PriEmbActivationFlag],
 [DMinThrhldAutoResCount],
 [TotalTransactionFeesCO],
 [TotalLateFeesCO],
 [TotalInsufficientFundsFeesCO],
 [TotalOverlimitFeesCO],
 [TotalInsurancePremiumsCO],
 [TotalCollectionExpensesCO],
 [TotalOtherFeesCO],
 [TotalAnnualFeesCO],
 [TotalInterestCO],
 [TotalPrincipalCO],
 [StatementRunningBalance],
 [StatementRemainingBalance],
 [RecoveryFeeDate],
 [QualifiedCycleCountRecoveryfee],
 [AcctInDelinq2Status],
 [CollateralID],
 [RegZ52aEndDate],
 [RegZ52aAmountThreshold],
 [RegZ52aFeeAmountYTD],
 [RunningMinimumDue],
 [RemainingMinimumDue],
 [CycleDue_DTDAtChargeoff],
 [BankruptcyFileDate])
VALUES (  @acctId,
 @FixedPaymentAmt,
 @FixedPaymentPercent,
 @PaymentLevel,
 @PaymentType,
 @AmountOfPayment120DLate,
 @AmountOfPayment150DLate,
 @AmountOfPayment180DLate,
 @AmountOfPayment210DLate,
 @AmountOfPayment30DLate,
 @AmountOfPayment60DLate,
 @AmountOfPayment90DLate,
 @AmtOfPayXDLate,
 @AmountOfTotalDue,
 @AutoSkipPaymentOpt,
 @pmtpriority,
 @BalSubjPayment,
 @SkipPayOptInEffect,
 @TempBalSubjPayment,
 @TempCurrentDue,
 @WaiveInterest,
 @BSWFeeIntStartDate,
 @DtOfLastDelinqCTD,
 @DateOfOriginalPaymentDueDTD,
 @DateOfTotalDue,
 @NumberTimesReaged,
 @LastSkipPymtDate,
 @LastSkipPymtAmt,
 @NoOfSkipPymts,
 @NoPayDaysDelinquent,
 @VirtualHdOfDelqChain,
 @CollReasonCode,
 @NextPaymentDueDate,
 @NumberOfPaymentPastDue,
 @NumberOfPayment30DLate,
 @NumberOfPayment60DLate,
 @NumberOfPayment90DLate,
 @NumberOfPayment120DLate,
 @NumberOfPayment150DLate,
 @NumberOfPayment180DLate,
 @NumberOfPayment210DLate,
 @daysdelinquent,
 @HighDelqBalanceLTD,
 @HighCyclePastDueLTD,
 @InterestDisclCycle,
 @InterestDisclMethod,
 @AmtGenIntCredits,
 @AmtGenInterestCreditsLTD,
 @AmtGenInterestCreditsYTD,
 @AmtInterestCreditsCTD,
 @AmtInterestCreditsLTD,
 @AmtInterestCreditsYTD,
 @AutoFinalChargeOffTiming,
 @ChrgdOffAcctAccrMeth,
 @ChargeOffAccountStatus,
 @ChargeOffDate,
 @DirectDebitPayStatus,
 @FinalChargeOffDate,
 @NbrOfDaysUntilChargeOff,
 @SystemChargeOffStatus,
 @UserChargeOffStatus,
 @InsFundsFeeNotChgOff,
 @ChargeOffStatement,
 @collectionfeesbnpco,
 @currentbalanceco,
 @DelinHistoryCtrCTD,
 @AmtOfInterestCTD,
 @AmtOfInterestLTD,
 @AmtOfInterestMTD,
 @AmtOfInterestYTD,
 @IntAccrCycle,
 @AfterCycleRevolvBSFC,
 @AggregateDays,
 @IntBilledNotPaid,
 @interestbnpco,
 @DeferredAccrued,
 @DeferredAggregate,
 @DeferredAggDays,
 @NewTransactionsAccrued,
 @NewTransactionsAgg,
 @NewTransactionsBSFC,
 @InterestPerDiem,
 @RevolvingAccrued,
 @RevolvingAgg,
 @RevolvingBSFC,
 @TotalAccruedInterest,
 @TotalBSFC,
 @latefeesbnpco,
 @membershipfeesbnpco,
 @nsffeesbnpco,
 @overlimitfeesbnpco,
 @PayHistoryCtrCTD,
 @PrePaidAmount,
 @principalco,
 @ratechgeffdate,
 @recoveryfeesbnpco,
 @totalamountco,
 @servicefeesbnpco,
 @AutoInitialChargeOffReason,
 @AutoInitialChargeOffStartDate,
 @ManualInitialChargeOffReason,
 @ManualInitialChargeOffStartDate,
 @ChargeOffProcessIndicator,
 @ChargeOffDateParam,
 @FinalChargeOffDateParam,
 @AutoInitialChargeOffCriteria,
 @AutoInitialChargeOffCriteria_t,
 @AutoInitialChargeOffCriteria_m,
 @AutoInitialChargeOffFreq,
 @AutoFinalChargeOffCriteria,
 @AutoFinalChargeOffCriteria_t,
 @AutoFinalChargeOffCriteria_m,
 @AutoFinalChargeOffPeriod,
 @AutoFinalChargeOffFreq,
 @ReageDate1,
 @ReageDate2,
 @ReageDate3,
 @ReageDate4,
 @ReageDate5,
 @ReageDate6,
 @ReageTypeIndic1,
 @ReageTypeIndic2,
 @ReageTypeIndic3,
 @ReageTypeIndic4,
 @ReageTypeIndic5,
 @ReageTypeIndic6,
 @AmountOfPaymentsDTD,
 @PastDueRangeAmt1,
 @PastDueRangeAmt2,
 @PastDueRangeAmt3,
 @PastDueRangeAmt4,
 @PastDueRangeAmt5,
 @PastDueRangeAmt6,
 @PastDueRangeAmt7,
 @PastDueRangeAmt8,
 @PastDueRangeCnt1,
 @PastDueRangeCnt2,
 @PastDueRangeCnt3,
 @PastDueRangeCnt4,
 @PastDueRangeCnt5,
 @PastDueRangeCnt6,
 @PastDueRangeCnt7,
 @PastDueRangeCnt8,
 @CurrentDue,
 @FirstDueDate,
 @WaiveInterestFor,
 @WaiveInterestFrom,
 @InsFundsFeeNotChgOffFor,
 @InsFundsFeeNotChgOffFrom,
 @FinalCOAmount,
 @PrincipalDefCTD,
 @PrincipalDefCC1,
 @PrincipalDefCC2,
 @PrincipalDefCC3,
 @PrincipalDefAdjustment,
 @OverlimitFeeAdjustment,
 @AmountOfCreditsAsPmt,
 @AmountOfCreditsAsPmtCTD,
 @AmountOfCreditsAsPmtCC1,
 @AmountOfCreditsAsPmtCC2,
 @AmountOfCreditsAsPmtCC3,
 @AmountOfCreditsAsPmtMTD,
 @AmountOfCreditsAsPmtQTD,
 @AmountOfCreditsAsPmtYTD,
 @AmountOfCreditsAsPmtLTD,
 @PendingBalIndicator,
 @PlanCancelationDate,
 @BeginningBalance_TranTime,
 @YTDFeesTotalOnly,
 @YTDIntTotalsOnly,
 @CTDtotalFeesDebit,
 @CTDtotalFeesCredit,
 @CTDtotalIntDebit,
 @CTDtotalIntCredit,
 @CTDLateFees,
 @CTDLateFeesCredit,
 @CTDLateFeesDebit,
 @YTDLateFees,
 @CTDNSFFees,
 @CTDNSFFeesCredit,
 @CTDNSFFeesDebit,
 @YTDNSFFees,
 @CTDMinimumCharge,
 @CTDMinimumChargeCredit,
 @CTDMinimumChargeDebit,
 @YTDMinimumCharge,
 @COEligibilityDate,
 @AccountOpenDate,
 @AutoDispInitiateDate,
 @FirstLateFeeWaiveDate,
 @OverlimitBalanceCTD,
 @AccumulatedOverlimitBalance,
 @OriginalDueDate,
 @LDStatusUpdateDate,
 @AnticipatedPayOffAmount,
 @DlqOneCpdLtdCount,
 @DlqTwoCpdLtdCount,
 @DlqThreePlusCpdLtdCount,
 @PriEmbActivationFlag,
 @DMinThrhldAutoResCount,
 @TotalTransactionFeesCO,
 @TotalLateFeesCO,
 @TotalInsufficientFundsFeesCO,
 @TotalOverlimitFeesCO,
 @TotalInsurancePremiumsCO,
 @TotalCollectionExpensesCO,
 @TotalOtherFeesCO,
 @TotalAnnualFeesCO,
 @TotalInterestCO,
 @TotalPrincipalCO,
 @StatementRunningBalance,
 @StatementRemainingBalance,
 @RecoveryFeeDate,
 @QualifiedCycleCountRecoveryfee,
 @AcctInDelinq2Status,
 @CollateralID,
 @RegZ52aEndDate,
 @RegZ52aAmountThreshold,
 @RegZ52aFeeAmountYTD,
 @RunningMinimumDue,
 @RemainingMinimumDue,
 @CycleDue_DTDAtChargeoff,
 @BankruptcyFileDate)
GO

grant execute on sp_BSegmentCreditCard_ins to public 
GO

if exists (select * from sysobjects where 
 id = object_id('sp_BSegmentCreditCard_insupd') and sysstat & 0xf = 4)
drop procedure sp_BSegmentCreditCard_insupd
GO
CREATE PROCEDURE sp_BSegmentCreditCard_insupd (  @acctId int,
  @FixedPaymentAmt money,
  @FixedPaymentPercent money,
  @PaymentLevel char (5),
  @PaymentType char (5),
  @AmountOfPayment120DLate money,
  @AmountOfPayment150DLate money,
  @AmountOfPayment180DLate money,
  @AmountOfPayment210DLate money,
  @AmountOfPayment30DLate money,
  @AmountOfPayment60DLate money,
  @AmountOfPayment90DLate money,
  @AmtOfPayXDLate money,
  @AmountOfTotalDue money,
  @AutoSkipPaymentOpt char (5),
  @pmtpriority char (2),
  @BalSubjPayment money,
  @SkipPayOptInEffect char (5),
  @TempBalSubjPayment money,
  @TempCurrentDue money,
  @WaiveInterest char (5),
  @BSWFeeIntStartDate datetime,
  @DtOfLastDelinqCTD datetime,
  @DateOfOriginalPaymentDueDTD datetime,
  @DateOfTotalDue datetime,
  @NumberTimesReaged int,
  @LastSkipPymtDate datetime,
  @LastSkipPymtAmt money,
  @NoOfSkipPymts int,
  @NoPayDaysDelinquent int,
  @VirtualHdOfDelqChain money,
  @CollReasonCode char (5),
  @NextPaymentDueDate datetime,
  @NumberOfPaymentPastDue int,
  @NumberOfPayment30DLate int,
  @NumberOfPayment60DLate int,
  @NumberOfPayment90DLate int,
  @NumberOfPayment120DLate int,
  @NumberOfPayment150DLate int,
  @NumberOfPayment180DLate int,
  @NumberOfPayment210DLate int,
  @daysdelinquent int,
  @HighDelqBalanceLTD money,
  @HighCyclePastDueLTD money,
  @InterestDisclCycle char (5),
  @InterestDisclMethod char (5),
  @AmtGenIntCredits money,
  @AmtGenInterestCreditsLTD money,
  @AmtGenInterestCreditsYTD money,
  @AmtInterestCreditsCTD money,
  @AmtInterestCreditsLTD money,
  @AmtInterestCreditsYTD money,
  @AutoFinalChargeOffTiming char (5),
  @ChrgdOffAcctAccrMeth char (5),
  @ChargeOffAccountStatus int,
  @ChargeOffDate datetime,
  @DirectDebitPayStatus char (5),
  @FinalChargeOffDate datetime,
  @NbrOfDaysUntilChargeOff int,
  @SystemChargeOffStatus char (5),
  @UserChargeOffStatus char (5),
  @InsFundsFeeNotChgOff char (5),
  @ChargeOffStatement char (5),
  @collectionfeesbnpco money,
  @currentbalanceco money,
  @DelinHistoryCtrCTD int,
  @AmtOfInterestCTD money,
  @AmtOfInterestLTD money,
  @AmtOfInterestMTD money,
  @AmtOfInterestYTD money,
  @IntAccrCycle money,
  @AfterCycleRevolvBSFC money,
  @AggregateDays int,
  @IntBilledNotPaid money,
  @interestbnpco money,
  @DeferredAccrued money,
  @DeferredAggregate money,
  @DeferredAggDays int,
  @NewTransactionsAccrued decimal(19,10),
  @NewTransactionsAgg money,
  @NewTransactionsBSFC money,
  @InterestPerDiem money,
  @RevolvingAccrued decimal(19,10),
  @RevolvingAgg money,
  @RevolvingBSFC money,
  @TotalAccruedInterest money,
  @TotalBSFC money,
  @latefeesbnpco money,
  @membershipfeesbnpco money,
  @nsffeesbnpco money,
  @overlimitfeesbnpco money,
  @PayHistoryCtrCTD int,
  @PrePaidAmount money,
  @principalco money,
  @ratechgeffdate datetime,
  @recoveryfeesbnpco money,
  @totalamountco money,
  @servicefeesbnpco money,
  @AutoInitialChargeOffReason char (5),
  @AutoInitialChargeOffStartDate datetime,
  @ManualInitialChargeOffReason char (5),
  @ManualInitialChargeOffStartDate datetime,
  @ChargeOffProcessIndicator char (5),
  @ChargeOffDateParam datetime,
  @FinalChargeOffDateParam datetime,
  @AutoInitialChargeOffCriteria char (5),
  @AutoInitialChargeOffCriteria_t char (5),
  @AutoInitialChargeOffCriteria_m char (5),
  @AutoInitialChargeOffFreq char (5),
  @AutoFinalChargeOffCriteria char (5),
  @AutoFinalChargeOffCriteria_t char (5),
  @AutoFinalChargeOffCriteria_m char (5),
  @AutoFinalChargeOffPeriod int,
  @AutoFinalChargeOffFreq char (5),
  @ReageDate1 datetime,
  @ReageDate2 datetime,
  @ReageDate3 datetime,
  @ReageDate4 datetime,
  @ReageDate5 datetime,
  @ReageDate6 datetime,
  @ReageTypeIndic1 int,
  @ReageTypeIndic2 int,
  @ReageTypeIndic3 int,
  @ReageTypeIndic4 int,
  @ReageTypeIndic5 int,
  @ReageTypeIndic6 int,
  @AmountOfPaymentsDTD money,
  @PastDueRangeAmt1 money,
  @PastDueRangeAmt2 money,
  @PastDueRangeAmt3 money,
  @PastDueRangeAmt4 money,
  @PastDueRangeAmt5 money,
  @PastDueRangeAmt6 money,
  @PastDueRangeAmt7 money,
  @PastDueRangeAmt8 money,
  @PastDueRangeCnt1 int,
  @PastDueRangeCnt2 int,
  @PastDueRangeCnt3 int,
  @PastDueRangeCnt4 int,
  @PastDueRangeCnt5 int,
  @PastDueRangeCnt6 int,
  @PastDueRangeCnt7 int,
  @PastDueRangeCnt8 int,
  @CurrentDue money,
  @FirstDueDate datetime,
  @WaiveInterestFor char (2),
  @WaiveInterestFrom char (1),
  @InsFundsFeeNotChgOffFor char (2),
  @InsFundsFeeNotChgOffFrom char (1),
  @FinalCOAmount money,
  @PrincipalDefCTD money,
  @PrincipalDefCC1 money,
  @PrincipalDefCC2 money,
  @PrincipalDefCC3 money,
  @PrincipalDefAdjustment money,
  @OverlimitFeeAdjustment money,
  @AmountOfCreditsAsPmt money,
  @AmountOfCreditsAsPmtCTD money,
  @AmountOfCreditsAsPmtCC1 money,
  @AmountOfCreditsAsPmtCC2 money,
  @AmountOfCreditsAsPmtCC3 money,
  @AmountOfCreditsAsPmtMTD money,
  @AmountOfCreditsAsPmtQTD money,
  @AmountOfCreditsAsPmtYTD money,
  @AmountOfCreditsAsPmtLTD money,
  @PendingBalIndicator money,
  @PlanCancelationDate datetime,
  @BeginningBalance_TranTime money,
  @YTDFeesTotalOnly money,
  @YTDIntTotalsOnly money,
  @CTDtotalFeesDebit money,
  @CTDtotalFeesCredit money,
  @CTDtotalIntDebit money,
  @CTDtotalIntCredit money,
  @CTDLateFees money,
  @CTDLateFeesCredit money,
  @CTDLateFeesDebit money,
  @YTDLateFees money,
  @CTDNSFFees money,
  @CTDNSFFeesCredit money,
  @CTDNSFFeesDebit money,
  @YTDNSFFees money,
  @CTDMinimumCharge money,
  @CTDMinimumChargeCredit money,
  @CTDMinimumChargeDebit money,
  @YTDMinimumCharge money,
  @COEligibilityDate datetime,
  @AccountOpenDate datetime,
  @AutoDispInitiateDate datetime,
  @FirstLateFeeWaiveDate datetime,
  @OverlimitBalanceCTD money,
  @AccumulatedOverlimitBalance money,
  @OriginalDueDate datetime,
  @LDStatusUpdateDate datetime,
  @AnticipatedPayOffAmount money,
  @DlqOneCpdLtdCount int,
  @DlqTwoCpdLtdCount int,
  @DlqThreePlusCpdLtdCount int,
  @PriEmbActivationFlag int,
  @DMinThrhldAutoResCount int,
  @TotalTransactionFeesCO money,
  @TotalLateFeesCO money,
  @TotalInsufficientFundsFeesCO money,
  @TotalOverlimitFeesCO money,
  @TotalInsurancePremiumsCO money,
  @TotalCollectionExpensesCO money,
  @TotalOtherFeesCO money,
  @TotalAnnualFeesCO money,
  @TotalInterestCO money,
  @TotalPrincipalCO money,
  @StatementRunningBalance money,
  @StatementRemainingBalance money,
  @RecoveryFeeDate datetime,
  @QualifiedCycleCountRecoveryfee int,
  @AcctInDelinq2Status int,
  @CollateralID varchar (50),
  @RegZ52aEndDate datetime,
  @RegZ52aAmountThreshold money,
  @RegZ52aFeeAmountYTD money,
  @RunningMinimumDue money,
  @RemainingMinimumDue money,
  @CycleDue_DTDAtChargeoff int,
  @BankruptcyFileDate datetime) AS
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET QUOTED_IDENTIFIER ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;
SET NOCOUNT OFF;

IF EXISTS (SELECT [acctId] FROM DBO.BSegmentCreditCard WHERE 
   [acctId] = @acctId 
)
UPDATE DBO.BSegmentCreditCard SET  [FixedPaymentAmt] = @FixedPaymentAmt,
  [FixedPaymentPercent] = @FixedPaymentPercent,
  [PaymentLevel] = @PaymentLevel,
  [PaymentType] = @PaymentType,
  [AmountOfPayment120DLate] = @AmountOfPayment120DLate,
  [AmountOfPayment150DLate] = @AmountOfPayment150DLate,
  [AmountOfPayment180DLate] = @AmountOfPayment180DLate,
  [AmountOfPayment210DLate] = @AmountOfPayment210DLate,
  [AmountOfPayment30DLate] = @AmountOfPayment30DLate,
  [AmountOfPayment60DLate] = @AmountOfPayment60DLate,
  [AmountOfPayment90DLate] = @AmountOfPayment90DLate,
  [AmtOfPayXDLate] = @AmtOfPayXDLate,
  [AmountOfTotalDue] = @AmountOfTotalDue,
  [AutoSkipPaymentOpt] = @AutoSkipPaymentOpt,
  [pmtpriority] = @pmtpriority,
  [BalSubjPayment] = @BalSubjPayment,
  [SkipPayOptInEffect] = @SkipPayOptInEffect,
  [TempBalSubjPayment] = @TempBalSubjPayment,
  [TempCurrentDue] = @TempCurrentDue,
  [WaiveInterest] = @WaiveInterest,
  [BSWFeeIntStartDate] = @BSWFeeIntStartDate,
  [DtOfLastDelinqCTD] = @DtOfLastDelinqCTD,
  [DateOfOriginalPaymentDueDTD] = @DateOfOriginalPaymentDueDTD,
  [DateOfTotalDue] = @DateOfTotalDue,
  [NumberTimesReaged] = @NumberTimesReaged,
  [LastSkipPymtDate] = @LastSkipPymtDate,
  [LastSkipPymtAmt] = @LastSkipPymtAmt,
  [NoOfSkipPymts] = @NoOfSkipPymts,
  [NoPayDaysDelinquent] = @NoPayDaysDelinquent,
  [VirtualHdOfDelqChain] = @VirtualHdOfDelqChain,
  [CollReasonCode] = @CollReasonCode,
  [NextPaymentDueDate] = @NextPaymentDueDate,
  [NumberOfPaymentPastDue] = @NumberOfPaymentPastDue,
  [NumberOfPayment30DLate] = @NumberOfPayment30DLate,
  [NumberOfPayment60DLate] = @NumberOfPayment60DLate,
  [NumberOfPayment90DLate] = @NumberOfPayment90DLate,
  [NumberOfPayment120DLate] = @NumberOfPayment120DLate,
  [NumberOfPayment150DLate] = @NumberOfPayment150DLate,
  [NumberOfPayment180DLate] = @NumberOfPayment180DLate,
  [NumberOfPayment210DLate] = @NumberOfPayment210DLate,
  [daysdelinquent] = @daysdelinquent,
  [HighDelqBalanceLTD] = @HighDelqBalanceLTD,
  [HighCyclePastDueLTD] = @HighCyclePastDueLTD,
  [InterestDisclCycle] = @InterestDisclCycle,
  [InterestDisclMethod] = @InterestDisclMethod,
  [AmtGenIntCredits] = @AmtGenIntCredits,
  [AmtGenInterestCreditsLTD] = @AmtGenInterestCreditsLTD,
  [AmtGenInterestCreditsYTD] = @AmtGenInterestCreditsYTD,
  [AmtInterestCreditsCTD] = @AmtInterestCreditsCTD,
  [AmtInterestCreditsLTD] = @AmtInterestCreditsLTD,
  [AmtInterestCreditsYTD] = @AmtInterestCreditsYTD,
  [AutoFinalChargeOffTiming] = @AutoFinalChargeOffTiming,
  [ChrgdOffAcctAccrMeth] = @ChrgdOffAcctAccrMeth,
  [ChargeOffAccountStatus] = @ChargeOffAccountStatus,
  [ChargeOffDate] = @ChargeOffDate,
  [DirectDebitPayStatus] = @DirectDebitPayStatus,
  [FinalChargeOffDate] = @FinalChargeOffDate,
  [NbrOfDaysUntilChargeOff] = @NbrOfDaysUntilChargeOff,
  [SystemChargeOffStatus] = @SystemChargeOffStatus,
  [UserChargeOffStatus] = @UserChargeOffStatus,
  [InsFundsFeeNotChgOff] = @InsFundsFeeNotChgOff,
  [ChargeOffStatement] = @ChargeOffStatement,
  [collectionfeesbnpco] = @collectionfeesbnpco,
  [currentbalanceco] = @currentbalanceco,
  [DelinHistoryCtrCTD] = @DelinHistoryCtrCTD,
  [AmtOfInterestCTD] = @AmtOfInterestCTD,
  [AmtOfInterestLTD] = @AmtOfInterestLTD,
  [AmtOfInterestMTD] = @AmtOfInterestMTD,
  [AmtOfInterestYTD] = @AmtOfInterestYTD,
  [IntAccrCycle] = @IntAccrCycle,
  [AfterCycleRevolvBSFC] = @AfterCycleRevolvBSFC,
  [AggregateDays] = @AggregateDays,
  [IntBilledNotPaid] = @IntBilledNotPaid,
  [interestbnpco] = @interestbnpco,
  [DeferredAccrued] = @DeferredAccrued,
  [DeferredAggregate] = @DeferredAggregate,
  [DeferredAggDays] = @DeferredAggDays,
  [NewTransactionsAccrued] = @NewTransactionsAccrued,
  [NewTransactionsAgg] = @NewTransactionsAgg,
  [NewTransactionsBSFC] = @NewTransactionsBSFC,
  [InterestPerDiem] = @InterestPerDiem,
  [RevolvingAccrued] = @RevolvingAccrued,
  [RevolvingAgg] = @RevolvingAgg,
  [RevolvingBSFC] = @RevolvingBSFC,
  [TotalAccruedInterest] = @TotalAccruedInterest,
  [TotalBSFC] = @TotalBSFC,
  [latefeesbnpco] = @latefeesbnpco,
  [membershipfeesbnpco] = @membershipfeesbnpco,
  [nsffeesbnpco] = @nsffeesbnpco,
  [overlimitfeesbnpco] = @overlimitfeesbnpco,
  [PayHistoryCtrCTD] = @PayHistoryCtrCTD,
  [PrePaidAmount] = @PrePaidAmount,
  [principalco] = @principalco,
  [ratechgeffdate] = @ratechgeffdate,
  [recoveryfeesbnpco] = @recoveryfeesbnpco,
  [totalamountco] = @totalamountco,
  [servicefeesbnpco] = @servicefeesbnpco,
  [AutoInitialChargeOffReason] = @AutoInitialChargeOffReason,
  [AutoInitialChargeOffStartDate] = @AutoInitialChargeOffStartDate,
  [ManualInitialChargeOffReason] = @ManualInitialChargeOffReason,
  [ManualInitialChargeOffStartDate] = @ManualInitialChargeOffStartDate,
  [ChargeOffProcessIndicator] = @ChargeOffProcessIndicator,
  [ChargeOffDateParam] = @ChargeOffDateParam,
  [FinalChargeOffDateParam] = @FinalChargeOffDateParam,
  [AutoInitialChargeOffCriteria] = @AutoInitialChargeOffCriteria,
  [AutoInitialChargeOffCriteria_t] = @AutoInitialChargeOffCriteria_t,
  [AutoInitialChargeOffCriteria_m] = @AutoInitialChargeOffCriteria_m,
  [AutoInitialChargeOffFreq] = @AutoInitialChargeOffFreq,
  [AutoFinalChargeOffCriteria] = @AutoFinalChargeOffCriteria,
  [AutoFinalChargeOffCriteria_t] = @AutoFinalChargeOffCriteria_t,
  [AutoFinalChargeOffCriteria_m] = @AutoFinalChargeOffCriteria_m,
  [AutoFinalChargeOffPeriod] = @AutoFinalChargeOffPeriod,
  [AutoFinalChargeOffFreq] = @AutoFinalChargeOffFreq,
  [ReageDate1] = @ReageDate1,
  [ReageDate2] = @ReageDate2,
  [ReageDate3] = @ReageDate3,
  [ReageDate4] = @ReageDate4,
  [ReageDate5] = @ReageDate5,
  [ReageDate6] = @ReageDate6,
  [ReageTypeIndic1] = @ReageTypeIndic1,
  [ReageTypeIndic2] = @ReageTypeIndic2,
  [ReageTypeIndic3] = @ReageTypeIndic3,
  [ReageTypeIndic4] = @ReageTypeIndic4,
  [ReageTypeIndic5] = @ReageTypeIndic5,
  [ReageTypeIndic6] = @ReageTypeIndic6,
  [AmountOfPaymentsDTD] = @AmountOfPaymentsDTD,
  [PastDueRangeAmt1] = @PastDueRangeAmt1,
  [PastDueRangeAmt2] = @PastDueRangeAmt2,
  [PastDueRangeAmt3] = @PastDueRangeAmt3,
  [PastDueRangeAmt4] = @PastDueRangeAmt4,
  [PastDueRangeAmt5] = @PastDueRangeAmt5,
  [PastDueRangeAmt6] = @PastDueRangeAmt6,
  [PastDueRangeAmt7] = @PastDueRangeAmt7,
  [PastDueRangeAmt8] = @PastDueRangeAmt8,
  [PastDueRangeCnt1] = @PastDueRangeCnt1,
  [PastDueRangeCnt2] = @PastDueRangeCnt2,
  [PastDueRangeCnt3] = @PastDueRangeCnt3,
  [PastDueRangeCnt4] = @PastDueRangeCnt4,
  [PastDueRangeCnt5] = @PastDueRangeCnt5,
  [PastDueRangeCnt6] = @PastDueRangeCnt6,
  [PastDueRangeCnt7] = @PastDueRangeCnt7,
  [PastDueRangeCnt8] = @PastDueRangeCnt8,
  [CurrentDue] = @CurrentDue,
  [FirstDueDate] = @FirstDueDate,
  [WaiveInterestFor] = @WaiveInterestFor,
  [WaiveInterestFrom] = @WaiveInterestFrom,
  [InsFundsFeeNotChgOffFor] = @InsFundsFeeNotChgOffFor,
  [InsFundsFeeNotChgOffFrom] = @InsFundsFeeNotChgOffFrom,
  [FinalCOAmount] = @FinalCOAmount,
  [PrincipalDefCTD] = @PrincipalDefCTD,
  [PrincipalDefCC1] = @PrincipalDefCC1,
  [PrincipalDefCC2] = @PrincipalDefCC2,
  [PrincipalDefCC3] = @PrincipalDefCC3,
  [PrincipalDefAdjustment] = @PrincipalDefAdjustment,
  [OverlimitFeeAdjustment] = @OverlimitFeeAdjustment,
  [AmountOfCreditsAsPmt] = @AmountOfCreditsAsPmt,
  [AmountOfCreditsAsPmtCTD] = @AmountOfCreditsAsPmtCTD,
  [AmountOfCreditsAsPmtCC1] = @AmountOfCreditsAsPmtCC1,
  [AmountOfCreditsAsPmtCC2] = @AmountOfCreditsAsPmtCC2,
  [AmountOfCreditsAsPmtCC3] = @AmountOfCreditsAsPmtCC3,
  [AmountOfCreditsAsPmtMTD] = @AmountOfCreditsAsPmtMTD,
  [AmountOfCreditsAsPmtQTD] = @AmountOfCreditsAsPmtQTD,
  [AmountOfCreditsAsPmtYTD] = @AmountOfCreditsAsPmtYTD,
  [AmountOfCreditsAsPmtLTD] = @AmountOfCreditsAsPmtLTD,
  [PendingBalIndicator] = @PendingBalIndicator,
  [PlanCancelationDate] = @PlanCancelationDate,
  [BeginningBalance_TranTime] = @BeginningBalance_TranTime,
  [YTDFeesTotalOnly] = @YTDFeesTotalOnly,
  [YTDIntTotalsOnly] = @YTDIntTotalsOnly,
  [CTDtotalFeesDebit] = @CTDtotalFeesDebit,
  [CTDtotalFeesCredit] = @CTDtotalFeesCredit,
  [CTDtotalIntDebit] = @CTDtotalIntDebit,
  [CTDtotalIntCredit] = @CTDtotalIntCredit,
  [CTDLateFees] = @CTDLateFees,
  [CTDLateFeesCredit] = @CTDLateFeesCredit,
  [CTDLateFeesDebit] = @CTDLateFeesDebit,
  [YTDLateFees] = @YTDLateFees,
  [CTDNSFFees] = @CTDNSFFees,
  [CTDNSFFeesCredit] = @CTDNSFFeesCredit,
  [CTDNSFFeesDebit] = @CTDNSFFeesDebit,
  [YTDNSFFees] = @YTDNSFFees,
  [CTDMinimumCharge] = @CTDMinimumCharge,
  [CTDMinimumChargeCredit] = @CTDMinimumChargeCredit,
  [CTDMinimumChargeDebit] = @CTDMinimumChargeDebit,
  [YTDMinimumCharge] = @YTDMinimumCharge,
  [COEligibilityDate] = @COEligibilityDate,
  [AccountOpenDate] = @AccountOpenDate,
  [AutoDispInitiateDate] = @AutoDispInitiateDate,
  [FirstLateFeeWaiveDate] = @FirstLateFeeWaiveDate,
  [OverlimitBalanceCTD] = @OverlimitBalanceCTD,
  [AccumulatedOverlimitBalance] = @AccumulatedOverlimitBalance,
  [OriginalDueDate] = @OriginalDueDate,
  [LDStatusUpdateDate] = @LDStatusUpdateDate,
  [AnticipatedPayOffAmount] = @AnticipatedPayOffAmount,
  [DlqOneCpdLtdCount] = @DlqOneCpdLtdCount,
  [DlqTwoCpdLtdCount] = @DlqTwoCpdLtdCount,
  [DlqThreePlusCpdLtdCount] = @DlqThreePlusCpdLtdCount,
  [PriEmbActivationFlag] = @PriEmbActivationFlag,
  [DMinThrhldAutoResCount] = @DMinThrhldAutoResCount,
  [TotalTransactionFeesCO] = @TotalTransactionFeesCO,
  [TotalLateFeesCO] = @TotalLateFeesCO,
  [TotalInsufficientFundsFeesCO] = @TotalInsufficientFundsFeesCO,
  [TotalOverlimitFeesCO] = @TotalOverlimitFeesCO,
  [TotalInsurancePremiumsCO] = @TotalInsurancePremiumsCO,
  [TotalCollectionExpensesCO] = @TotalCollectionExpensesCO,
  [TotalOtherFeesCO] = @TotalOtherFeesCO,
  [TotalAnnualFeesCO] = @TotalAnnualFeesCO,
  [TotalInterestCO] = @TotalInterestCO,
  [TotalPrincipalCO] = @TotalPrincipalCO,
  [StatementRunningBalance] = @StatementRunningBalance,
  [StatementRemainingBalance] = @StatementRemainingBalance,
  [RecoveryFeeDate] = @RecoveryFeeDate,
  [QualifiedCycleCountRecoveryfee] = @QualifiedCycleCountRecoveryfee,
  [AcctInDelinq2Status] = @AcctInDelinq2Status,
  [CollateralID] = @CollateralID,
  [RegZ52aEndDate] = @RegZ52aEndDate,
  [RegZ52aAmountThreshold] = @RegZ52aAmountThreshold,
  [RegZ52aFeeAmountYTD] = @RegZ52aFeeAmountYTD,
  [RunningMinimumDue] = @RunningMinimumDue,
  [RemainingMinimumDue] = @RemainingMinimumDue,
  [CycleDue_DTDAtChargeoff] = @CycleDue_DTDAtChargeoff,
  [BankruptcyFileDate] = @BankruptcyFileDate

WHERE 
   [acctId] = @acctId 
ELSE
INSERT INTO DBO.BSegmentCreditCard
 ( [acctId],
 [FixedPaymentAmt],
 [FixedPaymentPercent],
 [PaymentLevel],
 [PaymentType],
 [AmountOfPayment120DLate],
 [AmountOfPayment150DLate],
 [AmountOfPayment180DLate],
 [AmountOfPayment210DLate],
 [AmountOfPayment30DLate],
 [AmountOfPayment60DLate],
 [AmountOfPayment90DLate],
 [AmtOfPayXDLate],
 [AmountOfTotalDue],
 [AutoSkipPaymentOpt],
 [pmtpriority],
 [BalSubjPayment],
 [SkipPayOptInEffect],
 [TempBalSubjPayment],
 [TempCurrentDue],
 [WaiveInterest],
 [BSWFeeIntStartDate],
 [DtOfLastDelinqCTD],
 [DateOfOriginalPaymentDueDTD],
 [DateOfTotalDue],
 [NumberTimesReaged],
 [LastSkipPymtDate],
 [LastSkipPymtAmt],
 [NoOfSkipPymts],
 [NoPayDaysDelinquent],
 [VirtualHdOfDelqChain],
 [CollReasonCode],
 [NextPaymentDueDate],
 [NumberOfPaymentPastDue],
 [NumberOfPayment30DLate],
 [NumberOfPayment60DLate],
 [NumberOfPayment90DLate],
 [NumberOfPayment120DLate],
 [NumberOfPayment150DLate],
 [NumberOfPayment180DLate],
 [NumberOfPayment210DLate],
 [daysdelinquent],
 [HighDelqBalanceLTD],
 [HighCyclePastDueLTD],
 [InterestDisclCycle],
 [InterestDisclMethod],
 [AmtGenIntCredits],
 [AmtGenInterestCreditsLTD],
 [AmtGenInterestCreditsYTD],
 [AmtInterestCreditsCTD],
 [AmtInterestCreditsLTD],
 [AmtInterestCreditsYTD],
 [AutoFinalChargeOffTiming],
 [ChrgdOffAcctAccrMeth],
 [ChargeOffAccountStatus],
 [ChargeOffDate],
 [DirectDebitPayStatus],
 [FinalChargeOffDate],
 [NbrOfDaysUntilChargeOff],
 [SystemChargeOffStatus],
 [UserChargeOffStatus],
 [InsFundsFeeNotChgOff],
 [ChargeOffStatement],
 [collectionfeesbnpco],
 [currentbalanceco],
 [DelinHistoryCtrCTD],
 [AmtOfInterestCTD],
 [AmtOfInterestLTD],
 [AmtOfInterestMTD],
 [AmtOfInterestYTD],
 [IntAccrCycle],
 [AfterCycleRevolvBSFC],
 [AggregateDays],
 [IntBilledNotPaid],
 [interestbnpco],
 [DeferredAccrued],
 [DeferredAggregate],
 [DeferredAggDays],
 [NewTransactionsAccrued],
 [NewTransactionsAgg],
 [NewTransactionsBSFC],
 [InterestPerDiem],
 [RevolvingAccrued],
 [RevolvingAgg],
 [RevolvingBSFC],
 [TotalAccruedInterest],
 [TotalBSFC],
 [latefeesbnpco],
 [membershipfeesbnpco],
 [nsffeesbnpco],
 [overlimitfeesbnpco],
 [PayHistoryCtrCTD],
 [PrePaidAmount],
 [principalco],
 [ratechgeffdate],
 [recoveryfeesbnpco],
 [totalamountco],
 [servicefeesbnpco],
 [AutoInitialChargeOffReason],
 [AutoInitialChargeOffStartDate],
 [ManualInitialChargeOffReason],
 [ManualInitialChargeOffStartDate],
 [ChargeOffProcessIndicator],
 [ChargeOffDateParam],
 [FinalChargeOffDateParam],
 [AutoInitialChargeOffCriteria],
 [AutoInitialChargeOffCriteria_t],
 [AutoInitialChargeOffCriteria_m],
 [AutoInitialChargeOffFreq],
 [AutoFinalChargeOffCriteria],
 [AutoFinalChargeOffCriteria_t],
 [AutoFinalChargeOffCriteria_m],
 [AutoFinalChargeOffPeriod],
 [AutoFinalChargeOffFreq],
 [ReageDate1],
 [ReageDate2],
 [ReageDate3],
 [ReageDate4],
 [ReageDate5],
 [ReageDate6],
 [ReageTypeIndic1],
 [ReageTypeIndic2],
 [ReageTypeIndic3],
 [ReageTypeIndic4],
 [ReageTypeIndic5],
 [ReageTypeIndic6],
 [AmountOfPaymentsDTD],
 [PastDueRangeAmt1],
 [PastDueRangeAmt2],
 [PastDueRangeAmt3],
 [PastDueRangeAmt4],
 [PastDueRangeAmt5],
 [PastDueRangeAmt6],
 [PastDueRangeAmt7],
 [PastDueRangeAmt8],
 [PastDueRangeCnt1],
 [PastDueRangeCnt2],
 [PastDueRangeCnt3],
 [PastDueRangeCnt4],
 [PastDueRangeCnt5],
 [PastDueRangeCnt6],
 [PastDueRangeCnt7],
 [PastDueRangeCnt8],
 [CurrentDue],
 [FirstDueDate],
 [WaiveInterestFor],
 [WaiveInterestFrom],
 [InsFundsFeeNotChgOffFor],
 [InsFundsFeeNotChgOffFrom],
 [FinalCOAmount],
 [PrincipalDefCTD],
 [PrincipalDefCC1],
 [PrincipalDefCC2],
 [PrincipalDefCC3],
 [PrincipalDefAdjustment],
 [OverlimitFeeAdjustment],
 [AmountOfCreditsAsPmt],
 [AmountOfCreditsAsPmtCTD],
 [AmountOfCreditsAsPmtCC1],
 [AmountOfCreditsAsPmtCC2],
 [AmountOfCreditsAsPmtCC3],
 [AmountOfCreditsAsPmtMTD],
 [AmountOfCreditsAsPmtQTD],
 [AmountOfCreditsAsPmtYTD],
 [AmountOfCreditsAsPmtLTD],
 [PendingBalIndicator],
 [PlanCancelationDate],
 [BeginningBalance_TranTime],
 [YTDFeesTotalOnly],
 [YTDIntTotalsOnly],
 [CTDtotalFeesDebit],
 [CTDtotalFeesCredit],
 [CTDtotalIntDebit],
 [CTDtotalIntCredit],
 [CTDLateFees],
 [CTDLateFeesCredit],
 [CTDLateFeesDebit],
 [YTDLateFees],
 [CTDNSFFees],
 [CTDNSFFeesCredit],
 [CTDNSFFeesDebit],
 [YTDNSFFees],
 [CTDMinimumCharge],
 [CTDMinimumChargeCredit],
 [CTDMinimumChargeDebit],
 [YTDMinimumCharge],
 [COEligibilityDate],
 [AccountOpenDate],
 [AutoDispInitiateDate],
 [FirstLateFeeWaiveDate],
 [OverlimitBalanceCTD],
 [AccumulatedOverlimitBalance],
 [OriginalDueDate],
 [LDStatusUpdateDate],
 [AnticipatedPayOffAmount],
 [DlqOneCpdLtdCount],
 [DlqTwoCpdLtdCount],
 [DlqThreePlusCpdLtdCount],
 [PriEmbActivationFlag],
 [DMinThrhldAutoResCount],
 [TotalTransactionFeesCO],
 [TotalLateFeesCO],
 [TotalInsufficientFundsFeesCO],
 [TotalOverlimitFeesCO],
 [TotalInsurancePremiumsCO],
 [TotalCollectionExpensesCO],
 [TotalOtherFeesCO],
 [TotalAnnualFeesCO],
 [TotalInterestCO],
 [TotalPrincipalCO],
 [StatementRunningBalance],
 [StatementRemainingBalance],
 [RecoveryFeeDate],
 [QualifiedCycleCountRecoveryfee],
 [AcctInDelinq2Status],
 [CollateralID],
 [RegZ52aEndDate],
 [RegZ52aAmountThreshold],
 [RegZ52aFeeAmountYTD],
 [RunningMinimumDue],
 [RemainingMinimumDue],
 [CycleDue_DTDAtChargeoff],
 [BankruptcyFileDate]) VALUES ( @acctId,
 @FixedPaymentAmt,
 @FixedPaymentPercent,
 @PaymentLevel,
 @PaymentType,
 @AmountOfPayment120DLate,
 @AmountOfPayment150DLate,
 @AmountOfPayment180DLate,
 @AmountOfPayment210DLate,
 @AmountOfPayment30DLate,
 @AmountOfPayment60DLate,
 @AmountOfPayment90DLate,
 @AmtOfPayXDLate,
 @AmountOfTotalDue,
 @AutoSkipPaymentOpt,
 @pmtpriority,
 @BalSubjPayment,
 @SkipPayOptInEffect,
 @TempBalSubjPayment,
 @TempCurrentDue,
 @WaiveInterest,
 @BSWFeeIntStartDate,
 @DtOfLastDelinqCTD,
 @DateOfOriginalPaymentDueDTD,
 @DateOfTotalDue,
 @NumberTimesReaged,
 @LastSkipPymtDate,
 @LastSkipPymtAmt,
 @NoOfSkipPymts,
 @NoPayDaysDelinquent,
 @VirtualHdOfDelqChain,
 @CollReasonCode,
 @NextPaymentDueDate,
 @NumberOfPaymentPastDue,
 @NumberOfPayment30DLate,
 @NumberOfPayment60DLate,
 @NumberOfPayment90DLate,
 @NumberOfPayment120DLate,
 @NumberOfPayment150DLate,
 @NumberOfPayment180DLate,
 @NumberOfPayment210DLate,
 @daysdelinquent,
 @HighDelqBalanceLTD,
 @HighCyclePastDueLTD,
 @InterestDisclCycle,
 @InterestDisclMethod,
 @AmtGenIntCredits,
 @AmtGenInterestCreditsLTD,
 @AmtGenInterestCreditsYTD,
 @AmtInterestCreditsCTD,
 @AmtInterestCreditsLTD,
 @AmtInterestCreditsYTD,
 @AutoFinalChargeOffTiming,
 @ChrgdOffAcctAccrMeth,
 @ChargeOffAccountStatus,
 @ChargeOffDate,
 @DirectDebitPayStatus,
 @FinalChargeOffDate,
 @NbrOfDaysUntilChargeOff,
 @SystemChargeOffStatus,
 @UserChargeOffStatus,
 @InsFundsFeeNotChgOff,
 @ChargeOffStatement,
 @collectionfeesbnpco,
 @currentbalanceco,
 @DelinHistoryCtrCTD,
 @AmtOfInterestCTD,
 @AmtOfInterestLTD,
 @AmtOfInterestMTD,
 @AmtOfInterestYTD,
 @IntAccrCycle,
 @AfterCycleRevolvBSFC,
 @AggregateDays,
 @IntBilledNotPaid,
 @interestbnpco,
 @DeferredAccrued,
 @DeferredAggregate,
 @DeferredAggDays,
 @NewTransactionsAccrued,
 @NewTransactionsAgg,
 @NewTransactionsBSFC,
 @InterestPerDiem,
 @RevolvingAccrued,
 @RevolvingAgg,
 @RevolvingBSFC,
 @TotalAccruedInterest,
 @TotalBSFC,
 @latefeesbnpco,
 @membershipfeesbnpco,
 @nsffeesbnpco,
 @overlimitfeesbnpco,
 @PayHistoryCtrCTD,
 @PrePaidAmount,
 @principalco,
 @ratechgeffdate,
 @recoveryfeesbnpco,
 @totalamountco,
 @servicefeesbnpco,
 @AutoInitialChargeOffReason,
 @AutoInitialChargeOffStartDate,
 @ManualInitialChargeOffReason,
 @ManualInitialChargeOffStartDate,
 @ChargeOffProcessIndicator,
 @ChargeOffDateParam,
 @FinalChargeOffDateParam,
 @AutoInitialChargeOffCriteria,
 @AutoInitialChargeOffCriteria_t,
 @AutoInitialChargeOffCriteria_m,
 @AutoInitialChargeOffFreq,
 @AutoFinalChargeOffCriteria,
 @AutoFinalChargeOffCriteria_t,
 @AutoFinalChargeOffCriteria_m,
 @AutoFinalChargeOffPeriod,
 @AutoFinalChargeOffFreq,
 @ReageDate1,
 @ReageDate2,
 @ReageDate3,
 @ReageDate4,
 @ReageDate5,
 @ReageDate6,
 @ReageTypeIndic1,
 @ReageTypeIndic2,
 @ReageTypeIndic3,
 @ReageTypeIndic4,
 @ReageTypeIndic5,
 @ReageTypeIndic6,
 @AmountOfPaymentsDTD,
 @PastDueRangeAmt1,
 @PastDueRangeAmt2,
 @PastDueRangeAmt3,
 @PastDueRangeAmt4,
 @PastDueRangeAmt5,
 @PastDueRangeAmt6,
 @PastDueRangeAmt7,
 @PastDueRangeAmt8,
 @PastDueRangeCnt1,
 @PastDueRangeCnt2,
 @PastDueRangeCnt3,
 @PastDueRangeCnt4,
 @PastDueRangeCnt5,
 @PastDueRangeCnt6,
 @PastDueRangeCnt7,
 @PastDueRangeCnt8,
 @CurrentDue,
 @FirstDueDate,
 @WaiveInterestFor,
 @WaiveInterestFrom,
 @InsFundsFeeNotChgOffFor,
 @InsFundsFeeNotChgOffFrom,
 @FinalCOAmount,
 @PrincipalDefCTD,
 @PrincipalDefCC1,
 @PrincipalDefCC2,
 @PrincipalDefCC3,
 @PrincipalDefAdjustment,
 @OverlimitFeeAdjustment,
 @AmountOfCreditsAsPmt,
 @AmountOfCreditsAsPmtCTD,
 @AmountOfCreditsAsPmtCC1,
 @AmountOfCreditsAsPmtCC2,
 @AmountOfCreditsAsPmtCC3,
 @AmountOfCreditsAsPmtMTD,
 @AmountOfCreditsAsPmtQTD,
 @AmountOfCreditsAsPmtYTD,
 @AmountOfCreditsAsPmtLTD,
 @PendingBalIndicator,
 @PlanCancelationDate,
 @BeginningBalance_TranTime,
 @YTDFeesTotalOnly,
 @YTDIntTotalsOnly,
 @CTDtotalFeesDebit,
 @CTDtotalFeesCredit,
 @CTDtotalIntDebit,
 @CTDtotalIntCredit,
 @CTDLateFees,
 @CTDLateFeesCredit,
 @CTDLateFeesDebit,
 @YTDLateFees,
 @CTDNSFFees,
 @CTDNSFFeesCredit,
 @CTDNSFFeesDebit,
 @YTDNSFFees,
 @CTDMinimumCharge,
 @CTDMinimumChargeCredit,
 @CTDMinimumChargeDebit,
 @YTDMinimumCharge,
 @COEligibilityDate,
 @AccountOpenDate,
 @AutoDispInitiateDate,
 @FirstLateFeeWaiveDate,
 @OverlimitBalanceCTD,
 @AccumulatedOverlimitBalance,
 @OriginalDueDate,
 @LDStatusUpdateDate,
 @AnticipatedPayOffAmount,
 @DlqOneCpdLtdCount,
 @DlqTwoCpdLtdCount,
 @DlqThreePlusCpdLtdCount,
 @PriEmbActivationFlag,
 @DMinThrhldAutoResCount,
 @TotalTransactionFeesCO,
 @TotalLateFeesCO,
 @TotalInsufficientFundsFeesCO,
 @TotalOverlimitFeesCO,
 @TotalInsurancePremiumsCO,
 @TotalCollectionExpensesCO,
 @TotalOtherFeesCO,
 @TotalAnnualFeesCO,
 @TotalInterestCO,
 @TotalPrincipalCO,
 @StatementRunningBalance,
 @StatementRemainingBalance,
 @RecoveryFeeDate,
 @QualifiedCycleCountRecoveryfee,
 @AcctInDelinq2Status,
 @CollateralID,
 @RegZ52aEndDate,
 @RegZ52aAmountThreshold,
 @RegZ52aFeeAmountYTD,
 @RunningMinimumDue,
 @RemainingMinimumDue,
 @CycleDue_DTDAtChargeoff,
 @BankruptcyFileDate)
GO

grant execute on sp_BSegmentCreditCard_insupd to public 
GO

/* End of object msBSegmentCreditCard */
