
CREATE DATABASE [PP_Test_Secondary]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PP_Test_Secondary', FILENAME = N'\\BPLDEVDB01\Prasoon_Parashar\MDF\PP_Test_Secondary.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PP_Test_Secondary_log', FILENAME = N'\\BPLDEVDB01\Prasoon_Parashar\LDF\PP_Test_Secondary_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 WITH LEDGER = OFF
GO
ALTER DATABASE [PP_Test_Secondary] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PP_Test_Secondary] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PP_Test_Secondary] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PP_Test_Secondary] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PP_Test_Secondary] SET ARITHABORT OFF 
GO
ALTER DATABASE [PP_Test_Secondary] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PP_Test_Secondary] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PP_Test_Secondary] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [PP_Test_Secondary] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PP_Test_Secondary] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PP_Test_Secondary] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PP_Test_Secondary] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PP_Test_Secondary] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PP_Test_Secondary] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PP_Test_Secondary] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PP_Test_Secondary] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PP_Test_Secondary] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PP_Test_Secondary] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PP_Test_Secondary] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PP_Test_Secondary] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PP_Test_Secondary] SET  READ_WRITE 
GO
ALTER DATABASE [PP_Test_Secondary] SET RECOVERY FULL 
GO
ALTER DATABASE [PP_Test_Secondary] SET  MULTI_USER 
GO
ALTER DATABASE [PP_Test_Secondary] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PP_Test_Secondary] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PP_Test_Secondary] SET DELAYED_DURABILITY = DISABLED 
GO
USE [PP_Test_Secondary]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [PP_Test_Secondary]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [PP_Test_Secondary] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO