;WITH CTE
AS
(
SELECT *, ROW_NUMBER() OVER (PARTITION BY Name ORDER BY SN ASC) [RowCount]
FROM TempCricket
),
DoubleName
AS
(
SELECT Name FROM CTE WHERE [RowCount] > 1
)
SELECT T.* 
FROM TempCricket T
JOIN DoubleName D ON (T.Name = D.Name)
ORDER BY T.Name


;WITH CTE
AS
(
SELECT *, ROW_NUMBER() OVER (PARTITION BY Name ORDER BY SN ASC) [RowCount]
FROM TempCricket
)
SELECT Name, Team FROM CTE --WHERE [RowCount] > 1
ORDER BY Team






;WITH CTE
AS
(
SELECT *, ROW_NUMBER() OVER (PARTITION BY Name ORDER BY SN ASC) [RowCount]
FROM TempCricket
)
DELETE T
FROM TempCricket T 
JOIN CTE C ON (T.Name = C.Name)
WHERE [RowCount] > 1
AND T.Team = 'Uncapped'





DROP TABLE IF EXISTS TempCricket
CREATE TABLE TempCricket (SN DECIMAL(19, 0) IDENTITY(1, 1), Name VARCHAR(100), Team VARCHAR(50))
GO

INSERT INTO TempCricket
SELECT 'Ranveer Thakur ','Crazy Corecard 11'
UNION ALL SELECT 'Vishnu Raghuvanshi','Crazy Corecard 11'
UNION ALL SELECT 'Srijan jain ','Crazy Corecard 11'
UNION ALL SELECT 'manish yadav','Crazy Corecard 11'
UNION ALL SELECT 'vivek pal','Crazy Corecard 11'
UNION ALL SELECT 'Himanshu patel','Crazy Corecard 11'
UNION ALL SELECT 'yash kapoor','Crazy Corecard 11'
UNION ALL SELECT 'Anuj mittal','Crazy Corecard 11'
UNION ALL SELECT 'raj suman','Crazy Corecard 11'
UNION ALL SELECT 'vikash Kumar','Crazy Corecard 11'
UNION ALL SELECT 'Ankit Mitra','Crazy Corecard 11'
UNION ALL SELECT 'shivendra sharma','Crazy Corecard 11'
UNION ALL SELECT 'Nikhil badoni ','Crazy Corecard 11'
UNION ALL SELECT 'Durgesh wadbude','Crazy Corecard 11'
UNION ALL SELECT 'Bikesh sah','Crazy Corecard 11'
UNION ALL SELECT 'Yogendra Battu','Azmat 11'
UNION ALL SELECT 'Lokendra Battu','Azmat 11'
UNION ALL SELECT 'Azmat','Azmat 11'
UNION ALL SELECT 'Pradhuman','Azmat 11'
UNION ALL SELECT 'Ashish Saxena','Azmat 11'
UNION ALL SELECT 'Madan pal','Azmat 11'
UNION ALL SELECT 'Dharmendra','Azmat 11'
UNION ALL SELECT 'Sunny lot','Azmat 11'
UNION ALL SELECT 'Pavan','Azmat 11'
UNION ALL SELECT 'Sanjeet Meena','Azmat 11'
UNION ALL SELECT 'Shiv Kumar patel','Azmat 11'
UNION ALL SELECT 'Ravinder Suryavanshi','Azmat 11'
UNION ALL SELECT 'Amir Ali Khan','Azmat 11'
UNION ALL SELECT 'Deepak Prajapati','Azmat 11'
UNION ALL SELECT 'Abhishek singh Baghel','Azmat 11'
UNION ALL SELECT 'Nadir khan','Azmat 11'
UNION ALL SELECT 'Abhilash kaimal','Azmat 11'
UNION ALL SELECT 'Dhirendra Mishra','Core Warriors'
UNION ALL SELECT 'Lakush Rajput','Core Warriors'
UNION ALL SELECT 'Pramod Verma','Core Warriors'
UNION ALL SELECT 'Vijay Chandel','Core Warriors'
UNION ALL SELECT 'Rahul Baghel','Core Warriors'
UNION ALL SELECT 'Brijraj Singh','Core Warriors'
UNION ALL SELECT 'Ravindra Patel','Core Warriors'
UNION ALL SELECT 'Ajay Rajput','Core Warriors'
UNION ALL SELECT 'Abhilash kaimal','Core Warriors'
UNION ALL SELECT 'Siddhartha singh Negi','Core Warriors'
UNION ALL SELECT 'Ritik Sharma','Core Warriors'
UNION ALL SELECT 'Ankit sahu','Core Warriors'
UNION ALL SELECT 'ChandraKirti Vidharthi','Core Warriors'
UNION ALL SELECT 'Amit Mulmule','Core Warriors'
UNION ALL SELECT 'Pankaj Vishwakarma','Core Warriors'
UNION ALL SELECT 'Shashank jagne','Core Warriors'
UNION ALL SELECT 'Aman Singh','Core Warriors'
UNION ALL SELECT 'Anand dixit','Core Warriors'
UNION ALL SELECT 'Tarun Kumar Geed','Core Warriors'
UNION ALL SELECT 'Sandeep Sharma','Dream 11'
UNION ALL SELECT 'Prateek Dhimole','Dream 11'
UNION ALL SELECT 'Shashank Shrivastava','Dream 11'
UNION ALL SELECT 'Samarth Shrivastava','Dream 11'
UNION ALL SELECT 'Ravi Kumar','Dream 11'
UNION ALL SELECT 'Rajat Sharma','Dream 11'
UNION ALL SELECT 'Lovelesh Thalani','Dream 11'
UNION ALL SELECT 'Bharat patel','Dream 11'
UNION ALL SELECT 'Abhay Tiwari','Dream 11'
UNION ALL SELECT 'Praveen Mishra','Dream 11'
UNION ALL SELECT 'Chetan Deshmukh','Dream 11'
UNION ALL SELECT 'Anmol tomar','Dream 11'
UNION ALL SELECT 'Aishwarya Saxena','Dream 11'
UNION ALL SELECT 'Akshat Saxena','Dream 11'
UNION ALL SELECT 'Akash Choudhary','Dream 11'
UNION ALL SELECT 'Mahendra Dwivedi','Netra 11'
UNION ALL SELECT 'Afshaan Hussain','Netra 11'
UNION ALL SELECT 'Amit Mishra','Netra 11'
UNION ALL SELECT 'Netra Chettri','Netra 11'
UNION ALL SELECT 'Sunil Mishra','Netra 11'
UNION ALL SELECT 'Lakshya Kumawat','Netra 11'
UNION ALL SELECT 'Mohd. Anjum','Netra 11'
UNION ALL SELECT 'Ravi Prashant','Netra 11'
UNION ALL SELECT 'Surendra Potula','Netra 11'
UNION ALL SELECT 'Rajaram Singh','Netra 11'
UNION ALL SELECT 'Ramnivas Lodhi','Netra 11'
UNION ALL SELECT 'Raja Khandwe','Netra 11'
UNION ALL SELECT 'Manoj Soni','Netra 11'
UNION ALL SELECT 'Ravi Damade','Netra 11'
UNION ALL SELECT 'Siddhartha Chaurasia','Netra 11'
UNION ALL SELECT 'Aman Agarwal','Netra 11'
UNION ALL SELECT 'Ankit Sahu','Netra 11'
UNION ALL SELECT 'Akash Sharma','Netra 11'
UNION ALL SELECT 'Rahul Bajpai','Netra 11'
UNION ALL SELECT 'Samadhan Gogate','Netra 11'
UNION ALL SELECT 'Akhilesh Goyal ','Kamlesh 11'
UNION ALL SELECT 'Ankit Kumar Yadav ','Kamlesh 11'
UNION ALL SELECT 'Arg jain ','Kamlesh 11'
UNION ALL SELECT 'Deepak Prajapati ','Kamlesh 11'
UNION ALL SELECT 'Dhananjay Gaur ','Kamlesh 11'
UNION ALL SELECT 'Harsh Kushwaha ','Kamlesh 11'
UNION ALL SELECT 'Kamlesh Potphode','Kamlesh 11'
UNION ALL SELECT 'Niklesh Vishwakarma ','Kamlesh 11'
UNION ALL SELECT 'Rahul Paswan ','Kamlesh 11'
UNION ALL SELECT 'Rajesh maity ','Kamlesh 11'
UNION ALL SELECT 'Rajnish Kumar ','Kamlesh 11'
UNION ALL SELECT 'Satya Prakash ','Kamlesh 11'
UNION ALL SELECT 'Saurabh Tiwari ','Kamlesh 11'
UNION ALL SELECT 'Shakti Singh Tomer ','Kamlesh 11'
UNION ALL SELECT 'Shravan Kumar Chaurarasia ','Kamlesh 11'
UNION ALL SELECT 'Yashwant Dubey ','Kamlesh 11'
UNION ALL SELECT 'Yogendra Battu ','Kamlesh 11'
UNION ALL SELECT 'Aakash Tiwari','Aakash 11'
UNION ALL SELECT 'Chandra Bhushan Prasad','Aakash 11'
UNION ALL SELECT 'Gunjan Budkar','Aakash 11'
UNION ALL SELECT 'Nikhil Kumar','Aakash 11'
UNION ALL SELECT 'Sourav Tyagi','Aakash 11'
UNION ALL SELECT 'Susheel Upadhyay','Aakash 11'
UNION ALL SELECT 'Vicky Soni','Aakash 11'
UNION ALL SELECT 'Ankit Dongre','Aakash 11'
UNION ALL SELECT 'Shivam Dubey','Aakash 11'
UNION ALL SELECT 'Ronit lall','Aakash 11'
UNION ALL SELECT 'Nilesh Pal','Aakash 11'
UNION ALL SELECT 'Rishabh Bajpai','Aakash 11'
UNION ALL SELECT 'Atul Sagar','Aakash 11'
UNION ALL SELECT 'Sant kumar yadav','Aakash 11'
UNION ALL SELECT 'Aviral singh baghel','Aakash 11'
UNION ALL SELECT 'Reetesh Sharma','Royal Eleven'
UNION ALL SELECT 'Akash Sidhwani','Royal Eleven'
UNION ALL SELECT 'Anurag Jain','Royal Eleven'
UNION ALL SELECT 'Shivendra Shrivastava','Royal Eleven'
UNION ALL SELECT 'Deepesh Malviya','Royal Eleven'
UNION ALL SELECT 'Rajendra Singh','Royal Eleven'
UNION ALL SELECT 'Geetesh Pathak','Royal Eleven'
UNION ALL SELECT 'Dharmendra ','Royal Eleven'
UNION ALL SELECT 'Harsh Kushwah','Royal Eleven'
UNION ALL SELECT 'Shrikant Nair','Royal Eleven'
UNION ALL SELECT 'Kunal Bakshi','Royal Eleven'
UNION ALL SELECT 'Mohd Saif Ansari','Royal Eleven'
UNION ALL SELECT 'Shivam Kushwah','Royal Eleven'
UNION ALL SELECT 'Yograj Patel','Royal Eleven'
UNION ALL SELECT 'Ravi Raj Mishra','Royal Eleven'
UNION ALL SELECT 'Gaurav Upreti','Royal Eleven'
UNION ALL SELECT 'Kapil Kumar Gangrade','Kapil 11'
UNION ALL SELECT 'Praveen Kumar Yadav','Kapil 11'
UNION ALL SELECT 'Ashutosh Singh','Kapil 11'
UNION ALL SELECT 'Ajay Sharma','Kapil 11'
UNION ALL SELECT 'Tarun Kumar Mishra','Kapil 11'
UNION ALL SELECT 'Kundan Kumar Gour ','Kapil 11'
UNION ALL SELECT 'Mohammad Azhar','Kapil 11'
UNION ALL SELECT 'Rohit Tiwari ','Kapil 11'
UNION ALL SELECT 'Shivam Patel ','Kapil 11'
UNION ALL SELECT 'Rohan Dev Vinodiya','Kapil 11'
UNION ALL SELECT 'Harshit Mittal','Kapil 11'
UNION ALL SELECT 'Shubham Bagde','Kapil 11'
UNION ALL SELECT 'Neeraj Parihar','Kapil 11'
UNION ALL SELECT 'Gajendra Joshi','Kapil 11'
UNION ALL SELECT 'Tauseef Ahmad ','Kapil 11'
UNION ALL SELECT 'Chandra Prakash','Corecard Bulls'
UNION ALL SELECT 'Prasoon Parashar','Corecard Bulls'
UNION ALL SELECT 'Arun Lowanshi','Corecard Bulls'
UNION ALL SELECT 'Ankit Sharma','Corecard Bulls'
UNION ALL SELECT 'Arpit Jadon','Corecard Bulls'
UNION ALL SELECT 'Sandesh Jain','Corecard Bulls'
UNION ALL SELECT 'Gagan Gurjar','Corecard Bulls'
UNION ALL SELECT 'Ayansh Dubey','Corecard Bulls'
UNION ALL SELECT 'Md Imran Khan','Corecard Bulls'
UNION ALL SELECT 'Md Quaiser Ali','Corecard Bulls'
UNION ALL SELECT 'Shivesh Soni','Corecard Bulls'
UNION ALL SELECT 'Devendra Bagdi','Corecard Bulls'
UNION ALL SELECT 'Anurag Soni','Corecard Bulls'
UNION ALL SELECT 'Ravindra Birla','Corecard Bulls'
UNION ALL SELECT 'Vinod Chouhan','Corecard Bulls'
UNION ALL SELECT 'Deepak Jain','DJ 11'
UNION ALL SELECT 'Deepak Dharkar','DJ 11'
UNION ALL SELECT 'Shivam Gangil','DJ 11'
UNION ALL SELECT 'Rohit Soni','DJ 11'
UNION ALL SELECT 'Sunil Rathore','DJ 11'
UNION ALL SELECT 'Ritik Jain','DJ 11'
UNION ALL SELECT 'Nitin Tripathi','DJ 11'
UNION ALL SELECT 'Sahid Sheikh','DJ 11'
UNION ALL SELECT 'Krishna Gupta','DJ 11'
UNION ALL SELECT 'Rajesh Sahu','DJ 11'
UNION ALL SELECT 'Ashish Jayaswal','DJ 11'
UNION ALL SELECT 'Arjun Dewda','DJ 11'
UNION ALL SELECT 'Monu Sahu','DJ 11'
UNION ALL SELECT 'Rahul Bhargava','DJ 11'
UNION ALL SELECT 'Vinod Prajapati','DJ 11'
UNION ALL SELECT 'Ankit Mitra','Uncapped'
UNION ALL SELECT 'Rahul Bhargava','Uncapped'
UNION ALL SELECT 'Deepesh Malviya','Uncapped'
UNION ALL SELECT 'Pratibha Mishra','Uncapped'
UNION ALL SELECT 'Ayush Jain','Uncapped'
UNION ALL SELECT 'Mayank Karn','Uncapped'
UNION ALL SELECT 'Swapnil Pathak','Uncapped'
UNION ALL SELECT 'Shubham Dubey','Uncapped'
UNION ALL SELECT 'Shivendra Shrivastava','Uncapped'
UNION ALL SELECT 'Dileep Patel','Uncapped'
UNION ALL SELECT 'Dhirendra Mishra','Uncapped'
UNION ALL SELECT 'Bharat Patel','Uncapped'
UNION ALL SELECT 'Anand Tiwari','Uncapped'
UNION ALL SELECT 'yogendra','Uncapped'
UNION ALL SELECT 'Manu Tripathi','Uncapped'
UNION ALL SELECT 'Arpit Sharma ','Uncapped'
UNION ALL SELECT 'Prashant Yadav','Uncapped'
UNION ALL SELECT 'Pramod Verma','Uncapped'
UNION ALL SELECT 'Adarsh Singh','Uncapped'
UNION ALL SELECT 'Aishwary Saxena','Uncapped'
UNION ALL SELECT 'Amit dwivedi ','Uncapped'
UNION ALL SELECT 'Deepak Prajapati','Uncapped'
UNION ALL SELECT 'Aman Agarwal','Uncapped'
UNION ALL SELECT 'Satya Prakash Vinayak','Uncapped'
UNION ALL SELECT 'Sanipini Surendra Chowdary','Uncapped'
UNION ALL SELECT 'vishakha kalkar','Uncapped'
UNION ALL SELECT 'jaykrishn pal','Uncapped'
UNION ALL SELECT 'Niklesh Vishwakarma','Uncapped'
UNION ALL SELECT 'Ronit lall','Uncapped'
UNION ALL SELECT 'GowthamSreeram Javvadi','Uncapped'
UNION ALL SELECT 'Aviral Singh Baghel','Uncapped'
UNION ALL SELECT 'Nayan Jain','Uncapped'
UNION ALL SELECT 'shifa khatoon','Uncapped'
UNION ALL SELECT 'Yograj Patel','Uncapped'
UNION ALL SELECT 'Sanjay Vishwakarma','Uncapped'
UNION ALL SELECT 'Ishwar Das','Uncapped'
UNION ALL SELECT 'Kumar Vaibhav','Uncapped'
UNION ALL SELECT 'Senki Baderiya','Uncapped'
UNION ALL SELECT 'Shakti Singh','Uncapped'
UNION ALL SELECT 'Shivendra Sharma','Uncapped'
UNION ALL SELECT 'Anmol Khantal','Uncapped'
UNION ALL SELECT 'Pramendra Kumar','Uncapped'
UNION ALL SELECT 'Manish Thakre','Uncapped'
UNION ALL SELECT 'Ankit Sahu','Uncapped'
UNION ALL SELECT 'shivam gangil','Uncapped'
UNION ALL SELECT 'AMIT MULMULE','Uncapped'
UNION ALL SELECT 'Pradeep Bhaydiya','Uncapped'
UNION ALL SELECT 'Tauseef Ahmad','Uncapped'
UNION ALL SELECT 'Shravan Kumar Chaurasia','Uncapped'
UNION ALL SELECT 'yogesh jain','Uncapped'
UNION ALL SELECT 'Sejal Lokwani ','Uncapped'
UNION ALL SELECT 'Sushant Kumar ','Uncapped'
UNION ALL SELECT 'Kajal Kumari','Uncapped'
UNION ALL SELECT 'GUNJAN JAIN','Uncapped'
UNION ALL SELECT 'Ankit Singh','Uncapped'
UNION ALL SELECT 'lalit tilwani','Uncapped'
UNION ALL SELECT 'Mohammad Anjum','Uncapped'
UNION ALL SELECT 'Sohail Ansari','Uncapped'
UNION ALL SELECT 'Sanjeet Meena','Uncapped'
UNION ALL SELECT 'Rahul Bajpai','Uncapped'
UNION ALL SELECT 'Pankaj Vishwakarma','Uncapped'
UNION ALL SELECT 'Akash Choudhary','Uncapped'
UNION ALL SELECT 'Pranjali Agrawal','Uncapped'
UNION ALL SELECT 'Manali Chourasia ','Uncapped'
UNION ALL SELECT 'Manoj Kumar Peswani','Uncapped'
UNION ALL SELECT 'Atul Sagar ','Uncapped'
UNION ALL SELECT 'Kshitij Bhatta','Uncapped'
UNION ALL SELECT 'Fiza','Uncapped'
UNION ALL SELECT 'Ashutosh Rathore','Uncapped'
UNION ALL SELECT 'Palak Jain','Uncapped'
UNION ALL SELECT 'Ravishri Jain','Uncapped'
UNION ALL SELECT 'Sonali Kumari Singh','Uncapped'
UNION ALL SELECT 'Shivesh Kumar Soni','Uncapped'
UNION ALL SELECT 'Dipesh Kulshrestha','Uncapped'
UNION ALL SELECT 'Ravi Prashant ','Uncapped'
UNION ALL SELECT 'Monu Sahu','Uncapped'
UNION ALL SELECT 'Gaurang Chaturvedi','Uncapped'
UNION ALL SELECT 'Ali Raza Khan','Uncapped'
UNION ALL SELECT 'Harsh Vishwakarma','Uncapped'
UNION ALL SELECT 'mohit','Uncapped'
UNION ALL SELECT 'Deepali Dhakar','Uncapped'
UNION ALL SELECT 'Tarun Kumar Mishra','Uncapped'
UNION ALL SELECT 'Aarti Sahu','Uncapped'
UNION ALL SELECT 'Manish Kumar Yadav','Uncapped'
UNION ALL SELECT 'surendra sanipini','Uncapped'
UNION ALL SELECT 'Kajal Saini','Uncapped'
UNION ALL SELECT 'Sunil Mishra','Uncapped'
UNION ALL SELECT 'Pooja Patidar','Uncapped'
UNION ALL SELECT 'Amreen Mateen','Uncapped'
UNION ALL SELECT 'Geetesh Pathak','Uncapped'
UNION ALL SELECT 'Shrikant Nair','Uncapped'
UNION ALL SELECT 'Ravishri Jain','Uncapped'
UNION ALL SELECT 'Diksha Pushpad','Uncapped'
UNION ALL SELECT 'Ganesh Sonwane','Uncapped'
UNION ALL SELECT 'Kunal Bakshi','Uncapped'
UNION ALL SELECT 'Pushpendra Singh Chouhan','Uncapped'
UNION ALL SELECT 'GowthamJavvadi ','Uncapped'
UNION ALL SELECT 'Abhay Tiwari','Uncapped'
UNION ALL SELECT 'Kiran mestyr','Uncapped'
UNION ALL SELECT 'Dhananjay Gaur','Uncapped'
UNION ALL SELECT 'ravi raj mishra','Uncapped'
UNION ALL SELECT 'Anurag soni','Uncapped'
UNION ALL SELECT 'samadhan','Uncapped'
UNION ALL SELECT 'Aniket Gawde','Uncapped'
UNION ALL SELECT 'Pratibha Mishra','Uncapped'
UNION ALL SELECT 'Kartik Khare','Uncapped'
UNION ALL SELECT 'Shivam Patel','Uncapped'
UNION ALL SELECT 'Sandip Barve','Uncapped'
UNION ALL SELECT 'Akshay Bijwe','Uncapped'
UNION ALL SELECT 'Mohd Saif Ansari ','Uncapped'
UNION ALL SELECT 'Reetesh Sharma','Uncapped'
UNION ALL SELECT 'Ali Raza Khan','Uncapped'
UNION ALL SELECT 'Tasha Ansar','Uncapped'
UNION ALL SELECT 'Mohd Saif Ansari','Uncapped'
UNION ALL SELECT 'Ankit Yadav','Uncapped'
UNION ALL SELECT 'Prasoon Parashar','Uncapped'
UNION ALL SELECT 'Manish Kumar','Uncapped'
UNION ALL SELECT 'Sitendra Kada','Uncapped'
UNION ALL SELECT 'Ankit Singh','Uncapped'
UNION ALL SELECT 'Ankit Dongre','Uncapped'
UNION ALL SELECT 'Ankit Sharma','Uncapped'
UNION ALL SELECT 'Jitendra Lakhawat','Uncapped'
UNION ALL SELECT 'Vikas Rajani','Uncapped'
UNION ALL SELECT 'Nikita Raghuwanshi','Uncapped'
UNION ALL SELECT 'Sachin Kumar Silawat','Uncapped'
UNION ALL SELECT 'shubham singhai','Uncapped'
UNION ALL SELECT 'Gourav Bose','Uncapped'
UNION ALL SELECT 'Lakush Rajput','Uncapped'
UNION ALL SELECT 'Ajay Nigam','Uncapped'
UNION ALL SELECT 'Ashutosh Singh','Uncapped'
UNION ALL SELECT 'Chirag Kushwaha','Uncapped'
UNION ALL SELECT 'Pankaj Bhargava','Uncapped'
UNION ALL SELECT 'Rohit Soni','Uncapped'
UNION ALL SELECT 'Amandeep SaHU','Uncapped'
UNION ALL SELECT 'Vineet Shrivas','Uncapped'
UNION ALL SELECT 'Yogesh Kumar Choudhary','Uncapped'
UNION ALL SELECT 'Kapil Kumar Gangrade','Uncapped'
UNION ALL SELECT 'Jinendra Prakash Jain','Uncapped'
UNION ALL SELECT 'Aakash Tiwari','Uncapped'
UNION ALL SELECT 'Lokendra Battu','Uncapped'
UNION ALL SELECT 'Lakshya Kumawat','Uncapped'
UNION ALL SELECT 'Pradhumn Jain','Uncapped'
UNION ALL SELECT 'Kajal Kumari','Uncapped'
UNION ALL SELECT 'surendra sanipini','Uncapped'
UNION ALL SELECT 'Anurag Jain','Uncapped'
UNION ALL SELECT 'Pratibha Mishra','Uncapped'
UNION ALL SELECT 'Pranjali Agrawal','Uncapped'
UNION ALL SELECT 'ronit lall','Uncapped'
UNION ALL SELECT 'sarajit mondal','Uncapped'
UNION ALL SELECT 'Rishabh Bajpai','Uncapped'
UNION ALL SELECT 'Siddhi','Uncapped'
UNION ALL SELECT 'kamlesh','Uncapped'
UNION ALL SELECT 'Tara Shrivastava','Uncapped'
UNION ALL SELECT 'Hitesh Bhawsar','Uncapped'
UNION ALL SELECT 'Dilip Dixit','Uncapped'
UNION ALL SELECT 'George Dcruz','Uncapped'
UNION ALL SELECT 'Amit Mishra','Uncapped'
UNION ALL SELECT 'Abhay Asthana','Uncapped'
UNION ALL SELECT 'Ankit Dongre','Uncapped'
UNION ALL SELECT 'Umakant Shukla','Uncapped'
UNION ALL SELECT 'Kumar Vaibhav','Uncapped'
UNION ALL SELECT 'Kshitij Mishra','Uncapped'
UNION ALL SELECT 'Vidushi Shrivastava','Uncapped'
UNION ALL SELECT 'Chetan Deshmukh','Uncapped'
UNION ALL SELECT 'Ankita Shukla','Uncapped'
UNION ALL SELECT 'Ankita Shukla','Uncapped'
UNION ALL SELECT 'Deepak Kumar','Uncapped'
UNION ALL SELECT 'Rishi Raj Singh','Uncapped'
UNION ALL SELECT 'Pratiksha Meena','Uncapped'
UNION ALL SELECT 'Navendu Singh','Uncapped'
UNION ALL SELECT 'MD IMRAN KHAN','Uncapped'
UNION ALL SELECT 'Vinod Kumar Chouhan','Uncapped'
UNION ALL SELECT 'Sandeep Sharma','Uncapped'
UNION ALL SELECT 'Samarth Shrivastava','Uncapped'
UNION ALL SELECT 'Ashish sharma','Uncapped'
UNION ALL SELECT 'Sumika Dubey','Uncapped'
UNION ALL SELECT 'Arg Jain','Uncapped'
UNION ALL SELECT 'ronit lall','Uncapped'
UNION ALL SELECT 'ronit lall','Uncapped'
UNION ALL SELECT 'Prateek Dhimole','Uncapped'
UNION ALL SELECT 'Amit Sharma','Uncapped'
UNION ALL SELECT 'Azmat  ','Uncapped'
UNION ALL SELECT 'Nitin','Uncapped'
UNION ALL SELECT 'Vishnu Raghuvanshi','Uncapped'
UNION ALL SELECT 'Manali singh sengar','Uncapped'
UNION ALL SELECT 'Ritik vardhan jain','Uncapped'
UNION ALL SELECT 'aafreen','Uncapped'
UNION ALL SELECT 'Rashmi Billore','Uncapped'
UNION ALL SELECT 'Nikita Raghuwanshi','Uncapped'
UNION ALL SELECT 'Sana Khan','Uncapped'
UNION ALL SELECT 'Diksha Pushpad','Uncapped'
UNION ALL SELECT 'Abhishek Mehar','Uncapped'
UNION ALL SELECT 'Rahul Singh Baghe','Uncapped'
UNION ALL SELECT 'shifa khatoon','Uncapped'
UNION ALL SELECT 'abhishek asati','Uncapped'
UNION ALL SELECT 'Vishnu Raghuvanshi','Uncapped'
UNION ALL SELECT 'Akash Thaware','Uncapped'
UNION ALL SELECT 'Azmat ','Uncapped'
UNION ALL SELECT 'Mohit Tripathi','Uncapped'
UNION ALL SELECT 'Srijan Jain','Uncapped'
UNION ALL SELECT 'Ranveer Thakur','Uncapped'
UNION ALL SELECT 'Abhinav Gour','Uncapped'
UNION ALL SELECT 'shifa khatoon','Uncapped'
UNION ALL SELECT 'Vinay katoch','Uncapped'
UNION ALL SELECT 'Vinay katoch','Uncapped'
UNION ALL SELECT 'Abhilash Kaimal','Uncapped'
UNION ALL SELECT 'Rajat Sharma','Uncapped'
UNION ALL SELECT 'Divyanshu Singh','Uncapped'
UNION ALL SELECT 'Punit Sahu','Uncapped'
UNION ALL SELECT 'Vicky Soni','Uncapped'
UNION ALL SELECT 'Raj Gupta','Uncapped'
UNION ALL SELECT 'Nikhil Badoni','Uncapped'
UNION ALL SELECT 'Akash Mourya','Uncapped'
UNION ALL SELECT 'Ajay Rajput','Uncapped'
UNION ALL SELECT 'NAMRATA BULCHANDANI','Uncapped'
UNION ALL SELECT 'Malaika Shrivastava','Uncapped'
UNION ALL SELECT 'Gourav Bansal','Uncapped'
UNION ALL SELECT 'Rajesh Sahu','Uncapped'
UNION ALL SELECT 'Ajay Sharma','Uncapped'
UNION ALL SELECT 'Atul Sagar ','Uncapped'
UNION ALL SELECT 'Gaurav khanwalkar','Uncapped'
UNION ALL SELECT 'Himanshu Patel','Uncapped'
UNION ALL SELECT 'Shivam Dubey','Uncapped'
UNION ALL SELECT 'Lovelesh Thalani','Uncapped'
UNION ALL SELECT 'Pankaj Bhagwani','Uncapped'
UNION ALL SELECT 'Harshit Mittal','Uncapped'
UNION ALL SELECT 'Raghvendra Rajak','Uncapped'
UNION ALL SELECT 'Anshu Kumari ','Uncapped'
UNION ALL SELECT 'Shikha Jain','Uncapped'
UNION ALL SELECT 'Aman Mehta','Uncapped'
UNION ALL SELECT 'Prabhat Soni','Uncapped'
UNION ALL SELECT 'Swarna chouksey','Uncapped'
UNION ALL SELECT 'Sant Kumar Yadav ','Uncapped'
UNION ALL SELECT 'Ajay Mewada','Uncapped'
UNION ALL SELECT 'Ritik Sharma','Uncapped'
UNION ALL SELECT 'Vipin Baghel','Uncapped'
UNION ALL SELECT 'Ritik Sharma','Uncapped'
UNION ALL SELECT 'Rahul Sahu','Uncapped'
UNION ALL SELECT 'Rishika Soni','Uncapped'
UNION ALL SELECT 'Amit Kumar Pandit','Uncapped'
UNION ALL SELECT 'Amit Pandit','Uncapped'
UNION ALL SELECT 'Amit Pandit','Uncapped'
UNION ALL SELECT 'Tarun Singh Bais','Uncapped'
UNION ALL SELECT 'Santosh Mishra','Uncapped'
UNION ALL SELECT 'Gourav Chouksey','Uncapped'
UNION ALL SELECT 'Shivam Kushwah','Uncapped'
UNION ALL SELECT 'Gourav Chouksey','Uncapped'
UNION ALL SELECT 'Pratibha Mishra','Uncapped'
UNION ALL SELECT 'Tarun Kumar Geed','Uncapped'
UNION ALL SELECT 'Manoj Kumar Peswani','Uncapped'
UNION ALL SELECT 'Pradeep Bhaydiya','Uncapped'
UNION ALL SELECT 'Radha Raman Shama','Uncapped'
UNION ALL SELECT 'Divyanshi Gugliya','Uncapped'
UNION ALL SELECT 'Kalidindi Veerabhadrarao','Uncapped'
UNION ALL SELECT 'Nitin Tripathi','Uncapped'
UNION ALL SELECT 'Prakhar Nigam ','Uncapped'
UNION ALL SELECT 'Tanya saxena','Uncapped'
UNION ALL SELECT 'Amit dhakar','Uncapped'
UNION ALL SELECT 'Shakti Singh Tomar','Uncapped'
UNION ALL SELECT 'Rudrajeet Bhattacharya','Uncapped'
UNION ALL SELECT 'Ajay Bhaiya (canteen)','Uncapped'
UNION ALL SELECT 'Raj Kishor Rawat','Dark Horse A'
UNION ALL SELECT 'Kumar Vaibhav','Dark Horse A'
UNION ALL SELECT 'Jaihind Rajput','Dark Horse A'
UNION ALL SELECT 'Alin Awasthi','Dark Horse A'
UNION ALL SELECT 'Vinay Katoch','Dark Horse A'
UNION ALL SELECT 'Manish Thakre','Dark Horse A'
UNION ALL SELECT 'Prabhat Soni','Dark Horse A'
UNION ALL SELECT 'Gaurang Chaturvedi','Dark Horse A'
UNION ALL SELECT 'Gourav Sharma','Dark Horse A'
UNION ALL SELECT 'Shivam Tiwari','Dark Horse A'
UNION ALL SELECT 'Vishal Makode','Dark Horse A'
UNION ALL SELECT 'Harsh Vishwakarma','Dark Horse A'
UNION ALL SELECT 'Manoj Peswani','Dark Horse A'
UNION ALL SELECT 'Manish Gupta','Dark Horse A'
UNION ALL SELECT 'Vivek Sharma','Dark Horse A'
UNION ALL SELECT 'Vineet Shrivas','Dark Horse B'
UNION ALL SELECT 'Kshitij Bhatt','Dark Horse B'
UNION ALL SELECT 'Badal Kushwaha','Dark Horse B'
UNION ALL SELECT 'Deepak Kumar','Dark Horse B'
UNION ALL SELECT 'Arpit Sharma','Dark Horse B'
UNION ALL SELECT 'Adarsh patel','Dark Horse B'
UNION ALL SELECT 'Puspendra Kumar','Dark Horse B'
UNION ALL SELECT 'Senki Baderiya','Dark Horse B'
UNION ALL SELECT 'Abhay Asthana','Dark Horse B'
UNION ALL SELECT 'Pritam Bake','Dark Horse B'
UNION ALL SELECT 'Lavish Patel','Dark Horse B'
UNION ALL SELECT 'Aariz Akhtar','Dark Horse B'
UNION ALL SELECT 'Amit Dwivedi','Dark Horse B'
UNION ALL SELECT 'Vivek Tiwari','Dark Horse B'
UNION ALL SELECT 'Hirendra Singh Rajput','Dark Horse B'