IF NOT EXISTS ( SELECT TOP 1 1 FROM USERINFORMATION WITH(NOLOCK) WHERE USRID = 'svcUpdateCreditBureauReporting' AND USRTYPE = '4')
	BEGIN 
		INSERT INTO  USERINFORMATION(USRID,USRINFO1,USRTYPE,USRERNLOGIN,USRSTATUS) VALUES('svcUpdateCreditBureauReporting','appCardinal','4','0','0')
	END
GO