--SELECT acctID, TranTime, TranID, ROW_NUMBER() OVER (PARTITION BY NULL ORDER BY TranTime)  [Row]
--FROM CommonAP WITH (NOLOCK) 
--WHERE acctID = 1290188 AND TranID > 0

SELECT acctID, COUNT(1) FROm CommonAP WITH (NOLOCK) WHERE acctID IN (1264223) GROUP BY acctID

SELECT acctID, COUNT(1) FROm ErrorAP WITH (NOLOCK) WHERE acctID IN (1264223) GROUP BY acctID


--SELECT * FROm CommonAP WITH (NOLOCK) WHERE acctID = 2246270 ORDER BY TranTIME
--SELECT * FROm CommonAP WITH (NOLOCK) WHERE acctID = 2436874 ORDER BY TranTIME
--SELECT * FROm ErrorAP WITH (NOLOCK) WHERE acctID = 2436874 ORDER BY TranTIME
--SELECT * FROm PurchaseReversalRecord WITH (NOLOCK) WHERE parent02AID = 2246270
--SELECT * FROm CCard_Primary WITH (NOLOCK) WHERE TranID = 69004173769
--2436874
--2246270
--18438243

DECLARE @CurrentTime DATETIME = DATEADD(MINUTE, 3, GETDATE()), @acctID INT

SET @acctID = 1264223

;WITH CTE
AS
(
SELECT acctID, @CurrentTime TranTime, TranID, ROW_NUMBER() OVER (PARTITION BY NULL ORDER BY TranTime)  [Row]
FROM CommonAP WITH (NOLOCK) 
WHERE acctID = @acctID AND TranID > 0
)
, CCARD AS
(
SELECT CP.TranID, CP.TranTime, CP.PostTime, C.TranTime TNPTime, [Row],
CASE WHEN CP.TranTime < CP.PostTime THEN 0 ELSE 1 END AS TransactionType
FROM CCard_Primary CP WITH (NOLOCK)
JOIN CTE C ON (CP.TranID = C.TranID)
)
SELECT *, DATEADD(MINUTE, [Row]*3, TNPTime) NewTime,
CASE WHEN TransactionType = 0 THEN 
'UPDATE TOP(1) CCard_Primary SET PostTime = ''' + TRY_CONVERT(VARCHAR(20), DATEADD(MINUTE, [Row]*3, TNPTime), 20) + ''' WHERE TranID = ' + TRY_CAST(TranID AS VARCHAR)
ELSE 
'UPDATE TOP(1) CCard_Primary SET TranTime = ''' + TRY_CONVERT(VARCHAR(20), DATEADD(MINUTE, [Row]*3, TNPTime), 20) + ''', PostTime = ''' + TRY_CONVERT(VARCHAR(20), DATEADD(MINUTE, [Row]*3, TNPTime), 20) + ''' WHERE TranID = ' + TRY_CAST(TranID AS VARCHAR)
END AS CCardResult,
'UPDATE TOP(1) CommonAP SET TranTime = ''' + TRY_CONVERT(VARCHAR(20), DATEADD(MINUTE, [Row]*3, TNPTime), 20) + ''' WHERE TranID = ' + TRY_CAST(TranID AS VARCHAR)
FROM CCARD

