SELECT COUNT(1) FROM CCard_Primary WITH (NOLOCK)
SELECT COUNT(1) FROM CCard_Primary_Fix WITH (NOLOCK)
SELECT COUNT(1) FROM ccardTransactionMC WITH (NOLOCK)
SELECT COUNT(1) FROM CBLog WITH (NOLOCK)
SELECT COUNT(1) FROM CurrentBalanceAudit WITH (NOLOCK)
SELECT COUNT(1) FROM CurrentBalanceAuditPS WITH (NOLOCK)
SELECT COUNT(1) FROM Trans_In_Acct WITH (NOLOCK)
SELECT COUNT(1) FROM ILPScheduleDetails WITH (NOLOCK)
SELECT COUNT(1) FROM ILPScheduleDetailsRevised WITH (NOLOCK)
SELECT COUNT(1) FROM LogArTxnAddl WITH (NOLOCK)

SELECT COUNT(1) FROM ILPScheduleDetails_Activity WITH (NOLOCK)
SELECT COUNT(1) FROM ILPScheduleDetailsRevised_Activity WITH (NOLOCK)
SELECT COUNT(1) FROM ILPScheduleDetailSummary_Activity WITH (NOLOCK)


--SELECt 4263754+553285