-- TO BE RUN ON PRIMARY SERVER ONLY

USE CCGS_CoreIssue
GO

BEGIN TRANSACTION

	UPDATE CCard_Primary SET PostingRef = 'Transaction posted successfully', ArTxnType = '91' WHERE TranID IN (29175432180)
	-- 1 row

	UPDATE LogArTxnAddl SET ExcludeFlag = 1 WHERE TranID IN (29175432180) AND ArTxnType = '93'
	-- 1 row

COMMIT TRANSACTION
--ROLLBACK TRANSACTION

/*
VALIDATION

SELECT ExcludeFlag, * FROM LogArTxnAddl WITH (NOLOCK) WHERE TranID IN (29175432180) AND ArTxnType = '93'

SELECT PostingRef,ArTxnType,* FROM CCard_Primary WITH (NOLOCK) WHERE TranID IN (29175432180)

*/