
DECLARE @TotalTxns INT = 0, @CreatedTxns INT = 0, @PostedTxns INT = 0, @JiraID VARCHAR(50)

SET @JiraID = 'COOKIE-257478'

BEGIN TRY
		SELECT @TotalTxns = COUNT(1) FROM COOKIE_257478_ChargeOffAccount WITH (NOLOCK)

		DROP TABLE IF EXISTS #TempTxns
		SELECT TranID, TransactionStatus
		INTO #TempTxns
		FROM CreateNewSingleTransactionData WITH (NOLOCK)
		WHERE Reason = @JiraID

		SELECT @CreatedTxns = COUNT(1) FROM #TempTxns WITH (NOLOCK) WHERE TransactionStatus = 2

		IF(@TotalTxns = @CreatedTxns)
		BEGIN
			SELECT @PostedTxns = COUNT(1)
			FROM Trans_In_Acct WITH (NOLOCK)
			WHERE tran_id_index IN 
			(
				SELECT TranID
				FROM #TempTxns
				WHERE TransactionStatus = 2
			)
			AND ATID = 51

			IF(@CreatedTxns = @PostedTxns)
			BEGIN
				BEGIN TRANSACTION
					UPDATE COOKIE_257478_ChargeOffAccount SET JobStatus = 1
					SELECT 'ALL TRANSACTIONS HAVE BEEN POSTED SUCCESSFULLY, MOVING AHEAD' [RESULT]
				COMMIT TRANSACTION
			END
			ELSE
			BEGIN
				SELECT 'ALL TRANSACTION HAVE NOT BEEN POSTED OR JOBS IN ERROR, PLEASE CHECK ERRORJOBS OR TRY AFTER SOMETIME' [RESULT]
			END
	
		END
		ELSE
		BEGIN
			SELECT 'ISSUE IN CREATING TRANSACTION, CANNOT MOVE AHEAD' [RESULT]
		END		
END TRY
BEGIN CATCH
	IF @@TRANCOUNT > 0
		ROLLBACK TRANSACTION 
		SELECT ERROR_MESSAGE(),ERROR_LINE(),ERROR_NUMBER()
		RAISERROR('ERROR OCCURED :-', 16, 1);
END CATCH