IF NOT EXISTS (SELECT 1 FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'DBO.TransactionCreationTempData') AND NAME = 'RevTgt')
BEGIN
	ALTER TABLE DBO.TransactionCreationTempData ADD RevTgt DECIMAL(19,0) NULL
END

IF NOT EXISTS (SELECT 1 FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'DBO.TransactionCreationTempData') AND NAME = 'JiraID')
BEGIN
	ALTER TABLE DBO.TransactionCreationTempData ADD JiraID VARCHAR(20) NULL
END