-- TO BE RUN ON PRIMARY SERVER ONLY

USE CCGS_CoreIssue
GO

BEGIN TRANSACTION

	UPDATE CCard_Primary SET PostingRef = 'Transaction posted successfully', ArTxnType = '91' WHERE TranID = 28966120777
	-- 1 row

	UPDATE LogArTxnAddl SET ExcludeFlag = 1 WHERE TranID = 28966120777 AND ArTxnType = '93'
	-- 1 row

COMMIT TRANSACTION
--ROLLBACK TRANSACTION

/*
VALIDATION

SELECT ExcludeFlag, * FROM LogArTxnAddl WITH (NOLOCK) WHERE TranID = 28966120777 AND ArTxnType = '93'

SELECT PostingRef,ArTxnType,* FROM CCard_Primary WITH (NOLOCK) WHERE TranID = 28966120777

*/