
BEGIN TRAN
--COMMIT TRAN
--ROLLBACK TRAN

INSERT INTO [ILPScheduleDetails]
           ([acctId]
           ,[parent02AID]
           ,[cpsinterestplan]
           ,[InterestRate1]
           ,[PMTPaymentamount]
           ,[BestPaymentAmount]
           ,[Dailyfactor]
           ,[LoanDate]
           ,[Iteration]
           ,[LoanTerm]
           ,[LastStatementDate]
           ,[DateOfNextStmt]
           ,[DayswithoutPayment]
           ,[DayswithPayment]
           ,[DaysInCycle]
           ,[IntwithoutPayment]
           ,[IntwithPayment]
           ,[TotalInt]
           ,[BSFC]
           ,[InterestOnInterest]
           ,[ILPScheduleType]
           ,[GraceDayStatus]
           ,[WaiveInterest]
           ,[RegularPaymentAmountforIteration]
           ,[StatementDate]
           ,[DateOfTotalDue]
           ,[CurrentBalance]
           ,[OriginalLoanTerm]
           ,[OriginalLoanEndDate]
           ,[OriginalLoanAmount]
           ,[RemainingPrincipal]
           ,[PrincipalBilledCTD]
           ,[AuthTranId]
           ,[ScheduleIndicator]
           ,[LoanEndDate]
           ,[ScheduleID]
           ,[Skey]
           ,[IsDeferCycle])

SELECT 
			[acctId]
           ,[parent02AID]
           ,[cpsinterestplan]
           ,[InterestRate1]
           ,[PMTPaymentamount]
           ,[BestPaymentAmount]
           ,[Dailyfactor]
           ,[LoanDate]
           ,[Iteration]
           ,[LoanTerm]
           ,[LastStatementDate]
           ,[DateOfNextStmt]
           ,[DayswithoutPayment]
           ,[DayswithPayment]
           ,[DaysInCycle]
           ,[IntwithoutPayment]
           ,[IntwithPayment]
           ,[TotalInt]
           ,[BSFC]
           ,[InterestOnInterest]
           ,[ILPScheduleType]
           ,[GraceDayStatus]
           ,[WaiveInterest]
           ,[RegularPaymentAmountforIteration]
           ,[StatementDate]
           ,[DateOfTotalDue]
           ,[CurrentBalance]
           ,[OriginalLoanTerm]
           ,[OriginalLoanEndDate]
           ,[OriginalLoanAmount]
           ,[RemainingPrincipal]
           ,[PrincipalBilledCTD]
           ,[AuthTranId]
           ,[ScheduleIndicator]
           ,[LoanEndDate]
           ,[ScheduleID]
           ,[Skey]
           ,[IsDeferCycle]
FROM TempILPScheduleDetails
     


