/**********************************************************************************************************************
Purpose								: PLAT-259458
Author								: Prasoon Parashar
Date									: 09/08/2025
Application version					: Plat_25.10.3
Description							: Enhance high balance calculation logic
Review By							: Deepak Dharkar 
**********************************************************************************************************************/

CREATE OR ALTER PROCEDURE sp_Org_Balances_qsel(  @acctId int ) AS
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET QUOTED_IDENTIFIER ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;
SELECT
 [acctId],
 [AmountOfDebitsDM1],
 [NumberOfDebitsDM1],
 [AmountOfCreditsDM1],
 [NumberOfCreditsDM1],
 [AmtGenDebitsDD1],
 [AmtGenCreditsDD1],
 [NbrGenDebitsDD1],
 [NbrGenCreditsDD1],
 [TotAmtCashPurAuthReqDD1],
 [TotAmtCashPurAuthReqDD2],
 [TotAmtCashPurAuthReqDD3],
 [TotNoCashPurAuthReqDD1],
 [TotNoCashPurAuthReqDD2],
 [TotNoCashPurAuthReqDD3],
 [PeriodPrefix],
 [ARSystemAcctId],
 [TimeZone],
 [DayLightSaving],
 [ProcessingDayEndTime],
 [CBRPortfolioType],
 [CBRAccountType],
 [PreferredLanguage],
 [CMTransactionHistoryUpto],
 [CMTransactionHistoryUpRange],
 [ACHCutoffTime],
 [NoOfTxnInACHFile],
 [SSRegistrationMethod],
 [SSForgetPasswordMethod],
 [SSForgetUserIDMethod],
 [SSDisputeAllowed],
 [ccinhparent136AID],
 [ccinhparent136ATID],
 [ccinhparent137AID],
 [ccinhparent137ATID],
 [ccinhparent138AID],
 [ccinhparent138ATID],
 [ccinhparent139AID],
 [ccinhparent139ATID],
 [ccinhparent140AID],
 [ccinhparent140ATID],
 [ccinhparent141AID],
 [ccinhparent141ATID],
 [ccinhparent142AID],
 [ccinhparent142ATID],
 [ccinhparent143AID],
 [ccinhparent143ATID],
 [ccinhparent144AID],
 [ccinhparent144ATID],
 [ccinhparent145AID],
 [ccinhparent145ATID],
 [ccinhparent146AID],
 [ccinhparent146ATID],
 [ccinhparent147AID],
 [ccinhparent147ATID],
 [BankVerificationMethod],
 [CEDAlignment],
 [CompanyEntryDescription],
 [CompanyID],
 [CompanyName],
 [CompanyNameAlignment],
 [ECCAlignment],
 [EntryClassCode],
 [CompanyIdAlignment],
 [DestinationAlignment],
 [DestinationRTAlignment],
 [OriginationAlignment],
 [TINAlignment],
 [DEKEncryptionRequired],
 [DEKEncryptionKey],
 [RefundDescription],
 [BillPayOriginatorsRFIID],
 [BillPayDestinationName],
 [HolidayConsideration],
 [AccountNumberGeneration],
 [AccountNumberPrefix],
 [AccountNumberPostValue],
 [WellsFargoBankABA],
 [WellsFargoBankName],
 [PreQual],
 [ChargeAssmtFee],
 [MerchantTaxIdentificationNumber],
 [CompanyNameCCD],
 [CompanyIdCCD],
 [CompanyEntryDescCCDDebit],
 [CompanyEntryDescCCDCredit],
 [DestRoutingTransitRefund],
 [ACHIdRefund],
 [OrigRoutingTransitRefund],
 [CompanyIdRefund],
 [DestRoutingTransitReward],
 [ACHIdReward],
 [OrigRoutingTransitReward],
 [CompanyIdReward],
 [ACHFileContent],
 [PODID],
 [SysSubOrgID],
 [StmtCTDCombination],
 [StmtEODCombination],
 [ProgramIdSBFE],
 [BDCInDueDate],
 [BDCInLateFeeDate],
 [MiniPodID],
 [BackdatedPymtConsideration],
 [BackdatedPymtConsiderationTime],
 [Sharding],
 [MiniPODNumber],
 [AsynchronousPosting],
 [HighBalanceRecalculation],
 [PHPCalculationLogicOn],
 [PartnerName],
 [EODDataApproach],
 [RealTimePostingDuringEOM],
 [NewTNPQueue],
 [CBRFrequency],
 [CBRDataFrom],
 [CBRWeeklyPeriod],
 [CBREventReporting],
 [CBRHonourStatus],
 [CBRUpdateCCC],
 [CBRPaymentMade],
 [CBRUpdateSCC],
 [CBRUpdateCII],
 [CBRUpdateBillngCycle],
 [TSDBOActive],
 [TSDBOAllowedMonths],
 [TSDBOActiveDate]
FROM Org_Balances
WHERE 
   [acctId] = @acctId 
GO

CREATE OR ALTER PROCEDURE sp_Org_Balances_qslk(  @acctId int ) AS
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET QUOTED_IDENTIFIER ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;
SELECT
 [acctId],
 [AmountOfDebitsDM1],
 [NumberOfDebitsDM1],
 [AmountOfCreditsDM1],
 [NumberOfCreditsDM1],
 [AmtGenDebitsDD1],
 [AmtGenCreditsDD1],
 [NbrGenDebitsDD1],
 [NbrGenCreditsDD1],
 [TotAmtCashPurAuthReqDD1],
 [TotAmtCashPurAuthReqDD2],
 [TotAmtCashPurAuthReqDD3],
 [TotNoCashPurAuthReqDD1],
 [TotNoCashPurAuthReqDD2],
 [TotNoCashPurAuthReqDD3],
 [PeriodPrefix],
 [ARSystemAcctId],
 [TimeZone],
 [DayLightSaving],
 [ProcessingDayEndTime],
 [CBRPortfolioType],
 [CBRAccountType],
 [PreferredLanguage],
 [CMTransactionHistoryUpto],
 [CMTransactionHistoryUpRange],
 [ACHCutoffTime],
 [NoOfTxnInACHFile],
 [SSRegistrationMethod],
 [SSForgetPasswordMethod],
 [SSForgetUserIDMethod],
 [SSDisputeAllowed],
 [ccinhparent136AID],
 [ccinhparent136ATID],
 [ccinhparent137AID],
 [ccinhparent137ATID],
 [ccinhparent138AID],
 [ccinhparent138ATID],
 [ccinhparent139AID],
 [ccinhparent139ATID],
 [ccinhparent140AID],
 [ccinhparent140ATID],
 [ccinhparent141AID],
 [ccinhparent141ATID],
 [ccinhparent142AID],
 [ccinhparent142ATID],
 [ccinhparent143AID],
 [ccinhparent143ATID],
 [ccinhparent144AID],
 [ccinhparent144ATID],
 [ccinhparent145AID],
 [ccinhparent145ATID],
 [ccinhparent146AID],
 [ccinhparent146ATID],
 [ccinhparent147AID],
 [ccinhparent147ATID],
 [BankVerificationMethod],
 [CEDAlignment],
 [CompanyEntryDescription],
 [CompanyID],
 [CompanyName],
 [CompanyNameAlignment],
 [ECCAlignment],
 [EntryClassCode],
 [CompanyIdAlignment],
 [DestinationAlignment],
 [DestinationRTAlignment],
 [OriginationAlignment],
 [TINAlignment],
 [DEKEncryptionRequired],
 [DEKEncryptionKey],
 [RefundDescription],
 [BillPayOriginatorsRFIID],
 [BillPayDestinationName],
 [HolidayConsideration],
 [AccountNumberGeneration],
 [AccountNumberPrefix],
 [AccountNumberPostValue],
 [WellsFargoBankABA],
 [WellsFargoBankName],
 [PreQual],
 [ChargeAssmtFee],
 [MerchantTaxIdentificationNumber],
 [CompanyNameCCD],
 [CompanyIdCCD],
 [CompanyEntryDescCCDDebit],
 [CompanyEntryDescCCDCredit],
 [DestRoutingTransitRefund],
 [ACHIdRefund],
 [OrigRoutingTransitRefund],
 [CompanyIdRefund],
 [DestRoutingTransitReward],
 [ACHIdReward],
 [OrigRoutingTransitReward],
 [CompanyIdReward],
 [ACHFileContent],
 [PODID],
 [SysSubOrgID],
 [StmtCTDCombination],
 [StmtEODCombination],
 [ProgramIdSBFE],
 [BDCInDueDate],
 [BDCInLateFeeDate],
 [MiniPodID],
 [BackdatedPymtConsideration],
 [BackdatedPymtConsiderationTime],
 [Sharding],
 [MiniPODNumber],
 [AsynchronousPosting],
 [HighBalanceRecalculation],
 [PHPCalculationLogicOn],
 [PartnerName],
 [EODDataApproach],
 [RealTimePostingDuringEOM],
 [NewTNPQueue],
 [CBRFrequency],
 [CBRDataFrom],
 [CBRWeeklyPeriod],
 [CBREventReporting],
 [CBRHonourStatus],
 [CBRUpdateCCC],
 [CBRPaymentMade],
 [CBRUpdateSCC],
 [CBRUpdateCII],
 [CBRUpdateBillngCycle],
 [TSDBOActive],
 [TSDBOAllowedMonths],
 [TSDBOActiveDate]
FROM Org_Balances with (updlock)
WHERE 
   [acctId] = @acctId 
GO

CREATE OR ALTER PROCEDURE sp_Org_Balances_sel AS
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET QUOTED_IDENTIFIER ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;

SELECT [acctId],
 [AmountOfDebitsDM1],
 [NumberOfDebitsDM1],
 [AmountOfCreditsDM1],
 [NumberOfCreditsDM1],
 [AmtGenDebitsDD1],
 [AmtGenCreditsDD1],
 [NbrGenDebitsDD1],
 [NbrGenCreditsDD1],
 [TotAmtCashPurAuthReqDD1],
 [TotAmtCashPurAuthReqDD2],
 [TotAmtCashPurAuthReqDD3],
 [TotNoCashPurAuthReqDD1],
 [TotNoCashPurAuthReqDD2],
 [TotNoCashPurAuthReqDD3],
 [PeriodPrefix],
 [ARSystemAcctId],
 [TimeZone],
 [DayLightSaving],
 [ProcessingDayEndTime],
 [CBRPortfolioType],
 [CBRAccountType],
 [PreferredLanguage],
 [CMTransactionHistoryUpto],
 [CMTransactionHistoryUpRange],
 [ACHCutoffTime],
 [NoOfTxnInACHFile],
 [SSRegistrationMethod],
 [SSForgetPasswordMethod],
 [SSForgetUserIDMethod],
 [SSDisputeAllowed],
 [ccinhparent136AID],
 [ccinhparent136ATID],
 [ccinhparent137AID],
 [ccinhparent137ATID],
 [ccinhparent138AID],
 [ccinhparent138ATID],
 [ccinhparent139AID],
 [ccinhparent139ATID],
 [ccinhparent140AID],
 [ccinhparent140ATID],
 [ccinhparent141AID],
 [ccinhparent141ATID],
 [ccinhparent142AID],
 [ccinhparent142ATID],
 [ccinhparent143AID],
 [ccinhparent143ATID],
 [ccinhparent144AID],
 [ccinhparent144ATID],
 [ccinhparent145AID],
 [ccinhparent145ATID],
 [ccinhparent146AID],
 [ccinhparent146ATID],
 [ccinhparent147AID],
 [ccinhparent147ATID],
 [BankVerificationMethod],
 [CEDAlignment],
 [CompanyEntryDescription],
 [CompanyID],
 [CompanyName],
 [CompanyNameAlignment],
 [ECCAlignment],
 [EntryClassCode],
 [CompanyIdAlignment],
 [DestinationAlignment],
 [DestinationRTAlignment],
 [OriginationAlignment],
 [TINAlignment],
 [DEKEncryptionRequired],
 [DEKEncryptionKey],
 [RefundDescription],
 [BillPayOriginatorsRFIID],
 [BillPayDestinationName],
 [HolidayConsideration],
 [AccountNumberGeneration],
 [AccountNumberPrefix],
 [AccountNumberPostValue],
 [WellsFargoBankABA],
 [WellsFargoBankName],
 [PreQual],
 [ChargeAssmtFee],
 [MerchantTaxIdentificationNumber],
 [CompanyNameCCD],
 [CompanyIdCCD],
 [CompanyEntryDescCCDDebit],
 [CompanyEntryDescCCDCredit],
 [DestRoutingTransitRefund],
 [ACHIdRefund],
 [OrigRoutingTransitRefund],
 [CompanyIdRefund],
 [DestRoutingTransitReward],
 [ACHIdReward],
 [OrigRoutingTransitReward],
 [CompanyIdReward],
 [ACHFileContent],
 [PODID],
 [SysSubOrgID],
 [StmtCTDCombination],
 [StmtEODCombination],
 [ProgramIdSBFE],
 [BDCInDueDate],
 [BDCInLateFeeDate],
 [MiniPodID],
 [BackdatedPymtConsideration],
 [BackdatedPymtConsiderationTime],
 [Sharding],
 [MiniPODNumber],
 [AsynchronousPosting],
 [HighBalanceRecalculation],
 [PHPCalculationLogicOn],
 [PartnerName],
 [EODDataApproach],
 [RealTimePostingDuringEOM],
 [NewTNPQueue],
 [CBRFrequency],
 [CBRDataFrom],
 [CBRWeeklyPeriod],
 [CBREventReporting],
 [CBRHonourStatus],
 [CBRUpdateCCC],
 [CBRPaymentMade],
 [CBRUpdateSCC],
 [CBRUpdateCII],
 [CBRUpdateBillngCycle],
 [TSDBOActive],
 [TSDBOAllowedMonths],
 [TSDBOActiveDate]
FROM Org_Balances WITH (NOLOCK)
GO

CREATE OR ALTER PROCEDURE sp_Org_Balances_del(  @acctId int ) AS
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET QUOTED_IDENTIFIER ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;
DELETE FROM Org_Balances
WHERE 
   [acctId] = @acctId 
GO

CREATE OR ALTER PROCEDURE sp_Org_Balances_upd  @acctId int,
  @AmountOfDebitsDM1 money,
  @NumberOfDebitsDM1 int,
  @AmountOfCreditsDM1 money,
  @NumberOfCreditsDM1 int,
  @AmtGenDebitsDD1 money,
  @AmtGenCreditsDD1 money,
  @NbrGenDebitsDD1 int,
  @NbrGenCreditsDD1 int,
  @TotAmtCashPurAuthReqDD1 money,
  @TotAmtCashPurAuthReqDD2 money,
  @TotAmtCashPurAuthReqDD3 money,
  @TotNoCashPurAuthReqDD1 int,
  @TotNoCashPurAuthReqDD2 int,
  @TotNoCashPurAuthReqDD3 int,
  @PeriodPrefix int,
  @ARSystemAcctId int,
  @TimeZone char (3),
  @DayLightSaving tinyint,
  @ProcessingDayEndTime datetime,
  @CBRPortfolioType varchar (5),
  @CBRAccountType varchar (5),
  @PreferredLanguage varchar (8),
  @CMTransactionHistoryUpto varchar (5),
  @CMTransactionHistoryUpRange varchar (5),
  @ACHCutoffTime char (8),
  @NoOfTxnInACHFile int,
  @SSRegistrationMethod varchar (5),
  @SSForgetPasswordMethod varchar (5),
  @SSForgetUserIDMethod varchar (5),
  @SSDisputeAllowed varchar (5),
  @ccinhparent136AID int,
  @ccinhparent136ATID int,
  @ccinhparent137AID int,
  @ccinhparent137ATID int,
  @ccinhparent138AID int,
  @ccinhparent138ATID int,
  @ccinhparent139AID int,
  @ccinhparent139ATID int,
  @ccinhparent140AID int,
  @ccinhparent140ATID int,
  @ccinhparent141AID int,
  @ccinhparent141ATID int,
  @ccinhparent142AID int,
  @ccinhparent142ATID int,
  @ccinhparent143AID int,
  @ccinhparent143ATID int,
  @ccinhparent144AID int,
  @ccinhparent144ATID int,
  @ccinhparent145AID int,
  @ccinhparent145ATID int,
  @ccinhparent146AID int,
  @ccinhparent146ATID int,
  @ccinhparent147AID int,
  @ccinhparent147ATID int,
  @BankVerificationMethod varchar (2),
  @CEDAlignment varchar (5),
  @CompanyEntryDescription varchar (10),
  @CompanyID varchar (10),
  @CompanyName varchar (16),
  @CompanyNameAlignment varchar (5),
  @ECCAlignment varchar (5),
  @EntryClassCode varchar (3),
  @CompanyIdAlignment varchar (5),
  @DestinationAlignment varchar (5),
  @DestinationRTAlignment varchar (5),
  @OriginationAlignment varchar (5),
  @TINAlignment varchar (5),
  @DEKEncryptionRequired varchar (1),
  @DEKEncryptionKey varchar (100),
  @RefundDescription char (15),
  @BillPayOriginatorsRFIID varchar (15),
  @BillPayDestinationName char (25),
  @HolidayConsideration char (1),
  @AccountNumberGeneration varchar (15),
  @AccountNumberPrefix varchar (15),
  @AccountNumberPostValue varchar (15),
  @WellsFargoBankABA char (10),
  @WellsFargoBankName varchar (20),
  @PreQual varchar (5),
  @ChargeAssmtFee tinyint,
  @MerchantTaxIdentificationNumber varchar (10),
  @CompanyNameCCD varchar (16),
  @CompanyIdCCD varchar (10),
  @CompanyEntryDescCCDDebit varchar (10),
  @CompanyEntryDescCCDCredit varchar (10),
  @DestRoutingTransitRefund varchar (10),
  @ACHIdRefund varchar (10),
  @OrigRoutingTransitRefund varchar (10),
  @CompanyIdRefund varchar (10),
  @DestRoutingTransitReward varchar (10),
  @ACHIdReward varchar (10),
  @OrigRoutingTransitReward varchar (10),
  @CompanyIdReward varchar (10),
  @ACHFileContent varchar (2),
  @PODID tinyint,
  @SysSubOrgID tinyint,
  @StmtCTDCombination varchar (2),
  @StmtEODCombination varchar (2),
  @ProgramIdSBFE varchar (10),
  @BDCInDueDate tinyint,
  @BDCInLateFeeDate tinyint,
  @MiniPodID varchar (64),
  @BackdatedPymtConsideration varchar (1),
  @BackdatedPymtConsiderationTime varchar (8),
  @Sharding int,
  @MiniPODNumber int,
  @AsynchronousPosting char (2),
  @HighBalanceRecalculation varchar (2),
  @PHPCalculationLogicOn varchar (1),
  @PartnerName char (5),
  @EODDataApproach int,
  @RealTimePostingDuringEOM varchar (2),
  @NewTNPQueue varchar (2),
  @CBRFrequency varchar (1),
  @CBRDataFrom varchar (1),
  @CBRWeeklyPeriod varchar (1),
  @CBREventReporting varchar (1),
  @CBRHonourStatus tinyint,
  @CBRUpdateCCC tinyint,
  @CBRPaymentMade tinyint,
  @CBRUpdateSCC tinyint,
  @CBRUpdateCII tinyint,
  @CBRUpdateBillngCycle tinyint,
  @TSDBOActive varchar (2),
  @TSDBOAllowedMonths int,
  @TSDBOActiveDate datetime AS
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET QUOTED_IDENTIFIER ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;
SET NOCOUNT OFF;
 UPDATE Org_Balances SET   [acctId] = @acctId,
  [AmountOfDebitsDM1] = @AmountOfDebitsDM1,
  [NumberOfDebitsDM1] = @NumberOfDebitsDM1,
  [AmountOfCreditsDM1] = @AmountOfCreditsDM1,
  [NumberOfCreditsDM1] = @NumberOfCreditsDM1,
  [AmtGenDebitsDD1] = @AmtGenDebitsDD1,
  [AmtGenCreditsDD1] = @AmtGenCreditsDD1,
  [NbrGenDebitsDD1] = @NbrGenDebitsDD1,
  [NbrGenCreditsDD1] = @NbrGenCreditsDD1,
  [TotAmtCashPurAuthReqDD1] = @TotAmtCashPurAuthReqDD1,
  [TotAmtCashPurAuthReqDD2] = @TotAmtCashPurAuthReqDD2,
  [TotAmtCashPurAuthReqDD3] = @TotAmtCashPurAuthReqDD3,
  [TotNoCashPurAuthReqDD1] = @TotNoCashPurAuthReqDD1,
  [TotNoCashPurAuthReqDD2] = @TotNoCashPurAuthReqDD2,
  [TotNoCashPurAuthReqDD3] = @TotNoCashPurAuthReqDD3,
  [PeriodPrefix] = @PeriodPrefix,
  [ARSystemAcctId] = @ARSystemAcctId,
  [TimeZone] = @TimeZone,
  [DayLightSaving] = @DayLightSaving,
  [ProcessingDayEndTime] = @ProcessingDayEndTime,
  [CBRPortfolioType] = @CBRPortfolioType,
  [CBRAccountType] = @CBRAccountType,
  [PreferredLanguage] = @PreferredLanguage,
  [CMTransactionHistoryUpto] = @CMTransactionHistoryUpto,
  [CMTransactionHistoryUpRange] = @CMTransactionHistoryUpRange,
  [ACHCutoffTime] = @ACHCutoffTime,
  [NoOfTxnInACHFile] = @NoOfTxnInACHFile,
  [SSRegistrationMethod] = @SSRegistrationMethod,
  [SSForgetPasswordMethod] = @SSForgetPasswordMethod,
  [SSForgetUserIDMethod] = @SSForgetUserIDMethod,
  [SSDisputeAllowed] = @SSDisputeAllowed,
  [ccinhparent136AID] = @ccinhparent136AID,
  [ccinhparent136ATID] = @ccinhparent136ATID,
  [ccinhparent137AID] = @ccinhparent137AID,
  [ccinhparent137ATID] = @ccinhparent137ATID,
  [ccinhparent138AID] = @ccinhparent138AID,
  [ccinhparent138ATID] = @ccinhparent138ATID,
  [ccinhparent139AID] = @ccinhparent139AID,
  [ccinhparent139ATID] = @ccinhparent139ATID,
  [ccinhparent140AID] = @ccinhparent140AID,
  [ccinhparent140ATID] = @ccinhparent140ATID,
  [ccinhparent141AID] = @ccinhparent141AID,
  [ccinhparent141ATID] = @ccinhparent141ATID,
  [ccinhparent142AID] = @ccinhparent142AID,
  [ccinhparent142ATID] = @ccinhparent142ATID,
  [ccinhparent143AID] = @ccinhparent143AID,
  [ccinhparent143ATID] = @ccinhparent143ATID,
  [ccinhparent144AID] = @ccinhparent144AID,
  [ccinhparent144ATID] = @ccinhparent144ATID,
  [ccinhparent145AID] = @ccinhparent145AID,
  [ccinhparent145ATID] = @ccinhparent145ATID,
  [ccinhparent146AID] = @ccinhparent146AID,
  [ccinhparent146ATID] = @ccinhparent146ATID,
  [ccinhparent147AID] = @ccinhparent147AID,
  [ccinhparent147ATID] = @ccinhparent147ATID,
  [BankVerificationMethod] = @BankVerificationMethod,
  [CEDAlignment] = @CEDAlignment,
  [CompanyEntryDescription] = @CompanyEntryDescription,
  [CompanyID] = @CompanyID,
  [CompanyName] = @CompanyName,
  [CompanyNameAlignment] = @CompanyNameAlignment,
  [ECCAlignment] = @ECCAlignment,
  [EntryClassCode] = @EntryClassCode,
  [CompanyIdAlignment] = @CompanyIdAlignment,
  [DestinationAlignment] = @DestinationAlignment,
  [DestinationRTAlignment] = @DestinationRTAlignment,
  [OriginationAlignment] = @OriginationAlignment,
  [TINAlignment] = @TINAlignment,
  [DEKEncryptionRequired] = @DEKEncryptionRequired,
  [DEKEncryptionKey] = @DEKEncryptionKey,
  [RefundDescription] = @RefundDescription,
  [BillPayOriginatorsRFIID] = @BillPayOriginatorsRFIID,
  [BillPayDestinationName] = @BillPayDestinationName,
  [HolidayConsideration] = @HolidayConsideration,
  [AccountNumberGeneration] = @AccountNumberGeneration,
  [AccountNumberPrefix] = @AccountNumberPrefix,
  [AccountNumberPostValue] = @AccountNumberPostValue,
  [WellsFargoBankABA] = @WellsFargoBankABA,
  [WellsFargoBankName] = @WellsFargoBankName,
  [PreQual] = @PreQual,
  [ChargeAssmtFee] = @ChargeAssmtFee,
  [MerchantTaxIdentificationNumber] = @MerchantTaxIdentificationNumber,
  [CompanyNameCCD] = @CompanyNameCCD,
  [CompanyIdCCD] = @CompanyIdCCD,
  [CompanyEntryDescCCDDebit] = @CompanyEntryDescCCDDebit,
  [CompanyEntryDescCCDCredit] = @CompanyEntryDescCCDCredit,
  [DestRoutingTransitRefund] = @DestRoutingTransitRefund,
  [ACHIdRefund] = @ACHIdRefund,
  [OrigRoutingTransitRefund] = @OrigRoutingTransitRefund,
  [CompanyIdRefund] = @CompanyIdRefund,
  [DestRoutingTransitReward] = @DestRoutingTransitReward,
  [ACHIdReward] = @ACHIdReward,
  [OrigRoutingTransitReward] = @OrigRoutingTransitReward,
  [CompanyIdReward] = @CompanyIdReward,
  [ACHFileContent] = @ACHFileContent,
  [PODID] = @PODID,
  [SysSubOrgID] = @SysSubOrgID,
  [StmtCTDCombination] = @StmtCTDCombination,
  [StmtEODCombination] = @StmtEODCombination,
  [ProgramIdSBFE] = @ProgramIdSBFE,
  [BDCInDueDate] = @BDCInDueDate,
  [BDCInLateFeeDate] = @BDCInLateFeeDate,
  [MiniPodID] = @MiniPodID,
  [BackdatedPymtConsideration] = @BackdatedPymtConsideration,
  [BackdatedPymtConsiderationTime] = @BackdatedPymtConsiderationTime,
  [Sharding] = @Sharding,
  [MiniPODNumber] = @MiniPODNumber,
  [AsynchronousPosting] = @AsynchronousPosting,
  [HighBalanceRecalculation] = @HighBalanceRecalculation,
  [PHPCalculationLogicOn] = @PHPCalculationLogicOn,
  [PartnerName] = @PartnerName,
  [EODDataApproach] = @EODDataApproach,
  [RealTimePostingDuringEOM] = @RealTimePostingDuringEOM,
  [NewTNPQueue] = @NewTNPQueue,
  [CBRFrequency] = @CBRFrequency,
  [CBRDataFrom] = @CBRDataFrom,
  [CBRWeeklyPeriod] = @CBRWeeklyPeriod,
  [CBREventReporting] = @CBREventReporting,
  [CBRHonourStatus] = @CBRHonourStatus,
  [CBRUpdateCCC] = @CBRUpdateCCC,
  [CBRPaymentMade] = @CBRPaymentMade,
  [CBRUpdateSCC] = @CBRUpdateSCC,
  [CBRUpdateCII] = @CBRUpdateCII,
  [CBRUpdateBillngCycle] = @CBRUpdateBillngCycle,
  [TSDBOActive] = @TSDBOActive,
  [TSDBOAllowedMonths] = @TSDBOAllowedMonths,
  [TSDBOActiveDate] = @TSDBOActiveDate 
WHERE 
   [acctId] = @acctId 
GO

CREATE OR ALTER PROCEDURE sp_Org_Balances_ins (
  @acctId int,
  @AmountOfDebitsDM1 money,
  @NumberOfDebitsDM1 int,
  @AmountOfCreditsDM1 money,
  @NumberOfCreditsDM1 int,
  @AmtGenDebitsDD1 money,
  @AmtGenCreditsDD1 money,
  @NbrGenDebitsDD1 int,
  @NbrGenCreditsDD1 int,
  @TotAmtCashPurAuthReqDD1 money,
  @TotAmtCashPurAuthReqDD2 money,
  @TotAmtCashPurAuthReqDD3 money,
  @TotNoCashPurAuthReqDD1 int,
  @TotNoCashPurAuthReqDD2 int,
  @TotNoCashPurAuthReqDD3 int,
  @PeriodPrefix int,
  @ARSystemAcctId int,
  @TimeZone char (3),
  @DayLightSaving tinyint,
  @ProcessingDayEndTime datetime,
  @CBRPortfolioType varchar (5),
  @CBRAccountType varchar (5),
  @PreferredLanguage varchar (8),
  @CMTransactionHistoryUpto varchar (5),
  @CMTransactionHistoryUpRange varchar (5),
  @ACHCutoffTime char (8),
  @NoOfTxnInACHFile int,
  @SSRegistrationMethod varchar (5),
  @SSForgetPasswordMethod varchar (5),
  @SSForgetUserIDMethod varchar (5),
  @SSDisputeAllowed varchar (5),
  @ccinhparent136AID int,
  @ccinhparent136ATID int,
  @ccinhparent137AID int,
  @ccinhparent137ATID int,
  @ccinhparent138AID int,
  @ccinhparent138ATID int,
  @ccinhparent139AID int,
  @ccinhparent139ATID int,
  @ccinhparent140AID int,
  @ccinhparent140ATID int,
  @ccinhparent141AID int,
  @ccinhparent141ATID int,
  @ccinhparent142AID int,
  @ccinhparent142ATID int,
  @ccinhparent143AID int,
  @ccinhparent143ATID int,
  @ccinhparent144AID int,
  @ccinhparent144ATID int,
  @ccinhparent145AID int,
  @ccinhparent145ATID int,
  @ccinhparent146AID int,
  @ccinhparent146ATID int,
  @ccinhparent147AID int,
  @ccinhparent147ATID int,
  @BankVerificationMethod varchar (2),
  @CEDAlignment varchar (5),
  @CompanyEntryDescription varchar (10),
  @CompanyID varchar (10),
  @CompanyName varchar (16),
  @CompanyNameAlignment varchar (5),
  @ECCAlignment varchar (5),
  @EntryClassCode varchar (3),
  @CompanyIdAlignment varchar (5),
  @DestinationAlignment varchar (5),
  @DestinationRTAlignment varchar (5),
  @OriginationAlignment varchar (5),
  @TINAlignment varchar (5),
  @DEKEncryptionRequired varchar (1),
  @DEKEncryptionKey varchar (100),
  @RefundDescription char (15),
  @BillPayOriginatorsRFIID varchar (15),
  @BillPayDestinationName char (25),
  @HolidayConsideration char (1),
  @AccountNumberGeneration varchar (15),
  @AccountNumberPrefix varchar (15),
  @AccountNumberPostValue varchar (15),
  @WellsFargoBankABA char (10),
  @WellsFargoBankName varchar (20),
  @PreQual varchar (5),
  @ChargeAssmtFee tinyint,
  @MerchantTaxIdentificationNumber varchar (10),
  @CompanyNameCCD varchar (16),
  @CompanyIdCCD varchar (10),
  @CompanyEntryDescCCDDebit varchar (10),
  @CompanyEntryDescCCDCredit varchar (10),
  @DestRoutingTransitRefund varchar (10),
  @ACHIdRefund varchar (10),
  @OrigRoutingTransitRefund varchar (10),
  @CompanyIdRefund varchar (10),
  @DestRoutingTransitReward varchar (10),
  @ACHIdReward varchar (10),
  @OrigRoutingTransitReward varchar (10),
  @CompanyIdReward varchar (10),
  @ACHFileContent varchar (2),
  @PODID tinyint,
  @SysSubOrgID tinyint,
  @StmtCTDCombination varchar (2),
  @StmtEODCombination varchar (2),
  @ProgramIdSBFE varchar (10),
  @BDCInDueDate tinyint,
  @BDCInLateFeeDate tinyint,
  @MiniPodID varchar (64),
  @BackdatedPymtConsideration varchar (1),
  @BackdatedPymtConsiderationTime varchar (8),
  @Sharding int,
  @MiniPODNumber int,
  @AsynchronousPosting char (2),
  @HighBalanceRecalculation varchar (2),
  @PHPCalculationLogicOn varchar (1),
  @PartnerName char (5),
  @EODDataApproach int,
  @RealTimePostingDuringEOM varchar (2),
  @NewTNPQueue varchar (2),
  @CBRFrequency varchar (1),
  @CBRDataFrom varchar (1),
  @CBRWeeklyPeriod varchar (1),
  @CBREventReporting varchar (1),
  @CBRHonourStatus tinyint,
  @CBRUpdateCCC tinyint,
  @CBRPaymentMade tinyint,
  @CBRUpdateSCC tinyint,
  @CBRUpdateCII tinyint,
  @CBRUpdateBillngCycle tinyint,
  @TSDBOActive varchar (2),
  @TSDBOAllowedMonths int,
  @TSDBOActiveDate datetime)
AS
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET QUOTED_IDENTIFIER ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;
 INSERT INTO Org_Balances 
(  [acctId],
 [AmountOfDebitsDM1],
 [NumberOfDebitsDM1],
 [AmountOfCreditsDM1],
 [NumberOfCreditsDM1],
 [AmtGenDebitsDD1],
 [AmtGenCreditsDD1],
 [NbrGenDebitsDD1],
 [NbrGenCreditsDD1],
 [TotAmtCashPurAuthReqDD1],
 [TotAmtCashPurAuthReqDD2],
 [TotAmtCashPurAuthReqDD3],
 [TotNoCashPurAuthReqDD1],
 [TotNoCashPurAuthReqDD2],
 [TotNoCashPurAuthReqDD3],
 [PeriodPrefix],
 [ARSystemAcctId],
 [TimeZone],
 [DayLightSaving],
 [ProcessingDayEndTime],
 [CBRPortfolioType],
 [CBRAccountType],
 [PreferredLanguage],
 [CMTransactionHistoryUpto],
 [CMTransactionHistoryUpRange],
 [ACHCutoffTime],
 [NoOfTxnInACHFile],
 [SSRegistrationMethod],
 [SSForgetPasswordMethod],
 [SSForgetUserIDMethod],
 [SSDisputeAllowed],
 [ccinhparent136AID],
 [ccinhparent136ATID],
 [ccinhparent137AID],
 [ccinhparent137ATID],
 [ccinhparent138AID],
 [ccinhparent138ATID],
 [ccinhparent139AID],
 [ccinhparent139ATID],
 [ccinhparent140AID],
 [ccinhparent140ATID],
 [ccinhparent141AID],
 [ccinhparent141ATID],
 [ccinhparent142AID],
 [ccinhparent142ATID],
 [ccinhparent143AID],
 [ccinhparent143ATID],
 [ccinhparent144AID],
 [ccinhparent144ATID],
 [ccinhparent145AID],
 [ccinhparent145ATID],
 [ccinhparent146AID],
 [ccinhparent146ATID],
 [ccinhparent147AID],
 [ccinhparent147ATID],
 [BankVerificationMethod],
 [CEDAlignment],
 [CompanyEntryDescription],
 [CompanyID],
 [CompanyName],
 [CompanyNameAlignment],
 [ECCAlignment],
 [EntryClassCode],
 [CompanyIdAlignment],
 [DestinationAlignment],
 [DestinationRTAlignment],
 [OriginationAlignment],
 [TINAlignment],
 [DEKEncryptionRequired],
 [DEKEncryptionKey],
 [RefundDescription],
 [BillPayOriginatorsRFIID],
 [BillPayDestinationName],
 [HolidayConsideration],
 [AccountNumberGeneration],
 [AccountNumberPrefix],
 [AccountNumberPostValue],
 [WellsFargoBankABA],
 [WellsFargoBankName],
 [PreQual],
 [ChargeAssmtFee],
 [MerchantTaxIdentificationNumber],
 [CompanyNameCCD],
 [CompanyIdCCD],
 [CompanyEntryDescCCDDebit],
 [CompanyEntryDescCCDCredit],
 [DestRoutingTransitRefund],
 [ACHIdRefund],
 [OrigRoutingTransitRefund],
 [CompanyIdRefund],
 [DestRoutingTransitReward],
 [ACHIdReward],
 [OrigRoutingTransitReward],
 [CompanyIdReward],
 [ACHFileContent],
 [PODID],
 [SysSubOrgID],
 [StmtCTDCombination],
 [StmtEODCombination],
 [ProgramIdSBFE],
 [BDCInDueDate],
 [BDCInLateFeeDate],
 [MiniPodID],
 [BackdatedPymtConsideration],
 [BackdatedPymtConsiderationTime],
 [Sharding],
 [MiniPODNumber],
 [AsynchronousPosting],
 [HighBalanceRecalculation],
 [PHPCalculationLogicOn],
 [PartnerName],
 [EODDataApproach],
 [RealTimePostingDuringEOM],
 [NewTNPQueue],
 [CBRFrequency],
 [CBRDataFrom],
 [CBRWeeklyPeriod],
 [CBREventReporting],
 [CBRHonourStatus],
 [CBRUpdateCCC],
 [CBRPaymentMade],
 [CBRUpdateSCC],
 [CBRUpdateCII],
 [CBRUpdateBillngCycle],
 [TSDBOActive],
 [TSDBOAllowedMonths],
 [TSDBOActiveDate])
VALUES (  @acctId,
 @AmountOfDebitsDM1,
 @NumberOfDebitsDM1,
 @AmountOfCreditsDM1,
 @NumberOfCreditsDM1,
 @AmtGenDebitsDD1,
 @AmtGenCreditsDD1,
 @NbrGenDebitsDD1,
 @NbrGenCreditsDD1,
 @TotAmtCashPurAuthReqDD1,
 @TotAmtCashPurAuthReqDD2,
 @TotAmtCashPurAuthReqDD3,
 @TotNoCashPurAuthReqDD1,
 @TotNoCashPurAuthReqDD2,
 @TotNoCashPurAuthReqDD3,
 @PeriodPrefix,
 @ARSystemAcctId,
 @TimeZone,
 @DayLightSaving,
 @ProcessingDayEndTime,
 @CBRPortfolioType,
 @CBRAccountType,
 @PreferredLanguage,
 @CMTransactionHistoryUpto,
 @CMTransactionHistoryUpRange,
 @ACHCutoffTime,
 @NoOfTxnInACHFile,
 @SSRegistrationMethod,
 @SSForgetPasswordMethod,
 @SSForgetUserIDMethod,
 @SSDisputeAllowed,
 @ccinhparent136AID,
 @ccinhparent136ATID,
 @ccinhparent137AID,
 @ccinhparent137ATID,
 @ccinhparent138AID,
 @ccinhparent138ATID,
 @ccinhparent139AID,
 @ccinhparent139ATID,
 @ccinhparent140AID,
 @ccinhparent140ATID,
 @ccinhparent141AID,
 @ccinhparent141ATID,
 @ccinhparent142AID,
 @ccinhparent142ATID,
 @ccinhparent143AID,
 @ccinhparent143ATID,
 @ccinhparent144AID,
 @ccinhparent144ATID,
 @ccinhparent145AID,
 @ccinhparent145ATID,
 @ccinhparent146AID,
 @ccinhparent146ATID,
 @ccinhparent147AID,
 @ccinhparent147ATID,
 @BankVerificationMethod,
 @CEDAlignment,
 @CompanyEntryDescription,
 @CompanyID,
 @CompanyName,
 @CompanyNameAlignment,
 @ECCAlignment,
 @EntryClassCode,
 @CompanyIdAlignment,
 @DestinationAlignment,
 @DestinationRTAlignment,
 @OriginationAlignment,
 @TINAlignment,
 @DEKEncryptionRequired,
 @DEKEncryptionKey,
 @RefundDescription,
 @BillPayOriginatorsRFIID,
 @BillPayDestinationName,
 @HolidayConsideration,
 @AccountNumberGeneration,
 @AccountNumberPrefix,
 @AccountNumberPostValue,
 @WellsFargoBankABA,
 @WellsFargoBankName,
 @PreQual,
 @ChargeAssmtFee,
 @MerchantTaxIdentificationNumber,
 @CompanyNameCCD,
 @CompanyIdCCD,
 @CompanyEntryDescCCDDebit,
 @CompanyEntryDescCCDCredit,
 @DestRoutingTransitRefund,
 @ACHIdRefund,
 @OrigRoutingTransitRefund,
 @CompanyIdRefund,
 @DestRoutingTransitReward,
 @ACHIdReward,
 @OrigRoutingTransitReward,
 @CompanyIdReward,
 @ACHFileContent,
 @PODID,
 @SysSubOrgID,
 @StmtCTDCombination,
 @StmtEODCombination,
 @ProgramIdSBFE,
 @BDCInDueDate,
 @BDCInLateFeeDate,
 @MiniPodID,
 @BackdatedPymtConsideration,
 @BackdatedPymtConsiderationTime,
 @Sharding,
 @MiniPODNumber,
 @AsynchronousPosting,
 @HighBalanceRecalculation,
 @PHPCalculationLogicOn,
 @PartnerName,
 @EODDataApproach,
 @RealTimePostingDuringEOM,
 @NewTNPQueue,
 @CBRFrequency,
 @CBRDataFrom,
 @CBRWeeklyPeriod,
 @CBREventReporting,
 @CBRHonourStatus,
 @CBRUpdateCCC,
 @CBRPaymentMade,
 @CBRUpdateSCC,
 @CBRUpdateCII,
 @CBRUpdateBillngCycle,
 @TSDBOActive,
 @TSDBOAllowedMonths,
 @TSDBOActiveDate)
GO

CREATE OR ALTER PROCEDURE sp_Org_Balances_insupd (  @acctId int,
  @AmountOfDebitsDM1 money,
  @NumberOfDebitsDM1 int,
  @AmountOfCreditsDM1 money,
  @NumberOfCreditsDM1 int,
  @AmtGenDebitsDD1 money,
  @AmtGenCreditsDD1 money,
  @NbrGenDebitsDD1 int,
  @NbrGenCreditsDD1 int,
  @TotAmtCashPurAuthReqDD1 money,
  @TotAmtCashPurAuthReqDD2 money,
  @TotAmtCashPurAuthReqDD3 money,
  @TotNoCashPurAuthReqDD1 int,
  @TotNoCashPurAuthReqDD2 int,
  @TotNoCashPurAuthReqDD3 int,
  @PeriodPrefix int,
  @ARSystemAcctId int,
  @TimeZone char (3),
  @DayLightSaving tinyint,
  @ProcessingDayEndTime datetime,
  @CBRPortfolioType varchar (5),
  @CBRAccountType varchar (5),
  @PreferredLanguage varchar (8),
  @CMTransactionHistoryUpto varchar (5),
  @CMTransactionHistoryUpRange varchar (5),
  @ACHCutoffTime char (8),
  @NoOfTxnInACHFile int,
  @SSRegistrationMethod varchar (5),
  @SSForgetPasswordMethod varchar (5),
  @SSForgetUserIDMethod varchar (5),
  @SSDisputeAllowed varchar (5),
  @ccinhparent136AID int,
  @ccinhparent136ATID int,
  @ccinhparent137AID int,
  @ccinhparent137ATID int,
  @ccinhparent138AID int,
  @ccinhparent138ATID int,
  @ccinhparent139AID int,
  @ccinhparent139ATID int,
  @ccinhparent140AID int,
  @ccinhparent140ATID int,
  @ccinhparent141AID int,
  @ccinhparent141ATID int,
  @ccinhparent142AID int,
  @ccinhparent142ATID int,
  @ccinhparent143AID int,
  @ccinhparent143ATID int,
  @ccinhparent144AID int,
  @ccinhparent144ATID int,
  @ccinhparent145AID int,
  @ccinhparent145ATID int,
  @ccinhparent146AID int,
  @ccinhparent146ATID int,
  @ccinhparent147AID int,
  @ccinhparent147ATID int,
  @BankVerificationMethod varchar (2),
  @CEDAlignment varchar (5),
  @CompanyEntryDescription varchar (10),
  @CompanyID varchar (10),
  @CompanyName varchar (16),
  @CompanyNameAlignment varchar (5),
  @ECCAlignment varchar (5),
  @EntryClassCode varchar (3),
  @CompanyIdAlignment varchar (5),
  @DestinationAlignment varchar (5),
  @DestinationRTAlignment varchar (5),
  @OriginationAlignment varchar (5),
  @TINAlignment varchar (5),
  @DEKEncryptionRequired varchar (1),
  @DEKEncryptionKey varchar (100),
  @RefundDescription char (15),
  @BillPayOriginatorsRFIID varchar (15),
  @BillPayDestinationName char (25),
  @HolidayConsideration char (1),
  @AccountNumberGeneration varchar (15),
  @AccountNumberPrefix varchar (15),
  @AccountNumberPostValue varchar (15),
  @WellsFargoBankABA char (10),
  @WellsFargoBankName varchar (20),
  @PreQual varchar (5),
  @ChargeAssmtFee tinyint,
  @MerchantTaxIdentificationNumber varchar (10),
  @CompanyNameCCD varchar (16),
  @CompanyIdCCD varchar (10),
  @CompanyEntryDescCCDDebit varchar (10),
  @CompanyEntryDescCCDCredit varchar (10),
  @DestRoutingTransitRefund varchar (10),
  @ACHIdRefund varchar (10),
  @OrigRoutingTransitRefund varchar (10),
  @CompanyIdRefund varchar (10),
  @DestRoutingTransitReward varchar (10),
  @ACHIdReward varchar (10),
  @OrigRoutingTransitReward varchar (10),
  @CompanyIdReward varchar (10),
  @ACHFileContent varchar (2),
  @PODID tinyint,
  @SysSubOrgID tinyint,
  @StmtCTDCombination varchar (2),
  @StmtEODCombination varchar (2),
  @ProgramIdSBFE varchar (10),
  @BDCInDueDate tinyint,
  @BDCInLateFeeDate tinyint,
  @MiniPodID varchar (64),
  @BackdatedPymtConsideration varchar (1),
  @BackdatedPymtConsiderationTime varchar (8),
  @Sharding int,
  @MiniPODNumber int,
  @AsynchronousPosting char (2),
  @HighBalanceRecalculation varchar (2),
  @PHPCalculationLogicOn varchar (1),
  @PartnerName char (5),
  @EODDataApproach int,
  @RealTimePostingDuringEOM varchar (2),
  @NewTNPQueue varchar (2),
  @CBRFrequency varchar (1),
  @CBRDataFrom varchar (1),
  @CBRWeeklyPeriod varchar (1),
  @CBREventReporting varchar (1),
  @CBRHonourStatus tinyint,
  @CBRUpdateCCC tinyint,
  @CBRPaymentMade tinyint,
  @CBRUpdateSCC tinyint,
  @CBRUpdateCII tinyint,
  @CBRUpdateBillngCycle tinyint,
  @TSDBOActive varchar (2),
  @TSDBOAllowedMonths int,
  @TSDBOActiveDate datetime) AS
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET QUOTED_IDENTIFIER ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;
SET NOCOUNT OFF;

IF EXISTS (SELECT [acctId] FROM Org_Balances WHERE 
   [acctId] = @acctId 
)
UPDATE Org_Balances SET  [acctId] = @acctId,
  [AmountOfDebitsDM1] = @AmountOfDebitsDM1,
  [NumberOfDebitsDM1] = @NumberOfDebitsDM1,
  [AmountOfCreditsDM1] = @AmountOfCreditsDM1,
  [NumberOfCreditsDM1] = @NumberOfCreditsDM1,
  [AmtGenDebitsDD1] = @AmtGenDebitsDD1,
  [AmtGenCreditsDD1] = @AmtGenCreditsDD1,
  [NbrGenDebitsDD1] = @NbrGenDebitsDD1,
  [NbrGenCreditsDD1] = @NbrGenCreditsDD1,
  [TotAmtCashPurAuthReqDD1] = @TotAmtCashPurAuthReqDD1,
  [TotAmtCashPurAuthReqDD2] = @TotAmtCashPurAuthReqDD2,
  [TotAmtCashPurAuthReqDD3] = @TotAmtCashPurAuthReqDD3,
  [TotNoCashPurAuthReqDD1] = @TotNoCashPurAuthReqDD1,
  [TotNoCashPurAuthReqDD2] = @TotNoCashPurAuthReqDD2,
  [TotNoCashPurAuthReqDD3] = @TotNoCashPurAuthReqDD3,
  [PeriodPrefix] = @PeriodPrefix,
  [ARSystemAcctId] = @ARSystemAcctId,
  [TimeZone] = @TimeZone,
  [DayLightSaving] = @DayLightSaving,
  [ProcessingDayEndTime] = @ProcessingDayEndTime,
  [CBRPortfolioType] = @CBRPortfolioType,
  [CBRAccountType] = @CBRAccountType,
  [PreferredLanguage] = @PreferredLanguage,
  [CMTransactionHistoryUpto] = @CMTransactionHistoryUpto,
  [CMTransactionHistoryUpRange] = @CMTransactionHistoryUpRange,
  [ACHCutoffTime] = @ACHCutoffTime,
  [NoOfTxnInACHFile] = @NoOfTxnInACHFile,
  [SSRegistrationMethod] = @SSRegistrationMethod,
  [SSForgetPasswordMethod] = @SSForgetPasswordMethod,
  [SSForgetUserIDMethod] = @SSForgetUserIDMethod,
  [SSDisputeAllowed] = @SSDisputeAllowed,
  [ccinhparent136AID] = @ccinhparent136AID,
  [ccinhparent136ATID] = @ccinhparent136ATID,
  [ccinhparent137AID] = @ccinhparent137AID,
  [ccinhparent137ATID] = @ccinhparent137ATID,
  [ccinhparent138AID] = @ccinhparent138AID,
  [ccinhparent138ATID] = @ccinhparent138ATID,
  [ccinhparent139AID] = @ccinhparent139AID,
  [ccinhparent139ATID] = @ccinhparent139ATID,
  [ccinhparent140AID] = @ccinhparent140AID,
  [ccinhparent140ATID] = @ccinhparent140ATID,
  [ccinhparent141AID] = @ccinhparent141AID,
  [ccinhparent141ATID] = @ccinhparent141ATID,
  [ccinhparent142AID] = @ccinhparent142AID,
  [ccinhparent142ATID] = @ccinhparent142ATID,
  [ccinhparent143AID] = @ccinhparent143AID,
  [ccinhparent143ATID] = @ccinhparent143ATID,
  [ccinhparent144AID] = @ccinhparent144AID,
  [ccinhparent144ATID] = @ccinhparent144ATID,
  [ccinhparent145AID] = @ccinhparent145AID,
  [ccinhparent145ATID] = @ccinhparent145ATID,
  [ccinhparent146AID] = @ccinhparent146AID,
  [ccinhparent146ATID] = @ccinhparent146ATID,
  [ccinhparent147AID] = @ccinhparent147AID,
  [ccinhparent147ATID] = @ccinhparent147ATID,
  [BankVerificationMethod] = @BankVerificationMethod,
  [CEDAlignment] = @CEDAlignment,
  [CompanyEntryDescription] = @CompanyEntryDescription,
  [CompanyID] = @CompanyID,
  [CompanyName] = @CompanyName,
  [CompanyNameAlignment] = @CompanyNameAlignment,
  [ECCAlignment] = @ECCAlignment,
  [EntryClassCode] = @EntryClassCode,
  [CompanyIdAlignment] = @CompanyIdAlignment,
  [DestinationAlignment] = @DestinationAlignment,
  [DestinationRTAlignment] = @DestinationRTAlignment,
  [OriginationAlignment] = @OriginationAlignment,
  [TINAlignment] = @TINAlignment,
  [DEKEncryptionRequired] = @DEKEncryptionRequired,
  [DEKEncryptionKey] = @DEKEncryptionKey,
  [RefundDescription] = @RefundDescription,
  [BillPayOriginatorsRFIID] = @BillPayOriginatorsRFIID,
  [BillPayDestinationName] = @BillPayDestinationName,
  [HolidayConsideration] = @HolidayConsideration,
  [AccountNumberGeneration] = @AccountNumberGeneration,
  [AccountNumberPrefix] = @AccountNumberPrefix,
  [AccountNumberPostValue] = @AccountNumberPostValue,
  [WellsFargoBankABA] = @WellsFargoBankABA,
  [WellsFargoBankName] = @WellsFargoBankName,
  [PreQual] = @PreQual,
  [ChargeAssmtFee] = @ChargeAssmtFee,
  [MerchantTaxIdentificationNumber] = @MerchantTaxIdentificationNumber,
  [CompanyNameCCD] = @CompanyNameCCD,
  [CompanyIdCCD] = @CompanyIdCCD,
  [CompanyEntryDescCCDDebit] = @CompanyEntryDescCCDDebit,
  [CompanyEntryDescCCDCredit] = @CompanyEntryDescCCDCredit,
  [DestRoutingTransitRefund] = @DestRoutingTransitRefund,
  [ACHIdRefund] = @ACHIdRefund,
  [OrigRoutingTransitRefund] = @OrigRoutingTransitRefund,
  [CompanyIdRefund] = @CompanyIdRefund,
  [DestRoutingTransitReward] = @DestRoutingTransitReward,
  [ACHIdReward] = @ACHIdReward,
  [OrigRoutingTransitReward] = @OrigRoutingTransitReward,
  [CompanyIdReward] = @CompanyIdReward,
  [ACHFileContent] = @ACHFileContent,
  [PODID] = @PODID,
  [SysSubOrgID] = @SysSubOrgID,
  [StmtCTDCombination] = @StmtCTDCombination,
  [StmtEODCombination] = @StmtEODCombination,
  [ProgramIdSBFE] = @ProgramIdSBFE,
  [BDCInDueDate] = @BDCInDueDate,
  [BDCInLateFeeDate] = @BDCInLateFeeDate,
  [MiniPodID] = @MiniPodID,
  [BackdatedPymtConsideration] = @BackdatedPymtConsideration,
  [BackdatedPymtConsiderationTime] = @BackdatedPymtConsiderationTime,
  [Sharding] = @Sharding,
  [MiniPODNumber] = @MiniPODNumber,
  [AsynchronousPosting] = @AsynchronousPosting,
  [HighBalanceRecalculation] = @HighBalanceRecalculation,
  [PHPCalculationLogicOn] = @PHPCalculationLogicOn,
  [PartnerName] = @PartnerName,
  [EODDataApproach] = @EODDataApproach,
  [RealTimePostingDuringEOM] = @RealTimePostingDuringEOM,
  [NewTNPQueue] = @NewTNPQueue,
  [CBRFrequency] = @CBRFrequency,
  [CBRDataFrom] = @CBRDataFrom,
  [CBRWeeklyPeriod] = @CBRWeeklyPeriod,
  [CBREventReporting] = @CBREventReporting,
  [CBRHonourStatus] = @CBRHonourStatus,
  [CBRUpdateCCC] = @CBRUpdateCCC,
  [CBRPaymentMade] = @CBRPaymentMade,
  [CBRUpdateSCC] = @CBRUpdateSCC,
  [CBRUpdateCII] = @CBRUpdateCII,
  [CBRUpdateBillngCycle] = @CBRUpdateBillngCycle,
  [TSDBOActive] = @TSDBOActive,
  [TSDBOAllowedMonths] = @TSDBOAllowedMonths,
  [TSDBOActiveDate] = @TSDBOActiveDate

WHERE 
   [acctId] = @acctId 
ELSE
INSERT INTO Org_Balances
 ( [acctId],
 [AmountOfDebitsDM1],
 [NumberOfDebitsDM1],
 [AmountOfCreditsDM1],
 [NumberOfCreditsDM1],
 [AmtGenDebitsDD1],
 [AmtGenCreditsDD1],
 [NbrGenDebitsDD1],
 [NbrGenCreditsDD1],
 [TotAmtCashPurAuthReqDD1],
 [TotAmtCashPurAuthReqDD2],
 [TotAmtCashPurAuthReqDD3],
 [TotNoCashPurAuthReqDD1],
 [TotNoCashPurAuthReqDD2],
 [TotNoCashPurAuthReqDD3],
 [PeriodPrefix],
 [ARSystemAcctId],
 [TimeZone],
 [DayLightSaving],
 [ProcessingDayEndTime],
 [CBRPortfolioType],
 [CBRAccountType],
 [PreferredLanguage],
 [CMTransactionHistoryUpto],
 [CMTransactionHistoryUpRange],
 [ACHCutoffTime],
 [NoOfTxnInACHFile],
 [SSRegistrationMethod],
 [SSForgetPasswordMethod],
 [SSForgetUserIDMethod],
 [SSDisputeAllowed],
 [ccinhparent136AID],
 [ccinhparent136ATID],
 [ccinhparent137AID],
 [ccinhparent137ATID],
 [ccinhparent138AID],
 [ccinhparent138ATID],
 [ccinhparent139AID],
 [ccinhparent139ATID],
 [ccinhparent140AID],
 [ccinhparent140ATID],
 [ccinhparent141AID],
 [ccinhparent141ATID],
 [ccinhparent142AID],
 [ccinhparent142ATID],
 [ccinhparent143AID],
 [ccinhparent143ATID],
 [ccinhparent144AID],
 [ccinhparent144ATID],
 [ccinhparent145AID],
 [ccinhparent145ATID],
 [ccinhparent146AID],
 [ccinhparent146ATID],
 [ccinhparent147AID],
 [ccinhparent147ATID],
 [BankVerificationMethod],
 [CEDAlignment],
 [CompanyEntryDescription],
 [CompanyID],
 [CompanyName],
 [CompanyNameAlignment],
 [ECCAlignment],
 [EntryClassCode],
 [CompanyIdAlignment],
 [DestinationAlignment],
 [DestinationRTAlignment],
 [OriginationAlignment],
 [TINAlignment],
 [DEKEncryptionRequired],
 [DEKEncryptionKey],
 [RefundDescription],
 [BillPayOriginatorsRFIID],
 [BillPayDestinationName],
 [HolidayConsideration],
 [AccountNumberGeneration],
 [AccountNumberPrefix],
 [AccountNumberPostValue],
 [WellsFargoBankABA],
 [WellsFargoBankName],
 [PreQual],
 [ChargeAssmtFee],
 [MerchantTaxIdentificationNumber],
 [CompanyNameCCD],
 [CompanyIdCCD],
 [CompanyEntryDescCCDDebit],
 [CompanyEntryDescCCDCredit],
 [DestRoutingTransitRefund],
 [ACHIdRefund],
 [OrigRoutingTransitRefund],
 [CompanyIdRefund],
 [DestRoutingTransitReward],
 [ACHIdReward],
 [OrigRoutingTransitReward],
 [CompanyIdReward],
 [ACHFileContent],
 [PODID],
 [SysSubOrgID],
 [StmtCTDCombination],
 [StmtEODCombination],
 [ProgramIdSBFE],
 [BDCInDueDate],
 [BDCInLateFeeDate],
 [MiniPodID],
 [BackdatedPymtConsideration],
 [BackdatedPymtConsiderationTime],
 [Sharding],
 [MiniPODNumber],
 [AsynchronousPosting],
 [HighBalanceRecalculation],
 [PHPCalculationLogicOn],
 [PartnerName],
 [EODDataApproach],
 [RealTimePostingDuringEOM],
 [NewTNPQueue],
 [CBRFrequency],
 [CBRDataFrom],
 [CBRWeeklyPeriod],
 [CBREventReporting],
 [CBRHonourStatus],
 [CBRUpdateCCC],
 [CBRPaymentMade],
 [CBRUpdateSCC],
 [CBRUpdateCII],
 [CBRUpdateBillngCycle],
 [TSDBOActive],
 [TSDBOAllowedMonths],
 [TSDBOActiveDate]) VALUES ( @acctId,
 @AmountOfDebitsDM1,
 @NumberOfDebitsDM1,
 @AmountOfCreditsDM1,
 @NumberOfCreditsDM1,
 @AmtGenDebitsDD1,
 @AmtGenCreditsDD1,
 @NbrGenDebitsDD1,
 @NbrGenCreditsDD1,
 @TotAmtCashPurAuthReqDD1,
 @TotAmtCashPurAuthReqDD2,
 @TotAmtCashPurAuthReqDD3,
 @TotNoCashPurAuthReqDD1,
 @TotNoCashPurAuthReqDD2,
 @TotNoCashPurAuthReqDD3,
 @PeriodPrefix,
 @ARSystemAcctId,
 @TimeZone,
 @DayLightSaving,
 @ProcessingDayEndTime,
 @CBRPortfolioType,
 @CBRAccountType,
 @PreferredLanguage,
 @CMTransactionHistoryUpto,
 @CMTransactionHistoryUpRange,
 @ACHCutoffTime,
 @NoOfTxnInACHFile,
 @SSRegistrationMethod,
 @SSForgetPasswordMethod,
 @SSForgetUserIDMethod,
 @SSDisputeAllowed,
 @ccinhparent136AID,
 @ccinhparent136ATID,
 @ccinhparent137AID,
 @ccinhparent137ATID,
 @ccinhparent138AID,
 @ccinhparent138ATID,
 @ccinhparent139AID,
 @ccinhparent139ATID,
 @ccinhparent140AID,
 @ccinhparent140ATID,
 @ccinhparent141AID,
 @ccinhparent141ATID,
 @ccinhparent142AID,
 @ccinhparent142ATID,
 @ccinhparent143AID,
 @ccinhparent143ATID,
 @ccinhparent144AID,
 @ccinhparent144ATID,
 @ccinhparent145AID,
 @ccinhparent145ATID,
 @ccinhparent146AID,
 @ccinhparent146ATID,
 @ccinhparent147AID,
 @ccinhparent147ATID,
 @BankVerificationMethod,
 @CEDAlignment,
 @CompanyEntryDescription,
 @CompanyID,
 @CompanyName,
 @CompanyNameAlignment,
 @ECCAlignment,
 @EntryClassCode,
 @CompanyIdAlignment,
 @DestinationAlignment,
 @DestinationRTAlignment,
 @OriginationAlignment,
 @TINAlignment,
 @DEKEncryptionRequired,
 @DEKEncryptionKey,
 @RefundDescription,
 @BillPayOriginatorsRFIID,
 @BillPayDestinationName,
 @HolidayConsideration,
 @AccountNumberGeneration,
 @AccountNumberPrefix,
 @AccountNumberPostValue,
 @WellsFargoBankABA,
 @WellsFargoBankName,
 @PreQual,
 @ChargeAssmtFee,
 @MerchantTaxIdentificationNumber,
 @CompanyNameCCD,
 @CompanyIdCCD,
 @CompanyEntryDescCCDDebit,
 @CompanyEntryDescCCDCredit,
 @DestRoutingTransitRefund,
 @ACHIdRefund,
 @OrigRoutingTransitRefund,
 @CompanyIdRefund,
 @DestRoutingTransitReward,
 @ACHIdReward,
 @OrigRoutingTransitReward,
 @CompanyIdReward,
 @ACHFileContent,
 @PODID,
 @SysSubOrgID,
 @StmtCTDCombination,
 @StmtEODCombination,
 @ProgramIdSBFE,
 @BDCInDueDate,
 @BDCInLateFeeDate,
 @MiniPodID,
 @BackdatedPymtConsideration,
 @BackdatedPymtConsiderationTime,
 @Sharding,
 @MiniPODNumber,
 @AsynchronousPosting,
 @HighBalanceRecalculation,
 @PHPCalculationLogicOn,
 @PartnerName,
 @EODDataApproach,
 @RealTimePostingDuringEOM,
 @NewTNPQueue,
 @CBRFrequency,
 @CBRDataFrom,
 @CBRWeeklyPeriod,
 @CBREventReporting,
 @CBRHonourStatus,
 @CBRUpdateCCC,
 @CBRPaymentMade,
 @CBRUpdateSCC,
 @CBRUpdateCII,
 @CBRUpdateBillngCycle,
 @TSDBOActive,
 @TSDBOAllowedMonths,
 @TSDBOActiveDate)
GO