/**********************************************************************************************************************
Purpose								: PLAT-259458
Author								: Prasoon Parashar
Date									: 09/08/2025
Application version					: Plat_25.10.3
Description							: Enhance high balance calculation logic
Review By							: Deepak Dharkar 
**********************************************************************************************************************/

CREATE OR ALTER PROCEDURE sp_CurrentStatementHeader_qsel(  @acctId int ,
  @StatementDate datetime ) AS
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET QUOTED_IDENTIFIER ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;
SELECT
 [acctId],
 [BeginningBalance],
 [CurrentBalance],
 [StatementDate],
 [ccinhparent101AID],
 [LateChargesCTD],
 [DateOfOriginalPaymentDueDTD],
 [AmountOfTotalDue],
 [AmtOfPayCurrDue],
 [AmtOfPayXDLate],
 [AmountOfPayment30DLate],
 [AmountOfPayment60DLate],
 [AmountOfPayment90DLate],
 [AmountOfPayment120DLate],
 [AmountOfPayment150DLate],
 [AmountOfPayment180DLate],
 [AmountOfPayment210DLate],
 [AmountOfPaymentsDTD],
 [ActualMinIntAmtComputed],
 [FillerMinIntAmt],
 [GraceCutoffDate],
 [BeginningBalanceUpdate],
 [NoOfConsecPymtsatStmt],
 [ConsecutiveDelinquentCycles],
 [AmountOfPaymentsCTD],
 [AmountOfPaymentsCC1],
 [AmountOfPaymentsCC2],
 [AmountOfPaymentsCC3],
 [AmountOfPaymentsCC4],
 [AmountOfPaymentsCC5],
 [NetInstallmentDueCTD],
 [NetInstallmentDueCC1],
 [NetInstallmentDueCC2],
 [NetInstallmentDueCC3],
 [NetInstallmentDueCC4],
 [NetInstallmentDueCC5],
 [BackDatedPayments],
 [BackCredit1CPDAmt],
 [ccinhparent102AID],
 [StatementTime],
 [ReageStatus],
 [AmountOfPayments_InCycle],
 [PaymentDuringReageCTD],
 [TCAPStatusNew],
 [AmtOfCrAdjSRBCTD],
 [AmtOfCrAdjMSBCTD],
 [DateOfNextStmt],
 [RowChangedDate],
 [PaymentDuringProgramCTD],
 [CreditsDuringProgramCTD],
 [ProgramStatus],
 [BankruptcyFilingDate],
 [ccinhparent125AID],
 [IntWaiveForSCRA],
 [IsAcctSCRA],
 [CBRAmountOfCurrentBalance],
 [CBRAmountOfHighBalance],
 [AmountOfCreditsCTD],
 [HoldTCAPSuspensionDuringCycle],
 [AdjustedCurrentBalance],
 [AdjustedHighBalance],
 [AdjustedTransactionAmount]
FROM CurrentStatementHeader
WHERE 
   [acctId] = @acctId  AND   [StatementDate] = @StatementDate 
GO

CREATE OR ALTER PROCEDURE sp_CurrentStatementHeader_qslk(  @acctId int ,
  @StatementDate datetime ) AS
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET QUOTED_IDENTIFIER ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;
SELECT
 [acctId],
 [BeginningBalance],
 [CurrentBalance],
 [StatementDate],
 [ccinhparent101AID],
 [LateChargesCTD],
 [DateOfOriginalPaymentDueDTD],
 [AmountOfTotalDue],
 [AmtOfPayCurrDue],
 [AmtOfPayXDLate],
 [AmountOfPayment30DLate],
 [AmountOfPayment60DLate],
 [AmountOfPayment90DLate],
 [AmountOfPayment120DLate],
 [AmountOfPayment150DLate],
 [AmountOfPayment180DLate],
 [AmountOfPayment210DLate],
 [AmountOfPaymentsDTD],
 [ActualMinIntAmtComputed],
 [FillerMinIntAmt],
 [GraceCutoffDate],
 [BeginningBalanceUpdate],
 [NoOfConsecPymtsatStmt],
 [ConsecutiveDelinquentCycles],
 [AmountOfPaymentsCTD],
 [AmountOfPaymentsCC1],
 [AmountOfPaymentsCC2],
 [AmountOfPaymentsCC3],
 [AmountOfPaymentsCC4],
 [AmountOfPaymentsCC5],
 [NetInstallmentDueCTD],
 [NetInstallmentDueCC1],
 [NetInstallmentDueCC2],
 [NetInstallmentDueCC3],
 [NetInstallmentDueCC4],
 [NetInstallmentDueCC5],
 [BackDatedPayments],
 [BackCredit1CPDAmt],
 [ccinhparent102AID],
 [StatementTime],
 [ReageStatus],
 [AmountOfPayments_InCycle],
 [PaymentDuringReageCTD],
 [TCAPStatusNew],
 [AmtOfCrAdjSRBCTD],
 [AmtOfCrAdjMSBCTD],
 [DateOfNextStmt],
 [RowChangedDate],
 [PaymentDuringProgramCTD],
 [CreditsDuringProgramCTD],
 [ProgramStatus],
 [BankruptcyFilingDate],
 [ccinhparent125AID],
 [IntWaiveForSCRA],
 [IsAcctSCRA],
 [CBRAmountOfCurrentBalance],
 [CBRAmountOfHighBalance],
 [AmountOfCreditsCTD],
 [HoldTCAPSuspensionDuringCycle],
 [AdjustedCurrentBalance],
 [AdjustedHighBalance],
 [AdjustedTransactionAmount]
FROM CurrentStatementHeader with (updlock)
WHERE 
   [acctId] = @acctId  AND   [StatementDate] = @StatementDate 
GO

CREATE OR ALTER PROCEDURE sp_CurrentStatementHeader_sel AS
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET QUOTED_IDENTIFIER ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;

SELECT [acctId],
 [BeginningBalance],
 [CurrentBalance],
 [StatementDate],
 [ccinhparent101AID],
 [LateChargesCTD],
 [DateOfOriginalPaymentDueDTD],
 [AmountOfTotalDue],
 [AmtOfPayCurrDue],
 [AmtOfPayXDLate],
 [AmountOfPayment30DLate],
 [AmountOfPayment60DLate],
 [AmountOfPayment90DLate],
 [AmountOfPayment120DLate],
 [AmountOfPayment150DLate],
 [AmountOfPayment180DLate],
 [AmountOfPayment210DLate],
 [AmountOfPaymentsDTD],
 [ActualMinIntAmtComputed],
 [FillerMinIntAmt],
 [GraceCutoffDate],
 [BeginningBalanceUpdate],
 [NoOfConsecPymtsatStmt],
 [ConsecutiveDelinquentCycles],
 [AmountOfPaymentsCTD],
 [AmountOfPaymentsCC1],
 [AmountOfPaymentsCC2],
 [AmountOfPaymentsCC3],
 [AmountOfPaymentsCC4],
 [AmountOfPaymentsCC5],
 [NetInstallmentDueCTD],
 [NetInstallmentDueCC1],
 [NetInstallmentDueCC2],
 [NetInstallmentDueCC3],
 [NetInstallmentDueCC4],
 [NetInstallmentDueCC5],
 [BackDatedPayments],
 [BackCredit1CPDAmt],
 [ccinhparent102AID],
 [StatementTime],
 [ReageStatus],
 [AmountOfPayments_InCycle],
 [PaymentDuringReageCTD],
 [TCAPStatusNew],
 [AmtOfCrAdjSRBCTD],
 [AmtOfCrAdjMSBCTD],
 [DateOfNextStmt],
 [RowChangedDate],
 [PaymentDuringProgramCTD],
 [CreditsDuringProgramCTD],
 [ProgramStatus],
 [BankruptcyFilingDate],
 [ccinhparent125AID],
 [IntWaiveForSCRA],
 [IsAcctSCRA],
 [CBRAmountOfCurrentBalance],
 [CBRAmountOfHighBalance],
 [AmountOfCreditsCTD],
 [HoldTCAPSuspensionDuringCycle],
 [AdjustedCurrentBalance],
 [AdjustedHighBalance],
 [AdjustedTransactionAmount]
FROM CurrentStatementHeader WITH (NOLOCK)
GO

CREATE OR ALTER PROCEDURE sp_CurrentStatementHeader_del(  @acctId int ,
  @StatementDate datetime ) AS
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET QUOTED_IDENTIFIER ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;
DELETE FROM CurrentStatementHeader
WHERE 
   [acctId] = @acctId  AND   [StatementDate] = @StatementDate 
GO

CREATE OR ALTER PROCEDURE sp_CurrentStatementHeader_upd  @acctId int,
  @BeginningBalance money,
  @CurrentBalance money,
  @StatementDate datetime,
  @ccinhparent101AID int,
  @LateChargesCTD money,
  @DateOfOriginalPaymentDueDTD datetime,
  @AmountOfTotalDue money,
  @AmtOfPayCurrDue money,
  @AmtOfPayXDLate money,
  @AmountOfPayment30DLate money,
  @AmountOfPayment60DLate money,
  @AmountOfPayment90DLate money,
  @AmountOfPayment120DLate money,
  @AmountOfPayment150DLate money,
  @AmountOfPayment180DLate money,
  @AmountOfPayment210DLate money,
  @AmountOfPaymentsDTD money,
  @ActualMinIntAmtComputed money,
  @FillerMinIntAmt money,
  @GraceCutoffDate datetime,
  @BeginningBalanceUpdate money,
  @NoOfConsecPymtsatStmt int,
  @ConsecutiveDelinquentCycles int,
  @AmountOfPaymentsCTD money,
  @AmountOfPaymentsCC1 money,
  @AmountOfPaymentsCC2 money,
  @AmountOfPaymentsCC3 money,
  @AmountOfPaymentsCC4 money,
  @AmountOfPaymentsCC5 money,
  @NetInstallmentDueCTD money,
  @NetInstallmentDueCC1 money,
  @NetInstallmentDueCC2 money,
  @NetInstallmentDueCC3 money,
  @NetInstallmentDueCC4 money,
  @NetInstallmentDueCC5 money,
  @BackDatedPayments money,
  @BackCredit1CPDAmt money,
  @ccinhparent102AID int,
  @StatementTime datetime,
  @ReageStatus int,
  @AmountOfPayments_InCycle money,
  @PaymentDuringReageCTD money,
  @TCAPStatusNew int,
  @AmtOfCrAdjSRBCTD money,
  @AmtOfCrAdjMSBCTD money,
  @DateOfNextStmt datetime,
  @RowChangedDate datetime,
  @PaymentDuringProgramCTD money,
  @CreditsDuringProgramCTD money,
  @ProgramStatus int,
  @BankruptcyFilingDate datetime,
  @ccinhparent125AID int,
  @IntWaiveForSCRA int,
  @IsAcctSCRA tinyint,
  @CBRAmountOfCurrentBalance money,
  @CBRAmountOfHighBalance money,
  @AmountOfCreditsCTD money,
  @HoldTCAPSuspensionDuringCycle varchar (4),
  @AdjustedCurrentBalance money,
  @AdjustedHighBalance money,
  @AdjustedTransactionAmount money AS
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET QUOTED_IDENTIFIER ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;
SET NOCOUNT OFF;
 UPDATE CurrentStatementHeader SET   [acctId] = @acctId,
  [BeginningBalance] = @BeginningBalance,
  [CurrentBalance] = @CurrentBalance,
  [StatementDate] = @StatementDate,
  [ccinhparent101AID] = @ccinhparent101AID,
  [LateChargesCTD] = @LateChargesCTD,
  [DateOfOriginalPaymentDueDTD] = @DateOfOriginalPaymentDueDTD,
  [AmountOfTotalDue] = @AmountOfTotalDue,
  [AmtOfPayCurrDue] = @AmtOfPayCurrDue,
  [AmtOfPayXDLate] = @AmtOfPayXDLate,
  [AmountOfPayment30DLate] = @AmountOfPayment30DLate,
  [AmountOfPayment60DLate] = @AmountOfPayment60DLate,
  [AmountOfPayment90DLate] = @AmountOfPayment90DLate,
  [AmountOfPayment120DLate] = @AmountOfPayment120DLate,
  [AmountOfPayment150DLate] = @AmountOfPayment150DLate,
  [AmountOfPayment180DLate] = @AmountOfPayment180DLate,
  [AmountOfPayment210DLate] = @AmountOfPayment210DLate,
  [AmountOfPaymentsDTD] = @AmountOfPaymentsDTD,
  [ActualMinIntAmtComputed] = @ActualMinIntAmtComputed,
  [FillerMinIntAmt] = @FillerMinIntAmt,
  [GraceCutoffDate] = @GraceCutoffDate,
  [BeginningBalanceUpdate] = @BeginningBalanceUpdate,
  [NoOfConsecPymtsatStmt] = @NoOfConsecPymtsatStmt,
  [ConsecutiveDelinquentCycles] = @ConsecutiveDelinquentCycles,
  [AmountOfPaymentsCTD] = @AmountOfPaymentsCTD,
  [AmountOfPaymentsCC1] = @AmountOfPaymentsCC1,
  [AmountOfPaymentsCC2] = @AmountOfPaymentsCC2,
  [AmountOfPaymentsCC3] = @AmountOfPaymentsCC3,
  [AmountOfPaymentsCC4] = @AmountOfPaymentsCC4,
  [AmountOfPaymentsCC5] = @AmountOfPaymentsCC5,
  [NetInstallmentDueCTD] = @NetInstallmentDueCTD,
  [NetInstallmentDueCC1] = @NetInstallmentDueCC1,
  [NetInstallmentDueCC2] = @NetInstallmentDueCC2,
  [NetInstallmentDueCC3] = @NetInstallmentDueCC3,
  [NetInstallmentDueCC4] = @NetInstallmentDueCC4,
  [NetInstallmentDueCC5] = @NetInstallmentDueCC5,
  [BackDatedPayments] = @BackDatedPayments,
  [BackCredit1CPDAmt] = @BackCredit1CPDAmt,
  [ccinhparent102AID] = @ccinhparent102AID,
  [StatementTime] = @StatementTime,
  [ReageStatus] = @ReageStatus,
  [AmountOfPayments_InCycle] = @AmountOfPayments_InCycle,
  [PaymentDuringReageCTD] = @PaymentDuringReageCTD,
  [TCAPStatusNew] = @TCAPStatusNew,
  [AmtOfCrAdjSRBCTD] = @AmtOfCrAdjSRBCTD,
  [AmtOfCrAdjMSBCTD] = @AmtOfCrAdjMSBCTD,
  [DateOfNextStmt] = @DateOfNextStmt,
  [RowChangedDate] = @RowChangedDate,
  [PaymentDuringProgramCTD] = @PaymentDuringProgramCTD,
  [CreditsDuringProgramCTD] = @CreditsDuringProgramCTD,
  [ProgramStatus] = @ProgramStatus,
  [BankruptcyFilingDate] = @BankruptcyFilingDate,
  [ccinhparent125AID] = @ccinhparent125AID,
  [IntWaiveForSCRA] = @IntWaiveForSCRA,
  [IsAcctSCRA] = @IsAcctSCRA,
  [CBRAmountOfCurrentBalance] = @CBRAmountOfCurrentBalance,
  [CBRAmountOfHighBalance] = @CBRAmountOfHighBalance,
  [AmountOfCreditsCTD] = @AmountOfCreditsCTD,
  [HoldTCAPSuspensionDuringCycle] = @HoldTCAPSuspensionDuringCycle,
  [AdjustedCurrentBalance] = @AdjustedCurrentBalance,
  [AdjustedHighBalance] = @AdjustedHighBalance,
  [AdjustedTransactionAmount] = @AdjustedTransactionAmount 
WHERE 
   [acctId] = @acctId  AND   [StatementDate] = @StatementDate 
GO

CREATE OR ALTER PROCEDURE sp_CurrentStatementHeader_ins (
  @acctId int,
  @BeginningBalance money,
  @CurrentBalance money,
  @StatementDate datetime,
  @ccinhparent101AID int,
  @LateChargesCTD money,
  @DateOfOriginalPaymentDueDTD datetime,
  @AmountOfTotalDue money,
  @AmtOfPayCurrDue money,
  @AmtOfPayXDLate money,
  @AmountOfPayment30DLate money,
  @AmountOfPayment60DLate money,
  @AmountOfPayment90DLate money,
  @AmountOfPayment120DLate money,
  @AmountOfPayment150DLate money,
  @AmountOfPayment180DLate money,
  @AmountOfPayment210DLate money,
  @AmountOfPaymentsDTD money,
  @ActualMinIntAmtComputed money,
  @FillerMinIntAmt money,
  @GraceCutoffDate datetime,
  @BeginningBalanceUpdate money,
  @NoOfConsecPymtsatStmt int,
  @ConsecutiveDelinquentCycles int,
  @AmountOfPaymentsCTD money,
  @AmountOfPaymentsCC1 money,
  @AmountOfPaymentsCC2 money,
  @AmountOfPaymentsCC3 money,
  @AmountOfPaymentsCC4 money,
  @AmountOfPaymentsCC5 money,
  @NetInstallmentDueCTD money,
  @NetInstallmentDueCC1 money,
  @NetInstallmentDueCC2 money,
  @NetInstallmentDueCC3 money,
  @NetInstallmentDueCC4 money,
  @NetInstallmentDueCC5 money,
  @BackDatedPayments money,
  @BackCredit1CPDAmt money,
  @ccinhparent102AID int,
  @StatementTime datetime,
  @ReageStatus int,
  @AmountOfPayments_InCycle money,
  @PaymentDuringReageCTD money,
  @TCAPStatusNew int,
  @AmtOfCrAdjSRBCTD money,
  @AmtOfCrAdjMSBCTD money,
  @DateOfNextStmt datetime,
  @RowChangedDate datetime,
  @PaymentDuringProgramCTD money,
  @CreditsDuringProgramCTD money,
  @ProgramStatus int,
  @BankruptcyFilingDate datetime,
  @ccinhparent125AID int,
  @IntWaiveForSCRA int,
  @IsAcctSCRA tinyint,
  @CBRAmountOfCurrentBalance money,
  @CBRAmountOfHighBalance money,
  @AmountOfCreditsCTD money,
  @HoldTCAPSuspensionDuringCycle varchar (4),
  @AdjustedCurrentBalance money,
  @AdjustedHighBalance money,
  @AdjustedTransactionAmount money)
AS
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET QUOTED_IDENTIFIER ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;
 INSERT INTO CurrentStatementHeader 
(  [acctId],
 [BeginningBalance],
 [CurrentBalance],
 [StatementDate],
 [ccinhparent101AID],
 [LateChargesCTD],
 [DateOfOriginalPaymentDueDTD],
 [AmountOfTotalDue],
 [AmtOfPayCurrDue],
 [AmtOfPayXDLate],
 [AmountOfPayment30DLate],
 [AmountOfPayment60DLate],
 [AmountOfPayment90DLate],
 [AmountOfPayment120DLate],
 [AmountOfPayment150DLate],
 [AmountOfPayment180DLate],
 [AmountOfPayment210DLate],
 [AmountOfPaymentsDTD],
 [ActualMinIntAmtComputed],
 [FillerMinIntAmt],
 [GraceCutoffDate],
 [BeginningBalanceUpdate],
 [NoOfConsecPymtsatStmt],
 [ConsecutiveDelinquentCycles],
 [AmountOfPaymentsCTD],
 [AmountOfPaymentsCC1],
 [AmountOfPaymentsCC2],
 [AmountOfPaymentsCC3],
 [AmountOfPaymentsCC4],
 [AmountOfPaymentsCC5],
 [NetInstallmentDueCTD],
 [NetInstallmentDueCC1],
 [NetInstallmentDueCC2],
 [NetInstallmentDueCC3],
 [NetInstallmentDueCC4],
 [NetInstallmentDueCC5],
 [BackDatedPayments],
 [BackCredit1CPDAmt],
 [ccinhparent102AID],
 [StatementTime],
 [ReageStatus],
 [AmountOfPayments_InCycle],
 [PaymentDuringReageCTD],
 [TCAPStatusNew],
 [AmtOfCrAdjSRBCTD],
 [AmtOfCrAdjMSBCTD],
 [DateOfNextStmt],
 [RowChangedDate],
 [PaymentDuringProgramCTD],
 [CreditsDuringProgramCTD],
 [ProgramStatus],
 [BankruptcyFilingDate],
 [ccinhparent125AID],
 [IntWaiveForSCRA],
 [IsAcctSCRA],
 [CBRAmountOfCurrentBalance],
 [CBRAmountOfHighBalance],
 [AmountOfCreditsCTD],
 [HoldTCAPSuspensionDuringCycle],
 [AdjustedCurrentBalance],
 [AdjustedHighBalance],
 [AdjustedTransactionAmount])
VALUES (  @acctId,
 @BeginningBalance,
 @CurrentBalance,
 @StatementDate,
 @ccinhparent101AID,
 @LateChargesCTD,
 @DateOfOriginalPaymentDueDTD,
 @AmountOfTotalDue,
 @AmtOfPayCurrDue,
 @AmtOfPayXDLate,
 @AmountOfPayment30DLate,
 @AmountOfPayment60DLate,
 @AmountOfPayment90DLate,
 @AmountOfPayment120DLate,
 @AmountOfPayment150DLate,
 @AmountOfPayment180DLate,
 @AmountOfPayment210DLate,
 @AmountOfPaymentsDTD,
 @ActualMinIntAmtComputed,
 @FillerMinIntAmt,
 @GraceCutoffDate,
 @BeginningBalanceUpdate,
 @NoOfConsecPymtsatStmt,
 @ConsecutiveDelinquentCycles,
 @AmountOfPaymentsCTD,
 @AmountOfPaymentsCC1,
 @AmountOfPaymentsCC2,
 @AmountOfPaymentsCC3,
 @AmountOfPaymentsCC4,
 @AmountOfPaymentsCC5,
 @NetInstallmentDueCTD,
 @NetInstallmentDueCC1,
 @NetInstallmentDueCC2,
 @NetInstallmentDueCC3,
 @NetInstallmentDueCC4,
 @NetInstallmentDueCC5,
 @BackDatedPayments,
 @BackCredit1CPDAmt,
 @ccinhparent102AID,
 @StatementTime,
 @ReageStatus,
 @AmountOfPayments_InCycle,
 @PaymentDuringReageCTD,
 @TCAPStatusNew,
 @AmtOfCrAdjSRBCTD,
 @AmtOfCrAdjMSBCTD,
 @DateOfNextStmt,
 @RowChangedDate,
 @PaymentDuringProgramCTD,
 @CreditsDuringProgramCTD,
 @ProgramStatus,
 @BankruptcyFilingDate,
 @ccinhparent125AID,
 @IntWaiveForSCRA,
 @IsAcctSCRA,
 @CBRAmountOfCurrentBalance,
 @CBRAmountOfHighBalance,
 @AmountOfCreditsCTD,
 @HoldTCAPSuspensionDuringCycle,
 @AdjustedCurrentBalance,
 @AdjustedHighBalance,
 @AdjustedTransactionAmount)
GO

CREATE OR ALTER PROCEDURE sp_CurrentStatementHeader_insupd (  @acctId int,
  @BeginningBalance money,
  @CurrentBalance money,
  @StatementDate datetime,
  @ccinhparent101AID int,
  @LateChargesCTD money,
  @DateOfOriginalPaymentDueDTD datetime,
  @AmountOfTotalDue money,
  @AmtOfPayCurrDue money,
  @AmtOfPayXDLate money,
  @AmountOfPayment30DLate money,
  @AmountOfPayment60DLate money,
  @AmountOfPayment90DLate money,
  @AmountOfPayment120DLate money,
  @AmountOfPayment150DLate money,
  @AmountOfPayment180DLate money,
  @AmountOfPayment210DLate money,
  @AmountOfPaymentsDTD money,
  @ActualMinIntAmtComputed money,
  @FillerMinIntAmt money,
  @GraceCutoffDate datetime,
  @BeginningBalanceUpdate money,
  @NoOfConsecPymtsatStmt int,
  @ConsecutiveDelinquentCycles int,
  @AmountOfPaymentsCTD money,
  @AmountOfPaymentsCC1 money,
  @AmountOfPaymentsCC2 money,
  @AmountOfPaymentsCC3 money,
  @AmountOfPaymentsCC4 money,
  @AmountOfPaymentsCC5 money,
  @NetInstallmentDueCTD money,
  @NetInstallmentDueCC1 money,
  @NetInstallmentDueCC2 money,
  @NetInstallmentDueCC3 money,
  @NetInstallmentDueCC4 money,
  @NetInstallmentDueCC5 money,
  @BackDatedPayments money,
  @BackCredit1CPDAmt money,
  @ccinhparent102AID int,
  @StatementTime datetime,
  @ReageStatus int,
  @AmountOfPayments_InCycle money,
  @PaymentDuringReageCTD money,
  @TCAPStatusNew int,
  @AmtOfCrAdjSRBCTD money,
  @AmtOfCrAdjMSBCTD money,
  @DateOfNextStmt datetime,
  @RowChangedDate datetime,
  @PaymentDuringProgramCTD money,
  @CreditsDuringProgramCTD money,
  @ProgramStatus int,
  @BankruptcyFilingDate datetime,
  @ccinhparent125AID int,
  @IntWaiveForSCRA int,
  @IsAcctSCRA tinyint,
  @CBRAmountOfCurrentBalance money,
  @CBRAmountOfHighBalance money,
  @AmountOfCreditsCTD money,
  @HoldTCAPSuspensionDuringCycle varchar (4),
  @AdjustedCurrentBalance money,
  @AdjustedHighBalance money,
  @AdjustedTransactionAmount money) AS
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET QUOTED_IDENTIFIER ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;
SET NOCOUNT OFF;

IF EXISTS (SELECT [acctId] FROM CurrentStatementHeader WHERE 
   [acctId] = @acctId  AND   [StatementDate] = @StatementDate 
)
UPDATE CurrentStatementHeader SET  [acctId] = @acctId,
  [BeginningBalance] = @BeginningBalance,
  [CurrentBalance] = @CurrentBalance,
  [StatementDate] = @StatementDate,
  [ccinhparent101AID] = @ccinhparent101AID,
  [LateChargesCTD] = @LateChargesCTD,
  [DateOfOriginalPaymentDueDTD] = @DateOfOriginalPaymentDueDTD,
  [AmountOfTotalDue] = @AmountOfTotalDue,
  [AmtOfPayCurrDue] = @AmtOfPayCurrDue,
  [AmtOfPayXDLate] = @AmtOfPayXDLate,
  [AmountOfPayment30DLate] = @AmountOfPayment30DLate,
  [AmountOfPayment60DLate] = @AmountOfPayment60DLate,
  [AmountOfPayment90DLate] = @AmountOfPayment90DLate,
  [AmountOfPayment120DLate] = @AmountOfPayment120DLate,
  [AmountOfPayment150DLate] = @AmountOfPayment150DLate,
  [AmountOfPayment180DLate] = @AmountOfPayment180DLate,
  [AmountOfPayment210DLate] = @AmountOfPayment210DLate,
  [AmountOfPaymentsDTD] = @AmountOfPaymentsDTD,
  [ActualMinIntAmtComputed] = @ActualMinIntAmtComputed,
  [FillerMinIntAmt] = @FillerMinIntAmt,
  [GraceCutoffDate] = @GraceCutoffDate,
  [BeginningBalanceUpdate] = @BeginningBalanceUpdate,
  [NoOfConsecPymtsatStmt] = @NoOfConsecPymtsatStmt,
  [ConsecutiveDelinquentCycles] = @ConsecutiveDelinquentCycles,
  [AmountOfPaymentsCTD] = @AmountOfPaymentsCTD,
  [AmountOfPaymentsCC1] = @AmountOfPaymentsCC1,
  [AmountOfPaymentsCC2] = @AmountOfPaymentsCC2,
  [AmountOfPaymentsCC3] = @AmountOfPaymentsCC3,
  [AmountOfPaymentsCC4] = @AmountOfPaymentsCC4,
  [AmountOfPaymentsCC5] = @AmountOfPaymentsCC5,
  [NetInstallmentDueCTD] = @NetInstallmentDueCTD,
  [NetInstallmentDueCC1] = @NetInstallmentDueCC1,
  [NetInstallmentDueCC2] = @NetInstallmentDueCC2,
  [NetInstallmentDueCC3] = @NetInstallmentDueCC3,
  [NetInstallmentDueCC4] = @NetInstallmentDueCC4,
  [NetInstallmentDueCC5] = @NetInstallmentDueCC5,
  [BackDatedPayments] = @BackDatedPayments,
  [BackCredit1CPDAmt] = @BackCredit1CPDAmt,
  [ccinhparent102AID] = @ccinhparent102AID,
  [StatementTime] = @StatementTime,
  [ReageStatus] = @ReageStatus,
  [AmountOfPayments_InCycle] = @AmountOfPayments_InCycle,
  [PaymentDuringReageCTD] = @PaymentDuringReageCTD,
  [TCAPStatusNew] = @TCAPStatusNew,
  [AmtOfCrAdjSRBCTD] = @AmtOfCrAdjSRBCTD,
  [AmtOfCrAdjMSBCTD] = @AmtOfCrAdjMSBCTD,
  [DateOfNextStmt] = @DateOfNextStmt,
  [RowChangedDate] = @RowChangedDate,
  [PaymentDuringProgramCTD] = @PaymentDuringProgramCTD,
  [CreditsDuringProgramCTD] = @CreditsDuringProgramCTD,
  [ProgramStatus] = @ProgramStatus,
  [BankruptcyFilingDate] = @BankruptcyFilingDate,
  [ccinhparent125AID] = @ccinhparent125AID,
  [IntWaiveForSCRA] = @IntWaiveForSCRA,
  [IsAcctSCRA] = @IsAcctSCRA,
  [CBRAmountOfCurrentBalance] = @CBRAmountOfCurrentBalance,
  [CBRAmountOfHighBalance] = @CBRAmountOfHighBalance,
  [AmountOfCreditsCTD] = @AmountOfCreditsCTD,
  [HoldTCAPSuspensionDuringCycle] = @HoldTCAPSuspensionDuringCycle,
  [AdjustedCurrentBalance] = @AdjustedCurrentBalance,
  [AdjustedHighBalance] = @AdjustedHighBalance,
  [AdjustedTransactionAmount] = @AdjustedTransactionAmount

WHERE 
   [acctId] = @acctId  AND   [StatementDate] = @StatementDate 
ELSE
INSERT INTO CurrentStatementHeader
 ( [acctId],
 [BeginningBalance],
 [CurrentBalance],
 [StatementDate],
 [ccinhparent101AID],
 [LateChargesCTD],
 [DateOfOriginalPaymentDueDTD],
 [AmountOfTotalDue],
 [AmtOfPayCurrDue],
 [AmtOfPayXDLate],
 [AmountOfPayment30DLate],
 [AmountOfPayment60DLate],
 [AmountOfPayment90DLate],
 [AmountOfPayment120DLate],
 [AmountOfPayment150DLate],
 [AmountOfPayment180DLate],
 [AmountOfPayment210DLate],
 [AmountOfPaymentsDTD],
 [ActualMinIntAmtComputed],
 [FillerMinIntAmt],
 [GraceCutoffDate],
 [BeginningBalanceUpdate],
 [NoOfConsecPymtsatStmt],
 [ConsecutiveDelinquentCycles],
 [AmountOfPaymentsCTD],
 [AmountOfPaymentsCC1],
 [AmountOfPaymentsCC2],
 [AmountOfPaymentsCC3],
 [AmountOfPaymentsCC4],
 [AmountOfPaymentsCC5],
 [NetInstallmentDueCTD],
 [NetInstallmentDueCC1],
 [NetInstallmentDueCC2],
 [NetInstallmentDueCC3],
 [NetInstallmentDueCC4],
 [NetInstallmentDueCC5],
 [BackDatedPayments],
 [BackCredit1CPDAmt],
 [ccinhparent102AID],
 [StatementTime],
 [ReageStatus],
 [AmountOfPayments_InCycle],
 [PaymentDuringReageCTD],
 [TCAPStatusNew],
 [AmtOfCrAdjSRBCTD],
 [AmtOfCrAdjMSBCTD],
 [DateOfNextStmt],
 [RowChangedDate],
 [PaymentDuringProgramCTD],
 [CreditsDuringProgramCTD],
 [ProgramStatus],
 [BankruptcyFilingDate],
 [ccinhparent125AID],
 [IntWaiveForSCRA],
 [IsAcctSCRA],
 [CBRAmountOfCurrentBalance],
 [CBRAmountOfHighBalance],
 [AmountOfCreditsCTD],
 [HoldTCAPSuspensionDuringCycle],
 [AdjustedCurrentBalance],
 [AdjustedHighBalance],
 [AdjustedTransactionAmount]) VALUES ( @acctId,
 @BeginningBalance,
 @CurrentBalance,
 @StatementDate,
 @ccinhparent101AID,
 @LateChargesCTD,
 @DateOfOriginalPaymentDueDTD,
 @AmountOfTotalDue,
 @AmtOfPayCurrDue,
 @AmtOfPayXDLate,
 @AmountOfPayment30DLate,
 @AmountOfPayment60DLate,
 @AmountOfPayment90DLate,
 @AmountOfPayment120DLate,
 @AmountOfPayment150DLate,
 @AmountOfPayment180DLate,
 @AmountOfPayment210DLate,
 @AmountOfPaymentsDTD,
 @ActualMinIntAmtComputed,
 @FillerMinIntAmt,
 @GraceCutoffDate,
 @BeginningBalanceUpdate,
 @NoOfConsecPymtsatStmt,
 @ConsecutiveDelinquentCycles,
 @AmountOfPaymentsCTD,
 @AmountOfPaymentsCC1,
 @AmountOfPaymentsCC2,
 @AmountOfPaymentsCC3,
 @AmountOfPaymentsCC4,
 @AmountOfPaymentsCC5,
 @NetInstallmentDueCTD,
 @NetInstallmentDueCC1,
 @NetInstallmentDueCC2,
 @NetInstallmentDueCC3,
 @NetInstallmentDueCC4,
 @NetInstallmentDueCC5,
 @BackDatedPayments,
 @BackCredit1CPDAmt,
 @ccinhparent102AID,
 @StatementTime,
 @ReageStatus,
 @AmountOfPayments_InCycle,
 @PaymentDuringReageCTD,
 @TCAPStatusNew,
 @AmtOfCrAdjSRBCTD,
 @AmtOfCrAdjMSBCTD,
 @DateOfNextStmt,
 @RowChangedDate,
 @PaymentDuringProgramCTD,
 @CreditsDuringProgramCTD,
 @ProgramStatus,
 @BankruptcyFilingDate,
 @ccinhparent125AID,
 @IntWaiveForSCRA,
 @IsAcctSCRA,
 @CBRAmountOfCurrentBalance,
 @CBRAmountOfHighBalance,
 @AmountOfCreditsCTD,
 @HoldTCAPSuspensionDuringCycle,
 @AdjustedCurrentBalance,
 @AdjustedHighBalance,
 @AdjustedTransactionAmount)
GO