BEGIN TRANSACTION

--COMMIT
--ROLLBACK

UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2581795 AND DaysDelinquent = 93
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 93 WHERE Acctid = 326345 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 9869297 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2030535 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 3 ,NoPayDaysDelinquent = 3 WHERE Acctid = 4562521 AND DaysDelinquent = 4
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 62 WHERE Acctid = 2628898 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2653125 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 11041924 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2657029 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 9510042 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 8490298 AND DaysDelinquent = 93
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2478374 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 61 ,NoPayDaysDelinquent = 92 WHERE Acctid = 1964046 AND DaysDelinquent = 62
UPDATE BSegmentCreditCard SET DaysDelinquent = 61 ,NoPayDaysDelinquent = 151 WHERE Acctid = 1154079 AND DaysDelinquent = 62
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1223016 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 196218 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 211509 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 153 ,NoPayDaysDelinquent = 184 WHERE Acctid = 342352 AND DaysDelinquent = 154
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1199366 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1201777 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1139552 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1185242 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1678469 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1048934 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 279558 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 93 WHERE Acctid = 416134 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 3 ,NoPayDaysDelinquent = 186 WHERE Acctid = 433394 AND DaysDelinquent = 4
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1674264 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 510408 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 513409 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 202264 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 202791 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 175415 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4711559 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 32 ,NoPayDaysDelinquent = 32 WHERE Acctid = 69957 AND DaysDelinquent = 45
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 8283778 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3638925 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4685508 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1862175 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4698580 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4334412 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4342561 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1931062 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3630527 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2604156 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4936780 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 5521970 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1212891 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1224073 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1191867 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1216710 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1216887 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1046826 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 1108460 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1154772 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4371140 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 61 ,NoPayDaysDelinquent = 61 WHERE Acctid = 1048952 AND DaysDelinquent = 62
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 1182116 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4645490 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 62 WHERE Acctid = 4689535 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4612648 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 9856735 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2633675 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2015265 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 0 ,NoPayDaysDelinquent = 0 WHERE Acctid = 2016446 AND DaysDelinquent = 31
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 11310475 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1890834 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2682134 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 0 ,NoPayDaysDelinquent = 0 WHERE Acctid = 10344711 AND DaysDelinquent = 31
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1888832 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 0 ,NoPayDaysDelinquent = 0 WHERE Acctid = 2549861 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 0 ,NoPayDaysDelinquent = 0 WHERE Acctid = 4108934 AND DaysDelinquent = 31
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4127695 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 94 ,NoPayDaysDelinquent = 94 WHERE Acctid = 4425519 AND DaysDelinquent = 93
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3864982 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4124645 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 451843 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4254016 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 93 ,NoPayDaysDelinquent = 93 WHERE Acctid = 5519439 AND DaysDelinquent = 92
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3883623 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 6734101 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 440845 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 2 ,NoPayDaysDelinquent = 2 WHERE Acctid = 3520133 AND DaysDelinquent = 33
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3521944 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 62 WHERE Acctid = 4453557 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 508958 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3624817 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3625482 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1965219 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 11411445 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 11544649 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 11544810 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1911828 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 11402436 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 11406700 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2571604 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 576956 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 9442741 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 284115 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 312668 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2136425 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2140478 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2195985 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1206676 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 153 ,NoPayDaysDelinquent = 213 WHERE Acctid = 1207660 AND DaysDelinquent = 154
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1206290 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1216502 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1216854 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 201947 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1198763 AND DaysDelinquent = 93
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4664152 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 343939 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1153646 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1220755 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 63388 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 283841 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 153 ,NoPayDaysDelinquent = 184 WHERE Acctid = 1222125 AND DaysDelinquent = 154
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4301608 AND DaysDelinquent = 0
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4841969 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 433403 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 274881 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 274963 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 10270859 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 61 ,NoPayDaysDelinquent = 61 WHERE Acctid = 5740089 AND DaysDelinquent = 62
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1081430 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 282037 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1142304 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1858465 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1902609 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1189460 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1200985 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 1220923 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2555765 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2213568 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 6105075 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 94 WHERE Acctid = 6498469 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 30 ,NoPayDaysDelinquent = 61 WHERE Acctid = 286422 AND DaysDelinquent = 31
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3746311 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 3 ,NoPayDaysDelinquent = 3 WHERE Acctid = 10926683 AND DaysDelinquent = 34
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 11083883 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2622356 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 11209152 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2643132 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2655132 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 2 ,NoPayDaysDelinquent = 2 WHERE Acctid = 195477 AND DaysDelinquent = 3
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 2677561 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2684478 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2692903 AND DaysDelinquent = 93
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4722853 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4930716 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4712382 AND DaysDelinquent = 93
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4902397 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4821530 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 4243775 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1053770 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1053787 AND DaysDelinquent = 93
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1156032 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4808895 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1182858 AND DaysDelinquent = 93
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4357355 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1155345 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1202187 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4630735 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 8014125 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1764774 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2004832 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1198022 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1139879 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1145931 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1991098 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1991264 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1153551 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1155137 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1183180 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 1954143 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 308501 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 1975112 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2168958 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 232375 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 62 WHERE Acctid = 4834923 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1334128 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2050810 AND DaysDelinquent = 93
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2185814 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1343337 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 11500475 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1902402 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1224360 AND DaysDelinquent = 0
UPDATE BSegmentCreditCard SET DaysDelinquent = 3 ,NoPayDaysDelinquent = 3 WHERE Acctid = 2126273 AND DaysDelinquent = 4
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 11311590 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3809484 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 61 ,NoPayDaysDelinquent = 61 WHERE Acctid = 3761571 AND DaysDelinquent = 62
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4245419 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 9415005 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2685881 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 216915 AND DaysDelinquent = 93
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2603892 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 9493805 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 303251 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2643263 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1192098 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4324158 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4809018 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4930049 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 8181868 AND DaysDelinquent = 93
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1183954 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4902964 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 4907394 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1213112 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 153 ,NoPayDaysDelinquent = 184 WHERE Acctid = 1213187 AND DaysDelinquent = 154
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1217290 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1218183 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 153 ,NoPayDaysDelinquent = 184 WHERE Acctid = 4324194 AND DaysDelinquent = 154
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1681352 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1214524 AND DaysDelinquent = 124
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 2027339 AND DaysDelinquent = 21
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2640319 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 442779 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2040065 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2480621 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 62 ,NoPayDaysDelinquent = 62 WHERE Acctid = 2640310 AND DaysDelinquent = 31
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2282299 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 434903 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 63 ,NoPayDaysDelinquent = 124 WHERE Acctid = 2285393 AND DaysDelinquent = 62
UPDATE BSegmentCreditCard SET DaysDelinquent = 31 ,NoPayDaysDelinquent = 31 WHERE Acctid = 2285394 AND DaysDelinquent = 51
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4423425 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2323721 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 557797 AND DaysDelinquent = 93
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1746689 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2135813 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2255142 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 9977224 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 0 ,NoPayDaysDelinquent = 0 WHERE Acctid = 2279746 AND DaysDelinquent = 31
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 62 WHERE Acctid = 2091875 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 0 ,NoPayDaysDelinquent = 0 WHERE Acctid = 9840630 AND DaysDelinquent = 31
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2355372 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 7914563 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2736356 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2736422 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4341619 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 2 ,NoPayDaysDelinquent = 33 WHERE Acctid = 4398646 AND DaysDelinquent = 3
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 586096 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4255243 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2784694 AND DaysDelinquent = 93
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2785413 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 276873 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 554409 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3841712 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2723482 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 2728589 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4132453 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 345570 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1702919 AND DaysDelinquent = 93
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1722182 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1662291 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 1833627 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1984605 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 287989 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 3 ,NoPayDaysDelinquent = 3 WHERE Acctid = 1706456 AND DaysDelinquent = 4
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4674206 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1324463 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 124 ,NoPayDaysDelinquent = 216 WHERE Acctid = 309111 AND DaysDelinquent = 125
UPDATE BSegmentCreditCard SET DaysDelinquent = 94 ,NoPayDaysDelinquent = 124 WHERE Acctid = 5609740 AND DaysDelinquent = 93
UPDATE BSegmentCreditCard SET DaysDelinquent = 3 ,NoPayDaysDelinquent = 125 WHERE Acctid = 5628504 AND DaysDelinquent = 4
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4895715 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 342171 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 301708 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 5586242 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 348720 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2690949 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 9859207 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1736230 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2031505 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2136981 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2139234 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 11402646 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2019266 AND DaysDelinquent = 124
UPDATE BSegmentCreditCard SET DaysDelinquent = 61 ,NoPayDaysDelinquent = 182 WHERE Acctid = 2221454 AND DaysDelinquent = 62
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1894772 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1915180 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2953928 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2829052 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2835284 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 2 ,NoPayDaysDelinquent = 2 WHERE Acctid = 2972711 AND DaysDelinquent = 25
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2729377 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2769003 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2952556 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1317781 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1204360 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1197564 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 10336602 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2563175 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1677065 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1226450 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2622027 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2949658 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2976180 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 1590918 AND DaysDelinquent = 183
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2997980 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1662989 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3976648 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1217915 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 63 ,NoPayDaysDelinquent = 63 WHERE Acctid = 1366741 AND DaysDelinquent = 62
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 1873104 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 444621 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2440993 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4500621 AND DaysDelinquent = 93
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 2254415 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 439366 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4506076 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4510688 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2496938 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 350659 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 363410 AND DaysDelinquent = 93
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1708131 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1880801 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1663659 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 154 ,NoPayDaysDelinquent = 337 WHERE Acctid = 2182230 AND DaysDelinquent = 155
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1750613 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2282688 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2305048 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4685202 AND DaysDelinquent = 155
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3807460 AND DaysDelinquent = 93
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4727284 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 4727300 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3974917 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 7495649 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 2 ,NoPayDaysDelinquent = 185 WHERE Acctid = 4120666 AND DaysDelinquent = 62
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4520678 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2726495 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2732745 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2683229 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2464883 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 2796538 AND DaysDelinquent = 155
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2857704 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2651082 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 2796416 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2800737 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 62 WHERE Acctid = 2853556 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2949077 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3531066 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1992356 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3307060 AND DaysDelinquent = 93
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1727822 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1874740 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1939173 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3323208 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 0 ,NoPayDaysDelinquent = 0 WHERE Acctid = 3521554 AND DaysDelinquent = 31
UPDATE BSegmentCreditCard SET DaysDelinquent = 33 ,NoPayDaysDelinquent = 33 WHERE Acctid = 3879600 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1789540 AND DaysDelinquent = 93
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3857665 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3984908 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1972056 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 123 WHERE Acctid = 3513062 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3515309 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3614708 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 31 ,NoPayDaysDelinquent = 31 WHERE Acctid = 3998233 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3130848 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 2729739 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2950895 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2817644 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 31 ,NoPayDaysDelinquent = 31 WHERE Acctid = 2951846 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1755199 AND DaysDelinquent = 93
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2967757 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 11309644 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2716378 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4267580 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 3 ,NoPayDaysDelinquent = 3 WHERE Acctid = 621331 AND DaysDelinquent = 4
UPDATE BSegmentCreditCard SET DaysDelinquent = 0 ,NoPayDaysDelinquent = 0 WHERE Acctid = 2991609 AND DaysDelinquent = 123
UPDATE BSegmentCreditCard SET DaysDelinquent = 2 ,NoPayDaysDelinquent = 2 WHERE Acctid = 2838176 AND DaysDelinquent = 3
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 9841147 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 11027908 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 10552304 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1731512 AND DaysDelinquent = 93
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 10819611 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2754448 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1744764 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 1708315 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 8839348 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 3528024 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3960662 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 11526691 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 9072926 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2923622 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 9151474 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 9422768 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 239141 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 3540571 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 559994 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1998956 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 304094 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 5732900 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 509888 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 526865 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 564572 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 581585 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 62 WHERE Acctid = 5639968 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4492009 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2201965 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1833557 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2009336 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2015687 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2357257 AND DaysDelinquent = 124
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 407840 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2404998 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2487513 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1846451 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 63 WHERE Acctid = 2097821 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1858332 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2369015 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2457993 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 63 WHERE Acctid = 4514811 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2115350 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2076614 AND DaysDelinquent = 2
