BEGIN TRANSACTION

--COMMIT
--ROLLBACK

UPDATE BSegmentCreditCard SET DaysDelinquent = 2 ,NoPayDaysDelinquent = 2 WHERE Acctid = 400774 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 11903655 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1317593 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 0 ,NoPayDaysDelinquent = 30 WHERE Acctid = 621511 AND DaysDelinquent = 0
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1404814 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1841806 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1150520 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1081029 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 2 ,NoPayDaysDelinquent = 2 WHERE Acctid = 2274948 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 2 ,NoPayDaysDelinquent = 2 WHERE Acctid = 2140897 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 12465249 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1865348 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 1856443 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 3645369 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4341697 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 416385 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 2410090 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2646307 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2420947 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 1213723 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4724332 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 10049291 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1875413 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2952222 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 2967365 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 583441 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2579067 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2741165 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1185074 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4626887 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 1081661 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2541587 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 548560 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2961228 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4827721 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3688498 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3922795 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4048187 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2548235 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 9760232 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 6491071 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 2 ,NoPayDaysDelinquent = 32 WHERE Acctid = 2741531 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 6979144 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4058968 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 403125 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 2 ,NoPayDaysDelinquent = 2 WHERE Acctid = 1889397 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1683293 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2235160 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 9596655 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 9597860 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1112163 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 202893 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2454859 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 5625012 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 10890689 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 193571 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1196387 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1147830 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 593469 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 10659109 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 9158579 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2333889 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2377370 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3519786 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 2310055 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 2618050 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2600350 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1868646 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2985926 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1873235 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 503996 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 2 ,NoPayDaysDelinquent = 2 WHERE Acctid = 10336379 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4685675 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2079592 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 12446418 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 4726623 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4708887 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3954784 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 582929 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2112320 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 2542485 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 2 ,NoPayDaysDelinquent = 2 WHERE Acctid = 2611080 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1052003 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1047059 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 0 ,NoPayDaysDelinquent = 0 WHERE Acctid = 2261714 AND DaysDelinquent = 0
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2870036 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1184843 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1183147 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 4367947 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 1225006 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4893392 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 3234548 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2972308 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3560573 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3869888 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1151470 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2110928 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 2 ,NoPayDaysDelinquent = 2 WHERE Acctid = 2698195 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1140952 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2459494 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4463721 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 1895329 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 1223440 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4651018 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 4568676 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2365902 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2320855 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 500526 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1111388 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 281053 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1211392 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 1216993 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 1222794 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1665086 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4623066 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3532115 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3532283 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 583180 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 2506484 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 12400858 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2519881 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 4681002 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1943486 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2449567 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 12268253 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1972872 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 603522 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2562276 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 596315 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 2 ,NoPayDaysDelinquent = 2 WHERE Acctid = 495870 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2047296 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 241793 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2039044 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 336633 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 12474959 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4366247 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 2 ,NoPayDaysDelinquent = 2 WHERE Acctid = 10646983 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2756031 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2660949 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 2939600 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2380868 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1051603 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1411366 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 536208 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2898235 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 11915130 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 2538431 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2238263 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2306758 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1760872 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2025458 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 2 ,NoPayDaysDelinquent = 2 WHERE Acctid = 4679184 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 4439752 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3775590 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 2598727 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 1390436 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 278122 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 9454554 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 3742961 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4133555 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 4669238 AND DaysDelinquent = 1