BEGIN TRANSACTION

--COMMIT
--ROLLBACK

UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4811150 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4268846 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 9146843 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 562178 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2593922 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2618741 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2626028 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 61 ,NoPayDaysDelinquent = 61 WHERE Acctid = 2749315 AND DaysDelinquent = 62
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2636772 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 62 WHERE Acctid = 2670264 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2682635 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 0 ,NoPayDaysDelinquent = 0 WHERE Acctid = 2724681 AND DaysDelinquent = 92
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 2821833 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 2871803 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2607686 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2696129 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 153 ,NoPayDaysDelinquent = 153 WHERE Acctid = 2697750 AND DaysDelinquent = 154
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2743758 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2794466 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2625051 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2625767 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 153 ,NoPayDaysDelinquent = 184 WHERE Acctid = 2044681 AND DaysDelinquent = 155
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3635682 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3521787 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 122 ,NoPayDaysDelinquent = 183 WHERE Acctid = 3644968 AND DaysDelinquent = 123
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3646343 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4062905 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 4342108 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 62 WHERE Acctid = 4347590 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 122 ,NoPayDaysDelinquent = 122 WHERE Acctid = 4348385 AND DaysDelinquent = 124
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2030036 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 3 ,NoPayDaysDelinquent = 64 WHERE Acctid = 4000172 AND DaysDelinquent = 4
UPDATE BSegmentCreditCard SET DaysDelinquent = 0 ,NoPayDaysDelinquent = 30 WHERE Acctid = 3629386 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 3874208 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3987067 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4133638 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4133724 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 0 ,NoPayDaysDelinquent = 0 WHERE Acctid = 4250994 AND DaysDelinquent = 31
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4256290 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4068275 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4260103 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4353727 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4389155 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 62 WHERE Acctid = 2181212 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2782724 AND DaysDelinquent = 93
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2808927 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2965245 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2735338 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 9424254 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 185 ,NoPayDaysDelinquent = 185 WHERE Acctid = 1703587 AND DaysDelinquent = 186
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1735164 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2795454 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 2262052 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 1756568 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2841431 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2015658 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 93 WHERE Acctid = 2991779 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 62 WHERE Acctid = 2994922 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3417030 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1139243 AND DaysDelinquent = 93
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1200080 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 92 ,NoPayDaysDelinquent = 92 WHERE Acctid = 1222756 AND DaysDelinquent = 62
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 9859610 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 9746499 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1225698 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 9824128 AND DaysDelinquent = 24
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 8018632 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 8975000 AND DaysDelinquent = 93
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1943338 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1839275 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 307521 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 444670 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 11342220 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 62 WHERE Acctid = 545716 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3416342 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1842181 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 123 ,NoPayDaysDelinquent = 184 WHERE Acctid = 1958198 AND DaysDelinquent = 124
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2003788 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1916881 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 620378 AND DaysDelinquent = 93
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 563595 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2781214 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 502477 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 3 ,NoPayDaysDelinquent = 3 WHERE Acctid = 502558 AND DaysDelinquent = 34
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 504932 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 0 ,NoPayDaysDelinquent = 0 WHERE Acctid = 541803 AND DaysDelinquent = 31
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2534708 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 547559 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 547588 AND DaysDelinquent = 62
UPDATE BSegmentCreditCard SET DaysDelinquent = 61 ,NoPayDaysDelinquent = 123 WHERE Acctid = 550078 AND DaysDelinquent = 62
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2179165 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 6653864 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 286017 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2617699 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 31 ,NoPayDaysDelinquent = 31 WHERE Acctid = 2620825 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2551945 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2063905 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2628889 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2629600 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4687622 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 2 ,NoPayDaysDelinquent = 32 WHERE Acctid = 2480427 AND DaysDelinquent = 3
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 2116296 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4653237 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 153 ,NoPayDaysDelinquent = 184 WHERE Acctid = 2134928 AND DaysDelinquent = 154
UPDATE BSegmentCreditCard SET DaysDelinquent = 2 ,NoPayDaysDelinquent = 63 WHERE Acctid = 2615732 AND DaysDelinquent = 3
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4679590 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 2684618 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2694980 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2682748 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4955840 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 4736592 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 4864976 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 4238987 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4905064 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4356396 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4779509 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2446705 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2272561 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4829986 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2020486 AND DaysDelinquent = 93
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2247213 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1149573 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2545805 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2616515 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2620416 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2707788 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2819648 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2176968 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2921680 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 9426523 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2091872 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2156164 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 414142 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 419722 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2942380 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2943430 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2816649 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2919031 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 340012 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2726389 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2226520 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2390184 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2127732 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2307344 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2364650 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2407618 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4244527 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 0 ,NoPayDaysDelinquent = 0 WHERE Acctid = 4233892 AND DaysDelinquent = 31
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4240827 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4002109 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4307243 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4356377 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4130418 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 62 WHERE Acctid = 3412234 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3529587 AND DaysDelinquent = 93
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3645823 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2061539 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3883089 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3643548 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1787012 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2934266 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 2998493 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 3424789 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3638980 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2967292 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2979224 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 9862747 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 10806013 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 10656788 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 11090713 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1857318 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 11113391 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 10987525 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 11023926 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1836732 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 500288 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4002385 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2548565 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4345539 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1993528 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 300366 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1703398 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 152 ,NoPayDaysDelinquent = 182 WHERE Acctid = 1735387 AND DaysDelinquent = 154
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1839104 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 398604 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 5614666 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2215375 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2013780 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 1366801 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 8940139 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1873492 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1943842 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 8488058 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 9397359 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1947812 AND DaysDelinquent = 32
