BEGIN TRANSACTION

--COMMIT
--ROLLBACK
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 400213 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 2954830 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2997628 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 62 WHERE Acctid = 548683 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4369421 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4697354 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 432231 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 3503088 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1336282 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 7702412 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 1980472 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 5633009 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2049627 AND DaysDelinquent = 155
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 374413 AND DaysDelinquent = 124
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 307118 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1786056 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 290699 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 5626181 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 5543993 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1764134 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 9869791 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1995536 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2129089 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 0 ,NoPayDaysDelinquent = 212 WHERE Acctid = 2042037 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 11211575 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 407208 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4649202 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1929327 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 417568 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 47068 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3888870 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4503722 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3540736 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1188103 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 183 ,NoPayDaysDelinquent = 183 WHERE Acctid = 333452 AND DaysDelinquent = 152
UPDATE BSegmentCreditCard SET DaysDelinquent = 0 ,NoPayDaysDelinquent = 0 WHERE Acctid = 1189632 AND DaysDelinquent = 62
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 300864 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1054341 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1156580 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4000024 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1050215 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2142996 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 295751 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2830882 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2332480 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 9857439 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 9857572 AND DaysDelinquent = 93
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2411180 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 64038 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 124 WHERE Acctid = 2632046 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 119373 AND DaysDelinquent = 93
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 530813 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 64 ,NoPayDaysDelinquent = 64 WHERE Acctid = 1215721 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 93 WHERE Acctid = 4910478 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 153 ,NoPayDaysDelinquent = 182 WHERE Acctid = 3532235 AND DaysDelinquent = 154
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 548080 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 8486173 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1194491 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 3751358 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4934175 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 428362 AND DaysDelinquent = 155
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4524187 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2971699 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3751828 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 5620467 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1790320 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2189099 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 443258 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 5585954 AND DaysDelinquent = 124
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 422699 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1768197 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 153 ,NoPayDaysDelinquent = 184 WHERE Acctid = 1770146 AND DaysDelinquent = 154
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 351731 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 0 ,NoPayDaysDelinquent = 0 WHERE Acctid = 5625985 AND DaysDelinquent = 31
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 93 WHERE Acctid = 407185 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2065101 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1779483 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 430406 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 563072 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1848208 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 2243719 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 0 ,NoPayDaysDelinquent = 0 WHERE Acctid = 8493803 AND DaysDelinquent = 31
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4653715 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 0 ,NoPayDaysDelinquent = 0 WHERE Acctid = 1138242 AND DaysDelinquent = 62
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 10814983 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 93 ,NoPayDaysDelinquent = 124 WHERE Acctid = 1143490 AND DaysDelinquent = 92
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 1181777 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4501456 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1198127 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 152 ,NoPayDaysDelinquent = 183 WHERE Acctid = 283753 AND DaysDelinquent = 154
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 5552036 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 5054217 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 5609255 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4660251 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 3 ,NoPayDaysDelinquent = 3 WHERE Acctid = 1327134 AND DaysDelinquent = 4
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1707877 AND DaysDelinquent = 2
