BEGIN TRANSACTION

--COMMIT
--ROLLBACK
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 2589223 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3494973 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2136165 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 63 ,NoPayDaysDelinquent = 93 WHERE Acctid = 2547237 AND DaysDelinquent = 62
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4340918 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2333736 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3853533 AND DaysDelinquent = 93
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 558071 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 219723 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 9495436 AND DaysDelinquent = 93
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 579320 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 174277 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4503115 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1139779 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 10269615 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 209576 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3977795 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 279886 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1050125 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1146425 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1193318 AND DaysDelinquent = 0
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2157621 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 9748056 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1081689 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2490825 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2137504 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1046567 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1082363 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2091482 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4171705 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4256957 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4365124 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2510322 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 5610768 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 4725401 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4335259 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2996173 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4837825 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2514266 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 122 ,NoPayDaysDelinquent = 182 WHERE Acctid = 2514409 AND DaysDelinquent = 123
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 3637781 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2458104 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 275432 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 62 WHERE Acctid = 9853416 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 10384876 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 11439597 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 11404118 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1206005 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4610615 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 153 ,NoPayDaysDelinquent = 182 WHERE Acctid = 1195959 AND DaysDelinquent = 154
UPDATE BSegmentCreditCard SET DaysDelinquent = 61 ,NoPayDaysDelinquent = 92 WHERE Acctid = 1147246 AND DaysDelinquent = 62
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4477747 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4500986 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1183998 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 0 ,NoPayDaysDelinquent = 0 WHERE Acctid = 1207151 AND DaysDelinquent = 31
UPDATE BSegmentCreditCard SET DaysDelinquent = 92 ,NoPayDaysDelinquent = 92 WHERE Acctid = 1209541 AND DaysDelinquent = 93
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1210243 AND DaysDelinquent = 93
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1050805 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4387924 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4516436 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4915030 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1393422 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 335372 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1673154 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1673181 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1192455 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4376622 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 62 ,NoPayDaysDelinquent = 215 WHERE Acctid = 4609045 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4719282 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 62 WHERE Acctid = 1676474 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 2544251 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 153 ,NoPayDaysDelinquent = 182 WHERE Acctid = 2383410 AND DaysDelinquent = 154
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 9422414 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2459752 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 283896 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 591397 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 327841 AND DaysDelinquent = 93
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 9437275 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2010614 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2031252 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 308260 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2573900 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2022492 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 33 ,NoPayDaysDelinquent = 33 WHERE Acctid = 1991220 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 10233543 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1207738 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1211923 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 241665 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2568348 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2701048 AND DaysDelinquent = 93
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1223244 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 195630 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1949025 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1198321 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 1139775 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 0 ,NoPayDaysDelinquent = 0 WHERE Acctid = 1211843 AND DaysDelinquent = 31
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1212197 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2148791 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 412926 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2040884 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4393614 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 279483 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2482571 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2066297 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1740303 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2077456 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 11178450 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 0 ,NoPayDaysDelinquent = 0 WHERE Acctid = 12391756 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 9457670 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 6390105 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 9436289 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4264647 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 544973 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 509913 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4254595 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 538443 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 153 ,NoPayDaysDelinquent = 184 WHERE Acctid = 919532 AND DaysDelinquent = 154
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1210979 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2031752 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2157730 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 11215653 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 11218102 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 11518537 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1080672 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 93 WHERE Acctid = 2436506 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 566639 AND DaysDelinquent = 14
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2130030 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2164206 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1666528 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1729338 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 152 ,NoPayDaysDelinquent = 152 WHERE Acctid = 2181810 AND DaysDelinquent = 121
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 9841915 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2495692 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1714958 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4798923 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 121 ,NoPayDaysDelinquent = 183 WHERE Acctid = 767093 AND DaysDelinquent = 123
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2581950 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 62 WHERE Acctid = 3825684 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3977547 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 0 ,NoPayDaysDelinquent = 0 WHERE Acctid = 2514706 AND DaysDelinquent = 1
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2686977 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2586672 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3632016 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3638066 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4118921 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 153 ,NoPayDaysDelinquent = 184 WHERE Acctid = 4256848 AND DaysDelinquent = 154
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2764162 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2777573 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1155220 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 283172 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 313214 AND DaysDelinquent = 124
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 8486496 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 276165 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 285223 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 41967 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 32 WHERE Acctid = 4271114 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 566046 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 278367 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 348257 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4349296 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 11501637 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2972615 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4672366 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2786237 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4281051 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2803651 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4524051 AND DaysDelinquent = 63
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2966288 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3819521 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 3975188 AND DaysDelinquent = 93
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1223552 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1216831 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 153 ,NoPayDaysDelinquent = 184 WHERE Acctid = 1220108 AND DaysDelinquent = 154
UPDATE BSegmentCreditCard SET DaysDelinquent = 33 ,NoPayDaysDelinquent = 186 WHERE Acctid = 4734907 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 31 WHERE Acctid = 1146220 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1201420 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1203476 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 8179901 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4529020 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1201448 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 62 WHERE Acctid = 1700207 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1208934 AND DaysDelinquent = 2
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4127184 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4355394 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1706401 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1735982 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 63 ,NoPayDaysDelinquent = 63 WHERE Acctid = 1769939 AND DaysDelinquent = 64
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4580610 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4585054 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1850895 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1851161 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 1877303 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 4093091 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2562308 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 2563185 AND DaysDelinquent = 32
UPDATE BSegmentCreditCard SET DaysDelinquent = 1 ,NoPayDaysDelinquent = 1 WHERE Acctid = 10335386 AND DaysDelinquent = 32
