-- TO BE RUN ON PRIMARY SERVER ONLY

BEGIN TRANSACTION
--COMMIT TRANSACTION
-- ROLLBACK TRANSACTION


USE CCGS_CoreIssue
GO



UPDATE TOP(1) BSegment_Primary SET AmtOfPayCurrDue = AmtOfPayCurrDue + 53.93 WHERE acctId = 4919331