INSERT INTO AccountsOfPlanToReLink (acctID, TranID, TimeGap)
SELECT acctID, TranID, ROW_NUMBER() OVER(PARTITION BY acctId ORDER BY TranTime)*10 
FROM ErrorAP WITH (NOLOCK) 
WHERE ATID=51
AND TranID IN
(102625726603)