-- TO BE RUN ON PRIMARY NAD REPLICATION SERVER ONLY


USE CCGS_CoreIssue
GO


BEGIN TRANSACTION
--COMMIT TRANSACTION
-- ROLLBACK TRANSACTION



UPDATE TOP(1) PlanInfoForReport SET CycleDueDTD = 0, AmtOfPayXDLate = 0, 
AmountOfTotalDue = 0 WHERE CPSacctId = 1248910 AND BusinessDay = '2021-08-31 23:59:57.000'

