
BEGIN TRAN
--COMMIT TRAN
--ROLLBACK TRAN


INSERT INTO [dbo].[MergeSummaryHeader]
           ([SKey]
           ,[acctId]
           ,[parent02AID]
           ,[parent01AID]
           ,[APR]
           ,[StatementDate]
           ,[DateOfTotalDue]
           ,[CurrentBalance]
           ,[DaysInCycle]
           ,[Principal]
           ,[EqualPaymentAmt]
           ,[cpsinterestplan]
           ,[PlanUUID]
           ,[CardAcceptorNameLocation]
           ,[ClientId]
           ,[StmtHeader_UUID]
           ,[AmountOfTotalDue]
           ,[CurrentDue]
           ,[currentbalanceco]
           ,[AmountOfPaymentsCTD]
           ,[AmountOfReturnsCTD]
           ,[StatementID]
           ,[LoanEndDate]
           ,[DispRCHFavororWriteoff]
           ,[SRBwithInstallmentDueCC1]
           ,[DisputeIndicator]
           ,[DisputesAmtNS]
           ,[AmountOfCreditsLTD]
           ,[AmountOfPaymentsLTD]
           ,[OriginalPurchaseAmount]
           ,[PayOffDate]
           ,[DailyCashAmount]
           ,[DailyCashPercent]
           ,[SingleSaleTranID]
           ,[plansegcreatedate]
           ,[CreditPlanNumber]
           ,[InterestStartDate]
           ,[DeferredAccruedCTD]
           ,[BSFCMethod]
           ,[AmountOfReturnsLTD]
           ,[AmountOfCreditsRevLTD]
           ,[CounterForEqualPayment])
     
SELECT 
			[SKey]
           ,[acctId]
           ,[parent02AID]
           ,[parent01AID]
           ,[APR]
           ,[StatementDate]
           ,[DateOfTotalDue]
           ,[CurrentBalance]
           ,[DaysInCycle]
           ,[Principal]
           ,[EqualPaymentAmt]
           ,[cpsinterestplan]
           ,[PlanUUID]
           ,[CardAcceptorNameLocation]
           ,[ClientId]
           ,[StmtHeader_UUID]
           ,[AmountOfTotalDue]
           ,[CurrentDue]
           ,[currentbalanceco]
           ,[AmountOfPaymentsCTD]
           ,[AmountOfReturnsCTD]
           ,[StatementID]
           ,[LoanEndDate]
           ,[DispRCHFavororWriteoff]
           ,[SRBwithInstallmentDueCC1]
           ,[DisputeIndicator]
           ,[DisputesAmtNS]
           ,[AmountOfCreditsLTD]
           ,[AmountOfPaymentsLTD]
           ,[OriginalPurchaseAmount]
           ,[PayOffDate]
           ,[DailyCashAmount]
           ,[DailyCashPercent]
           ,[SingleSaleTranID]
           ,[plansegcreatedate]
           ,[CreditPlanNumber]
           ,[InterestStartDate]
           ,[DeferredAccruedCTD]
           ,[BSFCMethod]
           ,[AmountOfReturnsLTD]
           ,[AmountOfCreditsRevLTD]
           ,[CounterForEqualPayment]
FROM TempMergeSummaryHeader



     


