-- TO BE RUN ON REPLICATION SERVER ONLY

USE CCGS_RPT_CoreIssue
GO

BEGIN TRANSACTION

--COMMIT TRANSACTION
--ROLLBACK TRANSACTION
-- UPDATE TOP(1) WILL BE 1 ROW EACH

UPDATE TOP(1) AccountInfoForReport SET ManualInitialChargeOffReason = '6' WHERE BSacctId = 809746 AND BusinessDay = '2021-02-01 23:59:57'