-- TO BE RUN ON PRIMARY SERVER ONLY

USE CCGS_CoreIssue
GO

BEGIN TRANSACTION
--COMMIT TRANSACTION
--ROLLBACK TRANSACTION

-- UPDATE WILL BE 1 ROW EACH STATEMENT


UPDATE TOP(1) AccountInfoForReport SET AmtOfPayXDLate = AmtOfPayXDLate - 16.62 WHERE BSacctId = 1486005 AND BusinessDay = '2021-04-04 23:59:57.000'
