-- TO BE RUN ON PRIMARY SERVER ONLY

USE CCGS_CoreIssue
GO


BEGIN TRANSACTION
	UPDATE CommonTNP SET TranTime = DATEADD(SECOND, 10, GETDATE()) WHERE acctId = 340905 AND TranID = 0 AND ATID = 51
	-- 1 row
COMMIT TRANSACTION
--ROLLBACK TRANSACTION