DROP PROCEDURE IF EXISTS USP_GetUniqueID
GO
CREATE PROCEDURE USP_GetUniqueID (@Name VARCHAR(100))
AS
BEGIN

	DECLARE @ID DECIMAL(19, 0), @ErrorInID INT
	
	BEGIN TRY 
		BEGIN TRANSACTION 
			SELECT @ID = seq + 2 FROM PostValues WITH(updlock)  WHERE  NAME = @Name 

			UPDATE PostValues SET seq = seq + 2  WHERE  NAME = @Name
		COMMIT TRANSACTION 
	END TRY
	BEGIN catch 
		ROLLBACK TRANSACTION 
		SET @ErrorInID = 1 
	END catch

	IF(@ErrorInID = 1)
	BEGIN
		SELECT 0 AS ID
	END
	ELSE
	BEGIN
		SELECT @ID AS ID
	END

END