-- TO BE RUN ON PRIMARY SERVER ONLY

USE CCGS_CoreAuth
GO

BEGIN TRANSACTION

	-- UPDATE WILL BE 1 ROW EACH STATEMENT


	UPDATE BSegment_Primary SET SystemStatus = 2, DateOfLastDelinquent = NULL WHERE acctId = 2333040

COMMIT TRANSACTION
--ROLLBACK TRANSACTION