BEGIN TRY 
	BEGIN TRANSACTION 
		BEGIN

			UPDATE RetailAPILineItems SET APIErrorFound = CASE WHEN APR = -1 THEN 1 ELSE 0 END WHERE APIErrorFound IS NULL
			---351 Records
			-- APR (-1) = Error   used to log error in old version
		END
	COMMIT TRANSACTION 
END TRY

BEGIN CATCH
	IF @@TRANCOUNT > 0
		ROLLBACK TRANSACTION 
		SELECT ERROR_MESSAGE(),ERROR_LINE(),ERROR_NUMBER()
		RAISERROR('ERROR OCCURED :-', 16, 1);
END CATCH
GO

