-- TO BE RUN ON PRIMARY SERVER ONLY

USE CCGS_CoreIssue
GO


BEGIN TRANSACTION
--COMMIT TRANSACTION
-- ROLLBACK TRANSACTION

UPDATE TOP(1) BSegment_Primary SET CycleDueDTD = 0, SystemStatus = 2, AmtOfPayCurrDue = 0 WHERE acctId = 883659

UPDATE TOP(1) BSegmentCreditCard SET AmtOfPayXDLate = 0, AmountOfPayment30DLate = 0, DtOfLastDelinqCTD = NULL, DateOfOriginalPaymentDueDTD = NULL,
SRBWithInstallmentDue = 0, SBWithInstallmentDue = 0 ,FirstDueDate = NULL, DaysDelinquent = 0, NoPayDaysDelinquent = 0 WHERE acctId = 883659

UPDATE TOP(1) CPSgmentCreditCard SET AmountOfTotalDue = 0, CycleDueDTD = 0, AmtOfPayCurrDue = 0, AmtOfPayXDLate = 0, AmountOfPayment30DLate = 0, SRBWithInstallmentDue = 0, SBWithInstallmentDue = 0 WHERE acctId = 66742392


UPDATE TOP(1) BSegment_Primary SET CycleDueDTD = 0, SystemStatus = 2, AmtOfPayCurrDue = 0 WHERE acctId = 1240951

UPDATE TOP(1) BSegmentCreditCard SET AmtOfPayXDLate = 0, AmountOfPayment30DLate = 0, DtOfLastDelinqCTD = NULL, DateOfOriginalPaymentDueDTD = NULL,
SRBWithInstallmentDue = 0, SBWithInstallmentDue = 0 ,FirstDueDate = NULL, DaysDelinquent = 0, NoPayDaysDelinquent = 0 WHERE acctId = 1240951

UPDATE TOP(1) CPSgmentCreditCard SET AmountOfTotalDue = 0, CycleDueDTD = 0, AmtOfPayCurrDue = 0, AmtOfPayXDLate = 0, AmountOfPayment30DLate = 0, SRBWithInstallmentDue = 0, SBWithInstallmentDue = 0 WHERE acctId = 66478297
UPDATE TOP(1) CPSgmentCreditCard SET AmountOfTotalDue = 0, CycleDueDTD = 0, AmtOfPayCurrDue = 0, AmtOfPayXDLate = 0, AmountOfPayment30DLate = 0, SRBWithInstallmentDue = 0, SBWithInstallmentDue = 0 WHERE acctId = 66478298


UPDATE TOP(1) BSegment_Primary SET CycleDueDTD = 0, SystemStatus = 2, AmtOfPayCurrDue = 0 WHERE acctId = 1344799

UPDATE TOP(1) BSegmentCreditCard SET AmtOfPayXDLate = 0, AmountOfPayment30DLate = 0, DtOfLastDelinqCTD = NULL, DateOfOriginalPaymentDueDTD = NULL,
SRBWithInstallmentDue = 0, SBWithInstallmentDue = 0 ,FirstDueDate = NULL, DaysDelinquent = 0, NoPayDaysDelinquent = 0 WHERE acctId = 1344799

UPDATE TOP(1) CPSgmentCreditCard SET AmountOfTotalDue = 0, CycleDueDTD = 0, AmtOfPayCurrDue = 0, AmtOfPayXDLate = 0, AmountOfPayment30DLate = 0, SRBWithInstallmentDue = 0, SBWithInstallmentDue = 0 WHERE acctId = 1357219


UPDATE TOP(1) BSegment_Primary SET CycleDueDTD = 0, SystemStatus = 2, AmtOfPayCurrDue = 0 WHERE acctId = 1378174

UPDATE TOP(1) BSegmentCreditCard SET AmtOfPayXDLate = 0, AmountOfPayment30DLate = 0, DtOfLastDelinqCTD = NULL, DateOfOriginalPaymentDueDTD = NULL,
SRBWithInstallmentDue = 0, SBWithInstallmentDue = 0 ,FirstDueDate = NULL, DaysDelinquent = 0, NoPayDaysDelinquent = 0 WHERE acctId = 1378174

UPDATE TOP(1) CPSgmentCreditCard SET AmountOfTotalDue = 0, CycleDueDTD = 0, AmtOfPayCurrDue = 0, AmtOfPayXDLate = 0, AmountOfPayment30DLate = 0, SRBWithInstallmentDue = 0, SBWithInstallmentDue = 0 WHERE acctId = 67069091


UPDATE TOP(1) AccountInfoForReport SET CycleDueDTD = 0, SystemStatus = 2, AmtOfPayCurrDue = 0, AmtOfPayXDLate = 0, RunningMinimumDue = 0, RemainingMinimumDue = 0, DateOfDelinquency = NULL, DateOfOriginalPaymentDueDTD = NULL, 
 DaysDelinquent = 0, TotalDaysDelinquent = 0 WHERE BSacctId = 883659 AND BusinessDay = '2021-10-31 23:59:57.000'

UPDATE TOP(1) PlanInfoForReport SET AmountOfTotalDue = 0, CycleDueDTD = 0, AmtOfPayCurrDue = 0, AmtOfPayXDLate = 0, AmountOfPayment30DLate = 0, SRBWithInstallmentDue = 0 WHERE CPSacctId = 66742392 AND BusinessDay = '2021-10-31 23:59:57.000'


UPDATE TOP(1) AccountInfoForReport SET CycleDueDTD = 0, SystemStatus = 2, AmtOfPayCurrDue = 0, AmtOfPayXDLate = 0, RunningMinimumDue = 0, RemainingMinimumDue = 0, DateOfDelinquency = NULL, DateOfOriginalPaymentDueDTD = NULL, 
 DaysDelinquent = 0, TotalDaysDelinquent = 0 WHERE BSacctId = 1240951 AND BusinessDay = '2021-10-31 23:59:57.000'

UPDATE TOP(1) PlanInfoForReport SET AmountOfTotalDue = 0, CycleDueDTD = 0, AmtOfPayCurrDue = 0, AmtOfPayXDLate = 0, AmountOfPayment30DLate = 0, SRBWithInstallmentDue = 0 WHERE CPSacctId = 66478297 AND BusinessDay = '2021-10-31 23:59:57.000'
UPDATE TOP(1) PlanInfoForReport SET AmountOfTotalDue = 0, CycleDueDTD = 0, AmtOfPayCurrDue = 0, AmtOfPayXDLate = 0, AmountOfPayment30DLate = 0, SRBWithInstallmentDue = 0 WHERE CPSacctId = 66478298 AND BusinessDay = '2021-10-31 23:59:57.000'


UPDATE TOP(1) AccountInfoForReport SET CycleDueDTD = 0, SystemStatus = 2, AmtOfPayCurrDue = 0, AmtOfPayXDLate = 0, RunningMinimumDue = 0, RemainingMinimumDue = 0, DateOfDelinquency = NULL, DateOfOriginalPaymentDueDTD = NULL, 
 DaysDelinquent = 0, TotalDaysDelinquent = 0 WHERE BSacctId = 1344799 AND BusinessDay = '2021-10-31 23:59:57.000'

UPDATE TOP(1) PlanInfoForReport SET AmountOfTotalDue = 0, CycleDueDTD = 0, AmtOfPayCurrDue = 0, AmtOfPayXDLate = 0, AmountOfPayment30DLate = 0, SRBWithInstallmentDue = 0 WHERE CPSacctId = 1357219 AND BusinessDay = '2021-10-31 23:59:57.000'


UPDATE TOP(1) AccountInfoForReport SET CycleDueDTD = 0, SystemStatus = 2, AmtOfPayCurrDue = 0, AmtOfPayXDLate = 0, RunningMinimumDue = 0, RemainingMinimumDue = 0, DateOfDelinquency = NULL, DateOfOriginalPaymentDueDTD = NULL, 
 DaysDelinquent = 0, TotalDaysDelinquent = 0 WHERE BSacctId = 1378174 AND BusinessDay = '2021-10-31 23:59:57.000'

UPDATE TOP(1) PlanInfoForReport SET AmountOfTotalDue = 0, CycleDueDTD = 0, AmtOfPayCurrDue = 0, AmtOfPayXDLate = 0, AmountOfPayment30DLate = 0, SRBWithInstallmentDue = 0 WHERE CPSacctId = 67069091 AND BusinessDay = '2021-10-31 23:59:57.000'



update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 13371
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 4275371
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 256318
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 20590875
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 34554099
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 34554100
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 348968
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 14385702
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 424949
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 2800025
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 591772
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 14249843
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 600501
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 4970734
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 33691424
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 671644
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 5220745
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 21924960
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 21934920
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 66215965
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 66810225
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 69368003
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 676720
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 22498564
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 853759
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 4097356
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 876524
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 10624640
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 885688
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 6283830
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 958151
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 6518020
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 1026121
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 16227625
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 1081685
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 41812990
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 45771389
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 1169992
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 67956207
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 1267778
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 44752305
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 45639852
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 45639853
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 1368698
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 8350272
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 52876922
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 52876923
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 1521063
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 41925982
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 41925983
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 67986893
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 1565888
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 6082060
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 1680182
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 69422623
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 1737940
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 13449029
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 53804903
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 53804904
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 1860302
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 68046873
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 1860785
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 16149698
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 23421774
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 23421775
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 1899419
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 16747123
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 1987914
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 54724678
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 2027962
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 16193523
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 2108734
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 21293965
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 2176395
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 61613036
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 2324033
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 44362104
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 46544824
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 2416776
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 5313455
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 2630467
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 67482381
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 2782841
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 9414524
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 3484803
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 48657111
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 6003809
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 23628362
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 7977564
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 19854507
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 8163537
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 42856837
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 43816481
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 8320339
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 40682869
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 66130235
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 10201143
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 47017217
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 66189031
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 10237255
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 58529326
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 68010598
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 10437393
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 46197516
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 10439088
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 40127439
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 60816471
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 10619390
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 16743110
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 22585788
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 44398146
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 25055228
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 32126811
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 31482883
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 34454826
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 31519229
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 58869951
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 33093229
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 36716598
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 36143442
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 69372832
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 36823394
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 53507300
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 39147947
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 66211583
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 45394384
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 51581150
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 50485171
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 66188739
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 51632458
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 54686019
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 53038626
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 53510162
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 54760825
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 66010225
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 54895556
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 65685449
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 55028908
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 65770422
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 56076733
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 62440812
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 56154899
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 68056720
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 57756838
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 59001092
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 61111576
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 68018732
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 63051200
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 66074302
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 63072458
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 64411749
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 67987107
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 65104680
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 66947094
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 65115561
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 67960856
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 66737167
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 67986235
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 67261798
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 68582748



update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 256318
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 20590875
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 34554099
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 34554100
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 600501
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 4970734
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 33691424
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 671644
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 5220745
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 21924960
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 21934920
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 66215965
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 66810225
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 69368003
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 1267778
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 44752305
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 45639852
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 45639853
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 1368698
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 8350272
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 52876922
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 52876923
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 1521063
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 41925982
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 41925983
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 67986893
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 1737940
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 13449029
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 53804903
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 53804904
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 1860785
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 16149698
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 23421774
update    top(1)  PlanInfoForReport    set    amountoftotaldue  = 0  ,srbwithinstallmentdue  = 0 , sbwithinstallmentdue = 0 , amtofpaycurrdue= 0   ,  amtofpayxdlate =0   , AmountOfPayment30DLate =  0  ,  AmountOfPayment60DLate = 0  ,   AmountOfPayment90DLate = 0   ,  AmountOfPayment120DLate  = 0 ,   AmountOfPayment150DLate = 0  ,  AmountOfPayment180DLate  = 0  , AmountOfPayment210DLate = 0 ,cycleduedtd = 0   where   cpsacctid  = 23421775
