-- TO BE RUN ON PRIMARY SERVER ONLY

USE CCGS_CoreIssue
GO

BEGIN TRANSACTION
--COMMIT TRANSACTION
--ROLLBACK TRANSACTION

-- UPDATE WILL BE 1 ROW EACH STATEMENT



DELETE TOP(1) FROM CurrentBalanceAudit WHERE AID = 386463 AND ATID = 51 AND IdentityField = 1308495841
/*

UPDATE TOP(1) Bsegment_primary SET TPYLAD = NULL, TPYNAD = NULL, TPYBLOB = NULL WHERE acctId = 386463

UPDATE TOP(1) Bsegment_primary SET ccinhparent125aid = 16 WHERE acctId = 386463

DELETE TOP(1) FROM ErrorTNP WHERE acctId = 386463

*/