BEGIN
	BEGIN TRY
		BEGIN TRANSACTION

			UPDATE BP
			SET AmtOfAcctHighBalLTD = HB_Calc
			FROM BSegment_Primary BP 
			JOIN ##CBRAccounts C ON (BP.acctID = C.acctID)
			WHERE C.JobStatus = 1

			UPDATE ##CBRAccounts SET JobStatus = 2 WHERE JobStatus = 1

		COMMIT TRANSACTION
	END TRY

	BEGIN CATCH
		IF @@TRANCOUNT > 0
		ROLLBACK TRANSACTION
		SELECT ERROR_MESSAGE(), ERROR_LINE(), ERROR_NUMBER()
		RAISERROR('ERROR OCCURED :-', 16, 1);
	END CATCH

END



