INSERT INTO AccountsOfPlanToReLink (acctID, TranID, TimeGap)
SELECT acctID, TranID, ROW_NUMBER() OVER(PARTITION BY acctId ORDER BY TranTime)*10 
FROM ErrorAP WITH (NOLOCK) 
WHERE ATID=51
AND TranID IN
(134508721911)


--SELECT *
--FROM CommonAP WITH (NOLOCK) 
--WHERE ATID=51
--AND TranID IN
--(121217425748)

--SELECT *
--FROM CCard_Primary WITH (NOLOCK) 
--WHERE TranID IN
--(121217425748)

--SELECT *
--FROM CommonAP WITH (NOLOCK)
--WHERE TranTime < GETDATE() 