-- TO BE EXECUTED ON PRIMARY SERVER COREISSUE DATABASE ONLY

BEGIN TRANSACTION
--COMMIT TRANSACTION
--ROLLBACK TRANSACTION

UPDATE ILPS 
SET ILPS.ClientID = BS.ClientID
FROM ILPScheduleDetailSummary ILPS WITH(NOLOCK) 
JOIN BSegment_Secondary BS WITH (NOLOCK) ON (ILPS.parent02AID = BS.acctID)
WHERE ILPS.ClientID IS NULL 
AND PlanID > 0
--122 rows