-- TO BE RUN ON PRIMARY SERVER ONLY

USE CCGS_CoreIssue
GO

BEGIN TRANSACTION
--COMMIT TRANSACTION
--ROLLBACK TRANSACTION

-- UPDATE WILL BE 1 ROW EACH STATEMENT


UPDATE TOP(1) BSegmentCreditCard SET NoPayDaysDelinquent = 3 WHERE acctId = 2836591
UPDATE TOP(1) BSegmentCreditCard SET NoPayDaysDelinquent = 3 WHERE acctId = 2387350