IF NOT EXISTS (SELECT 1 FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'DBO.TransactionCreationTempData') AND NAME = 'RevTgt')
BEGIN
	ALTER TABLE DBO.TransactionCreationTempData ADD RevTgt DECIMAL(19,0) NULL
END

IF NOT EXISTS (SELECT 1 FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'DBO.TransactionCreationTempData') AND NAME = 'JiraID')
BEGIN
	ALTER TABLE DBO.TransactionCreationTempData ADD JiraID VARCHAR(20) NULL
END

IF NOT EXISTS (SELECT 1 FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'DBO.TransactionCreationTempData') AND NAME = 'ClientID')
BEGIN
	ALTER TABLE DBO.TransactionCreationTempData ADD ClientID VARCHAR(64) NULL
END

IF NOT EXISTS (SELECT 1 FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'DBO.TransactionCreationTempData') AND NAME = 'RMATranUUID')
BEGIN
	ALTER TABLE DBO.TransactionCreationTempData ADD RMATranUUID VARCHAR(64) NULL
END

IF NOT EXISTS (SELECT 1 FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'DBO.TransactionCreationTempData') AND NAME = 'CreditPlanMaster')
BEGIN
	ALTER TABLE DBO.TransactionCreationTempData ADD CreditPlanMaster INT NULL
END

IF NOT EXISTS (SELECT 1 FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'DBO.TransactionCreationTempData') AND NAME = 'InvoiceNumber')
BEGIN
	ALTER TABLE DBO.TransactionCreationTempData ADD InvoiceNumber VARCHAR(20) NULL
END

IF NOT EXISTS (SELECT 1 FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'DBO.CreateNewSingleTransactionData') AND NAME = 'InvoiceNumber')
BEGIN
	ALTER TABLE DBO.CreateNewSingleTransactionData ADD InvoiceNumber VARCHAR(20) NULL
END