-- TO BE RUN ON PRIMARY SERVER COREAUTH DATABASE

Begin   Tran 
--commit 
--rollback 
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 11131
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 336878
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 412729
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 579552
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 664310
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 841349
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 864114
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 873268
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 945731
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 1013701
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 1069265
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 1157572
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 1665352
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 1841142
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 1877109
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 1958254
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 1997732
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 2077434
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 2142845
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 2279693
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 2358566
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 2531177
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 2652061
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 2996653
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 4185659
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 4383406
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 4445379
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 4502181
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 4854985
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 4891097
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 4915235
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 4916930
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 4953232
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 9253630
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 10080333
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 11898737
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 11915083
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 12321119
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 13150694
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 13402663
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 244248
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 588281
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 659234
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 1255358
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 1356278
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 1508643
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 1553468
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 1722050
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 1841625
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 14111857
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 14886165
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 16534502
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 17003098
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 17482733
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 17966168
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 18023824
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 18068429
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 18260066
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 18274232
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 18537769
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 19611584
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 20444752
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 20450010
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 20773301
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 20966132
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 20975013
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 21467212
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 21578298

update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 244248
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 588281
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 659234
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 1255358
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 1356278
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 1508643
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 1722050
update    top(1)  bsegment_primary     set    DateOfLastDelinquent = null  , systemstatus  =2   where   acctid  = 1841625