-- TO BE RUN ON PRIMARY SERVER ONLY

USE CCGS_CoreIssue
GO

BEGIN TRANSACTION
--COMMIT TRANSACTION
--ROLLBACK TRANSACTION


-- 168 rows

UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 69046
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 171415
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 245534
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 255780
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 401591
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 420911
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 484854
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 560818
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 608807
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 661196
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 839022
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 847069
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 934281
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 1031139
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 1040776
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 1068654
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 1077627
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 1087682
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 1087864
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 1104990
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 1176979
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 1179650
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 1182008
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 1256843
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 1279374
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 1295264
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 1299962
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 1332282
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 1345131
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 1347824
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 1351742
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 1375523
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 1398563
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 1410501
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 1416950
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 1466247
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 1512722
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 1643207
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 1655551
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 1694707
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 1773717
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 1834633
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 1837118
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 1839192
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 1898958
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 1945472
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 1977284
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 1992780
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 2014248
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 2029224
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 2032409
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 2045535
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 2064493
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 2089527
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 2116716
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 2133483
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 2140601
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 2144035
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 2157783
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 2158221
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 2186522
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 2214113
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 2223617
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 2301987
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 2340443
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 2348892
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 2394238
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 2473193
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 2667954
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 2711791
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 2730929
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 2805367
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 2827132
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 2828625
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 2831268
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 2946237
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 2967087
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 2974725
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 3265718
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 3558766
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 3742895
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 3865415
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 3876024
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 3920877
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 4086513
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 4117539
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 4118316
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 4305627
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 4307559
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 4323634
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 4325880
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 4387037
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 4506682
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 4560658
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 4674553
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 4737575
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 4793052
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 4861070
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 4912086
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 4947016
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 4955487
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 5584296
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 5638892
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 6087428
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 6309749
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 7576703
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 7849117
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 9418296
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 9425304
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 9426111
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 9450261
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 9592312
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 10196493
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 10291484
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 10320610
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 10647948
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 10784782
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 10806307
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 10814661
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 11011919
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 11080496
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 11450369
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 11525031
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 11910570
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 11937056
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 12296940
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 12341360
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 12374468
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 12801821
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 12803801
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 12827023
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 12882000
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 12938548
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 12959269
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 12984961
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 13172498
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 13594052
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 13855144
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 13881241
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 14106167
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 14112083
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 14253726
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 14262184
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 14273992
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 15224296
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 15251270
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 15290957
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 15451195
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 15568952
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 15691408
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 15699287
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 15715683
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 15923493
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 15937319
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 16060972
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 16418321
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 16550691
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 16579570
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 16822713
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 16857364
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 16947683
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 16954859
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 17002879
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 17304886
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 17960022
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 17979079
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 18088326
UPDATE TOP(1) BSegmentCreditCard SET AccountGraceStatus = 'T' WHERE acctId = 18237284