class SetUp:
    InputFile = "E:\\Python\\FileConverter_Miscelleneous\\INPUT"
    ErrorFile = "E:\\Python\\FileConverter_Miscelleneous\\ERROR"
    OutFile = "E:\\Python\\FileConverter_Miscelleneous\\OUT"
    LogFile = "E:\\Python\\FileConverter_Miscelleneous\\LOG"
    ResponseFile = "E:\\Python\\FileConverter_Miscelleneous\\ResponseFile"
    DumpedFile = "E:\\Python\\FileConverter_Miscelleneous\\DumpedFile"
    OutFileNamePrefix = "COOKIE-342791_"
    SheetName = 'CBR population'
    #Columns = ['AccountUUID']
    #DataTypes = ['VARCHAR']
    #Prefix = 'INSERT INTO ##TempRecords (AccountUUID) VALUES ('
    #Columns = ['ACCOUNT_UID', 'CASE_ID', 'BUSINESS_DATE', 'TRANSACTION_CODE', 'LM', 'TXN_DESC', 'TXN_AMT', 'TXN_ID']
    #DataTypes = ['VARCHAR', 'VARCHAR', 'DATETIME', 'VARCHAR', 'VARCHAR', 'VARCHAR', 'MONEY', 'DECIMAL']
    #Prefix = 'INSERT INTO ##CBRWriteOffPosting_COOKIE-320533 (person_id, account_id, effective_date, transaction_amount, bank_account, transaction_code) VALUES ('
    Columns = ['dispute_id','dispute_amount','account_uuid','px_create_date_time','transaction_amount','transaction_date','clearing_date','PC_date', 'PC_amount_Final','py_resolved_date']
    DataTypes = ['VARCHAR', 'MONEY', 'VARCHAR', 'DATETIME', 'MONEY', 'DATETIME', 'DATETIME', 'DATETIME', 'MONEY', 'DATETIME']
    Prefix = 'INSERT INTO ##TempRawData (DisputeID, DisputeAmount, AccountUUID, px_create_date_time, TransactionAmount, TransactionDate, ClearingDate, PCDate, PCAmount, PCResolvedDate) VALUES ('
    #Columns = ['Account id', 'Customer ID', 'Payment Effective Date', 'Payment Amount']
    #DataTypes = ['VARCHAR', 'VARCHAR', 'DATETIME', 'MONEY']
    #Prefix = 'INSERT INTO ##TempRawData (AccountUUID, ClientID, ClearingDate, DisputeAmount) VALUES ('
    Suffix = ')'
    ReadAllFiles = 0
