
IF NOT EXISTS (SELECT TOP 1 1 FROM SYS.sequences WHERE NAME = 'FeatureStepDataStore_ID')
BEGIN
	CREATE SEQUENCE dbo.FeatureStepDataStore_ID
		START WITH 1
		INCREMENT BY 1
		MINVALUE 1
		NO MAXVALUE
		CACHE 20
END